Repository OCA/project, pull requests merged in 2018-12, with the labels that each got.

#452 [12.0][ADD] project_role: role-based project roster
  project_role/README.rst
  project_role/__init__.py
  project_role/__manifest__.py
  project_role/models/__init__.py
  project_role/models/project_assignment.py
  project_role/models/project_project.py
  project_role/models/project_role.py
  project_role/readme/CONFIGURE.rst
  project_role/readme/CONTRIBUTORS.rst
  project_role/readme/DESCRIPTION.rst
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/index.html
  project_role/tests/__init__.py
  project_role/tests/test_project_role.py
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
Labels: approved

#460 [ADD] project_category: module to categorize projects
  project_category/README.rst
  project_category/__init__.py
  project_category/__manifest__.py
  project_category/i18n/es.po
  project_category/i18n/project_category.pot
  project_category/models/__init__.py
  project_category/models/project_project.py
  project_category/models/project_type.py
  project_category/readme/CONTRIBUTORS.rst
  project_category/readme/DESCRIPTION.rst
  project_category/readme/USAGE.rst
  project_category/security/ir.model.access.csv
  project_category/static/description/index.html
  project_category/views/project_project_views.xml
  project_category/views/project_type_views.xml
Labels: approved, needs review

#445 12.0 mig project_task_pull_request
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/readme/CONTRIBUTORS.rst
  project_task_pull_request/readme/DESCRIPTION.rst
  project_task_pull_request/readme/USAGE.rst
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
Labels: approved, ready to merge
