Repository OCA/project, pull requests merged in 2019-04, with the labels that each got.

#488 [12.0][IMP] Don't allow create-and-edit on assignments
  project_role/__manifest__.py
  project_role/views/project_assignment.xml
  project_role/views/project_role.xml
Labels: approved

#490 [12.0][IMP] Don't allow quick-create on assignments
  project_role/__manifest__.py
  project_role/views/project_assignment.xml
  project_role/views/project_role.xml
Labels: approved

#494 [ADD][12.0]project_parent_task_filter
  project_parent_task_filter/README.rst
  project_parent_task_filter/__init__.py
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
  project_parent_task_filter/readme/USAGE.rst
  project_parent_task_filter/static/description/icon.png
  project_parent_task_filter/views/project_task.xml
Labels: approved

#463 [11.0][IMP] project_category: Project type in task and parent types
  project_category/README.rst
  project_category/__manifest__.py
  project_category/models/__init__.py
  project_category/models/project_project.py
  project_category/models/project_task.py
  project_category/models/project_type.py
  project_category/readme/CONTRIBUTORS.rst
  project_category/readme/DESCRIPTION.rst
  project_category/readme/USAGE.rst
  project_category/tests/__init__.py
  project_category/tests/test_project_category.py
  project_category/views/project_project_views.xml
  project_category/views/project_task_views.xml
  project_category/views/project_type_views.xml
Labels: approved, ready to merge

#470 [12.0] [MIG] project_category
  project_category/README.rst
  project_category/__init__.py
  project_category/__manifest__.py
  project_category/i18n/es.po
  project_category/i18n/project_category.pot
  project_category/models/__init__.py
  project_category/models/project_project.py
  project_category/models/project_task.py
  project_category/models/project_type.py
  project_category/readme/CONTRIBUTORS.rst
  project_category/readme/DESCRIPTION.rst
  project_category/readme/USAGE.rst
  project_category/security/ir.model.access.csv
  project_category/static/description/index.html
  project_category/tests/__init__.py
  project_category/tests/test_project_category.py
  project_category/views/project_project_views.xml
  project_category/views/project_task_views.xml
  project_category/views/project_type_views.xml
Labels: approved, ready to merge

#498 [12.0][IMP] project_timeline - Enable subtasks
  project_timeline/__manifest__.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/views/project_task_view.xml
Labels: approved, needs review, ready to merge

#499 [12.0][IMP]project_parent_task_filter-Add-group
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/USAGE.rst
  project_parent_task_filter/views/project_task.xml
Labels: approved, ready to merge

#503 [Add] Project Status Module
  project_status/README.rst
  project_status/__init__.py
  project_status/__manifest__.py
  project_status/data/data.xml
  project_status/models/__init__.py
  project_status/models/project.py
  project_status/models/project_status.py
  project_status/security/ir.model.access.csv
  project_status/static/description/icon.png
  project_status/views/project.xml
  project_status/views/project_status.xml
Labels: approved, needs review, ready to merge

#508 [12.0][IMP]project_parent_task_filter Add subtask number in kanban view
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
  project_parent_task_filter/readme/USAGE.rst
  project_parent_task_filter/views/project_task.xml
Labels: approved

#449 [ADD] project_hr: Link HR with project
  project_hr/README.rst
  project_hr/__init__.py
  project_hr/__manifest__.py
  project_hr/i18n/es.po
  project_hr/i18n/project_hr.pot
  project_hr/models/__init__.py
  project_hr/models/project_project.py
  project_hr/models/project_task.py
  project_hr/models/res_users.py
  project_hr/readme/CONFIGURE.rst
  project_hr/readme/DESCRIPTION.rst
  project_hr/readme/ROADMAP.rst
  project_hr/readme/USAGE.rst
  project_hr/static/description/icon.png
  project_hr/static/description/index.html
  project_hr/tests/__init__.py
  project_hr/tests/test_project_hr.py
  project_hr/views/project_project_views.xml
  project_hr/views/project_task_views.xml
Labels: approved, needs review

#507 [MIG] project_task_digitized_signature: Migration to 11.0
  project_task_digitized_signature/README.rst
  project_task_digitized_signature/__init__.py
  project_task_digitized_signature/__manifest__.py
  project_task_digitized_signature/i18n/ar.po
  project_task_digitized_signature/i18n/ca.po
  project_task_digitized_signature/i18n/de.po
  project_task_digitized_signature/i18n/el.po
  project_task_digitized_signature/i18n/es.po
  project_task_digitized_signature/i18n/es_CR.po
  project_task_digitized_signature/i18n/es_MX.po
  project_task_digitized_signature/i18n/es_VE.po
  project_task_digitized_signature/i18n/fi.po
  project_task_digitized_signature/i18n/fr.po
  project_task_digitized_signature/i18n/gl.po
  project_task_digitized_signature/i18n/hr.po
  project_task_digitized_signature/i18n/hr_HR.po
  project_task_digitized_signature/i18n/hu.po
  project_task_digitized_signature/i18n/it.po
  project_task_digitized_signature/i18n/ja.po
  project_task_digitized_signature/i18n/lt.po
  project_task_digitized_signature/i18n/lv.po
  project_task_digitized_signature/i18n/mk.po
  project_task_digitized_signature/i18n/mn.po
  project_task_digitized_signature/i18n/nl.po
  project_task_digitized_signature/i18n/pl.po
  project_task_digitized_signature/i18n/project_task_digitized_signature.pot
  project_task_digitized_signature/i18n/pt.po
  project_task_digitized_signature/i18n/pt_BR.po
  project_task_digitized_signature/i18n/pt_PT.po
  project_task_digitized_signature/i18n/ro.po
  project_task_digitized_signature/i18n/sl.po
  project_task_digitized_signature/i18n/sv.po
  project_task_digitized_signature/i18n/tr.po
  project_task_digitized_signature/i18n/uk.po
  project_task_digitized_signature/i18n/zh_CN.po
  project_task_digitized_signature/models/__init__.py
  project_task_digitized_signature/models/project.py
  project_task_digitized_signature/readme/CONTRIBUTORS.rst
  project_task_digitized_signature/readme/DESCRIPTION.rst
  project_task_digitized_signature/readme/INSTALL.rst
  project_task_digitized_signature/readme/USAGE.rst
  project_task_digitized_signature/report/project_task_report.xml
  project_task_digitized_signature/static/description/icon.png
  project_task_digitized_signature/static/description/index.html
  project_task_digitized_signature/tests/__init__.py
  project_task_digitized_signature/tests/test_project_task_digitized_signature.py
  project_task_digitized_signature/views/project_task_views.xml
Labels: approved

#514 [10.0][FIX] project_model_to_task compute method name
  project_model_to_task/__manifest__.py
  project_model_to_task/models/project.py
Labels: approved

#517 [FIX][10.0] sale_order_project Redefining warning
  sale_order_project/models/sale.py
  sale_order_project/tests/test_sale_order_project.py
Labels: needs review

#519 [FIX][10.0] project_recalculate fix api.one & Redefining
  project_recalculate/models/project_task.py
  project_recalculate/models/resource_calendar.py
  project_recalculate/tests/test_project_project.py
Labels: needs review

#472 [IMP][11.0][project_task_material_stock] Improve the workflow to consume materials in project task using a stock picking
  project_task_material_stock/README.rst
  project_task_material_stock/__manifest__.py
  project_task_material_stock/data/data.xml
  project_task_material_stock/models/project_task.py
  project_task_material_stock/views/project_task_view.xml
Labels: approved, ready to merge
