Repository OCA/project, pull requests merged in 2019-05, with the labels that each got.

#524 [FIX][11.0] project_timeline_critical_path fix whitespaces and strict function
  project_timeline_critical_path/static/src/js/backend.js
Labels: approved

#505 [ADD] Project Tag Module
  project_tag/README.rst
  project_tag/__init__.py
  project_tag/__manifest__.py
  project_tag/models/__init__.py
  project_tag/models/project.py
  project_tag/readme/CONTRIBUTORS.rst
  project_tag/readme/DESCRIPTION.rst
  project_tag/readme/USAGE.rst
  project_tag/static/description/icon.png
  project_tag/views/project.xml
Labels: approved, needs review, ready to merge

#501 [ADD] Project Milestone Module
  project_milestone/README.rst
  project_milestone/__init__.py
  project_milestone/__manifest__.py
  project_milestone/models/__init__.py
  project_milestone/models/project.py
  project_milestone/models/project_milestone.py
  project_milestone/models/project_task.py
  project_milestone/readme/CONTRIBUTORS.rst
  project_milestone/readme/DESCRIPTION.rst
  project_milestone/readme/USAGE.rst
  project_milestone/security/ir.model.access.csv
  project_milestone/static/description/icon.png
  project_milestone/tests/__init__.py
  project_milestone/tests/test_project_milestone.py
  project_milestone/views/project.xml
  project_milestone/views/project_milestone.xml
  project_milestone/views/project_task.xml
Labels: needs review

#504 [ADD] Project Template Module
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
Labels: approved, needs review

#513 [12.0][FIX] project_task_add_very_high: move priority widget before title
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/views/project_task_view.xml
Labels: approved

#536 [ADD] project_template_milestone
  project_template_milestone/README.rst
  project_template_milestone/__init__.py
  project_template_milestone/__manifest__.py
  project_template_milestone/models/__init__.py
  project_template_milestone/models/project.py
  project_template_milestone/readme/CONTRIBUTORS.rst
  project_template_milestone/readme/DESCRIPTION.rst
  project_template_milestone/readme/USAGE.rst
  project_template_milestone/static/description/icon.png
  project_template_milestone/tests/__init__.py
  project_template_milestone/tests/test_project_template.py
Labels: approved, needs review

#535 [12.0] Add project tags on search view
  project_tag/views/project.xml
Labels: approved, ready to merge

#541 [12.0][IMP] project_role: improve usability
  project_role/README.rst
  project_role/__manifest__.py
  project_role/i18n/project_role.pot
  project_role/readme/CONFIGURE.rst
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/index.html
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
Labels: approved
