Repository OCA/project, pull requests merged in 2019-09, with the labels that each got.

#571 [ADD] project_stock_request
  oca_dependencies.txt
  project_stock_request/README.rst
  project_stock_request/__init__.py
  project_stock_request/__manifest__.py
  project_stock_request/models/__init__.py
  project_stock_request/models/project.py
  project_stock_request/models/project_task.py
  project_stock_request/models/stock_request_order.py
  project_stock_request/readme/CONTRIBUTORS.rst
  project_stock_request/readme/CREDITS.rst
  project_stock_request/readme/DESCRIPTION.rst
  project_stock_request/readme/USAGE.rst
  project_stock_request/security/ir.model.access.csv
  project_stock_request/static/description/icon.png
  project_stock_request/views/project_task_views.xml
  project_stock_request/views/project_views.xml
  project_stock_request/views/stock_request_order_views.xml
Labels: approved, enhancement, needs review

#558 project_status UX: add default_group_by and group_expand
  project_status/models/project.py
  project_status/views/project.xml
Labels: approved, enhancement, needs review

#573 [12.0][FIX] project_hr: domain on field breaks other modules
  project_hr/models/project_task.py
  project_hr/readme/CONTRIBUTORS.rst
  project_hr/views/project_task_views.xml
Labels: bug, needs review

#550 [12.0][IMP] project_role: revert manual options in favor of web_m2x_options
  project_role/README.rst
  project_role/readme/CONFIGURE.rst
  project_role/static/description/index.html
  project_role/views/project_assignment.xml
  project_role/views/project_role.xml
Labels: approved, ready to merge

#570 [12.0][ADD] project_task_project_required
  project_task_project_required/__init__.py
  project_task_project_required/__manifest__.py
  project_task_project_required/models/__init__.py
  project_task_project_required/models/project_task.py
  project_task_project_required/models/res_company.py
  project_task_project_required/models/res_config_settings.py
  project_task_project_required/readme/CONFIGURE.rst
  project_task_project_required/readme/CONTRIBUTORS.rst
  project_task_project_required/readme/DESCRIPTION.rst
  project_task_project_required/tests/__init__.py
  project_task_project_required/tests/test_project_task_project_required.py
  project_task_project_required/views/project_task.xml
  project_task_project_required/views/res_config_settings.xml
Labels: approved, needs review, ready to merge

#569 [12.0][ADD] project_deadline
  project_deadline/README.rst
  project_deadline/__init__.py
  project_deadline/__manifest__.py
  project_deadline/models/__init__.py
  project_deadline/models/project_project.py
  project_deadline/models/project_task.py
  project_deadline/readme/CONTRIBUTORS.rst
  project_deadline/readme/DESCRIPTION.rst
  project_deadline/readme/USAGE.rst
  project_deadline/static/description/index.html
  project_deadline/tests/__init__.py
  project_deadline/tests/test_project_deadline.py
  project_deadline/views/project_project_view.xml
  project_deadline/views/project_task_view.xml
Labels: approved, needs review, ready to merge
