Repository OCA/project, pull requests merged in 2020-10, with the labels that each got.

#716 [13.0][UPD] Eficent -> ForgeFlow
  project_task_dependency/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#711 [10.0] project_issue_code: included parent filter_domain
  project_issue_code/views/project_issue_view.xml
Labels: bot is merging ⏳

#713 [IMP] project_category: add code field
  project_category/models/project_type.py
  project_category/readme/CONTRIBUTORS.rst
  project_category/views/project_type_views.xml
Labels: bot is merging ⏳

#704 [13.0][MIG] project_milestone
  project_milestone/README.rst
  project_milestone/__init__.py
  project_milestone/__manifest__.py
  project_milestone/i18n/de.po
  project_milestone/i18n/es.po
  project_milestone/i18n/es_ES.po
  project_milestone/i18n/it.po
  project_milestone/i18n/project_milestone.pot
  project_milestone/i18n/sl.po
  project_milestone/models/__init__.py
  project_milestone/models/project.py
  project_milestone/models/project_milestone.py
  project_milestone/models/project_task.py
  project_milestone/readme/CONTRIBUTORS.rst
  project_milestone/readme/DESCRIPTION.rst
  project_milestone/readme/USAGE.rst
  project_milestone/security/ir.model.access.csv
  project_milestone/static/description/icon.png
  project_milestone/static/description/index.html
  project_milestone/tests/__init__.py
  project_milestone/tests/test_project_milestone.py
  project_milestone/views/project.xml
  project_milestone/views/project_milestone.xml
  project_milestone/views/project_task.xml
  setup/project_milestone/odoo/addons/project_milestone
  setup/project_milestone/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#723 [12.0][IMP] project_task_code: allow to import Task Numbers
  project_task_code/models/project_task.py
  project_task_code/readme/USAGE.rst
  project_task_code/views/project_view.xml
Labels: approved, bot is merging ⏳

#729 [14.0][MIG] project_task_add_very_high
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/hooks.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/readme/CONTRIBUTORS.rst
  project_task_add_very_high/readme/DESCRIPTION.rst
  project_task_add_very_high/readme/USAGE.rst
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#730 [14.0][MIG] project_task_dependency
  project_task_dependency/README.rst
  project_task_dependency/__init__.py
  project_task_dependency/__manifest__.py
  project_task_dependency/i18n/ar.po
  project_task_dependency/i18n/ca.po
  project_task_dependency/i18n/de.po
  project_task_dependency/i18n/el.po
  project_task_dependency/i18n/es.po
  project_task_dependency/i18n/es_CR.po
  project_task_dependency/i18n/es_MX.po
  project_task_dependency/i18n/es_VE.po
  project_task_dependency/i18n/fi.po
  project_task_dependency/i18n/fr.po
  project_task_dependency/i18n/gl.po
  project_task_dependency/i18n/hr.po
  project_task_dependency/i18n/hr_HR.po
  project_task_dependency/i18n/hu.po
  project_task_dependency/i18n/it.po
  project_task_dependency/i18n/ja.po
  project_task_dependency/i18n/lt.po
  project_task_dependency/i18n/lv.po
  project_task_dependency/i18n/mk.po
  project_task_dependency/i18n/mn.po
  project_task_dependency/i18n/nl.po
  project_task_dependency/i18n/nl_NL.po
  project_task_dependency/i18n/pl.po
  project_task_dependency/i18n/project_task_dependency.pot
  project_task_dependency/i18n/pt.po
  project_task_dependency/i18n/pt_BR.po
  project_task_dependency/i18n/pt_PT.po
  project_task_dependency/i18n/ro.po
  project_task_dependency/i18n/sl.po
  project_task_dependency/i18n/sv.po
  project_task_dependency/i18n/tr.po
  project_task_dependency/i18n/uk.po
  project_task_dependency/i18n/zh_CN.po
  project_task_dependency/models/__init__.py
  project_task_dependency/models/project_project.py
  project_task_dependency/models/project_task.py
  project_task_dependency/models/project_task_copy_map.py
  project_task_dependency/readme/CONTRIBUTORS.rst
  project_task_dependency/readme/DESCRIPTION.rst
  project_task_dependency/readme/USAGE.rst
  project_task_dependency/security/ir.model.access.csv
  project_task_dependency/static/description/icon.png
  project_task_dependency/static/description/index.html
  project_task_dependency/tests/__init__.py
  project_task_dependency/tests/test_project_task_dependency.py
  project_task_dependency/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#701 [13.0][FIX] project_task_dependency: recursion error
  project_task_dependency/models/project_task.py
  project_task_dependency/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳
