Repository OCA/project, pull requests merged in 2020-11, with the labels that each got.

#735 [14.0][MIG] project_category
  project_category/README.rst
  project_category/__init__.py
  project_category/__manifest__.py
  project_category/i18n/ca.po
  project_category/i18n/de.po
  project_category/i18n/es.po
  project_category/i18n/project_category.pot
  project_category/models/__init__.py
  project_category/models/project_project.py
  project_category/models/project_task.py
  project_category/models/project_type.py
  project_category/readme/CONTRIBUTORS.rst
  project_category/readme/DESCRIPTION.rst
  project_category/readme/USAGE.rst
  project_category/security/ir.model.access.csv
  project_category/static/description/icon.png
  project_category/static/description/index.html
  project_category/tests/__init__.py
  project_category/tests/test_project_category.py
  project_category/views/project_project_views.xml
  project_category/views/project_task_views.xml
  project_category/views/project_type_views.xml
  setup/project_category/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#726 [14.0][MIG] project_parent_task_filter
  project_parent_task_filter/README.rst
  project_parent_task_filter/__init__.py
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/i18n/ca.po
  project_parent_task_filter/i18n/de.po
  project_parent_task_filter/i18n/es.po
  project_parent_task_filter/i18n/es_ES.po
  project_parent_task_filter/i18n/project_parent_task_filter.pot
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
  project_parent_task_filter/readme/USAGE.rst
  project_parent_task_filter/static/description/icon.png
  project_parent_task_filter/static/description/index.html
  project_parent_task_filter/views/project_task.xml
  setup/project_parent_task_filter/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#739 [UPD] Brainbean Apps => CorporateHub
  project_hr/README.rst
  project_hr/readme/CONTRIBUTORS.rst
  project_key/README.rst
  project_key/readme/CONTRIBUTORS.rst
  project_list/README.rst
  project_list/__manifest__.py
  project_list/readme/CONTRIBUTORS.rst
  project_role/README.rst
  project_role/__manifest__.py
  project_role/readme/CONTRIBUTORS.rst
  project_task_code/README.rst
  project_task_code/readme/CONTRIBUTORS.rst
  project_task_project_required/README.rst
  project_task_project_required/__manifest__.py
  project_task_project_required/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#743 [UPD] Brainbean Apps => CorporateHub
  project_hr/README.rst
  project_hr/readme/CONTRIBUTORS.rst
  project_key/README.rst
  project_key/readme/CONTRIBUTORS.rst
  project_list/README.rst
  project_list/__manifest__.py
  project_list/readme/CONTRIBUTORS.rst
  project_role/README.rst
  project_role/__manifest__.py
  project_role/readme/CONTRIBUTORS.rst
  project_task_code/README.rst
  project_task_code/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#741 [12.0][FIX] project_key: avoid index out of range error
  project_key/models/project_project.py
Labels: approved, bot is merging ⏳

#740 [13.0][FIX] project_key: avoid index out of range error
  project_key/models/project_project.py
Labels: approved, bot is merging ⏳

#731 [IMP] project_task_code: support already initialized code column
  project_task_code/hooks.py
Labels: approved, bot is merging ⏳, needs review

#745 [13.0][FIX] project_category: allow copying of project type_id
  project_category/models/project_project.py
Labels: approved, bot is merging ⏳

#742 [11.0][FIX] project_key: avoid index out of range error
  project_key/models/project_project.py
Labels: approved, bot is merging ⏳

#755 [14.0][MIG] project_task_default_stage: Migration to 14.0
  project_task_default_stage/README.rst
  project_task_default_stage/__init__.py
  project_task_default_stage/__manifest__.py
  project_task_default_stage/data/project_data.xml
  project_task_default_stage/i18n/bg.po
  project_task_default_stage/i18n/ca.po
  project_task_default_stage/i18n/cs_CZ.po
  project_task_default_stage/i18n/de.po
  project_task_default_stage/i18n/el_GR.po
  project_task_default_stage/i18n/en.po
  project_task_default_stage/i18n/es.po
  project_task_default_stage/i18n/es_CO.po
  project_task_default_stage/i18n/es_MX.po
  project_task_default_stage/i18n/fi.po
  project_task_default_stage/i18n/fr.po
  project_task_default_stage/i18n/gl.po
  project_task_default_stage/i18n/hr.po
  project_task_default_stage/i18n/hu.po
  project_task_default_stage/i18n/it.po
  project_task_default_stage/i18n/nb.po
  project_task_default_stage/i18n/nb_NO.po
  project_task_default_stage/i18n/nl.po
  project_task_default_stage/i18n/nl_NL.po
  project_task_default_stage/i18n/pl.po
  project_task_default_stage/i18n/project_task_default_stage.pot
  project_task_default_stage/i18n/pt.po
  project_task_default_stage/i18n/pt_BR.po
  project_task_default_stage/i18n/pt_PT.po
  project_task_default_stage/i18n/ru.po
  project_task_default_stage/i18n/sk.po
  project_task_default_stage/i18n/sl.po
  project_task_default_stage/i18n/tr.po
  project_task_default_stage/i18n/zh_CN.po
  project_task_default_stage/models/__init__.py
  project_task_default_stage/models/project.py
  project_task_default_stage/models/project_task_type.py
  project_task_default_stage/readme/CONFIGURE.rst
  project_task_default_stage/readme/CONTRIBUTORS.rst
  project_task_default_stage/readme/DESCRIPTION.rst
  project_task_default_stage/static/description/icon.png
  project_task_default_stage/static/description/index.html
  project_task_default_stage/tests/__init__.py
  project_task_default_stage/tests/test_project_task_default_stage.py
  project_task_default_stage/views/project_view.xml
  setup/project_task_default_stage/odoo/addons/project_task_default_stage
  setup/project_task_default_stage/setup.py
Labels: approved, bot is merging ⏳
