Repository OCA/project, pull requests merged in 2020-06, with the labels that each got.

#681 13.0 mig project role
  project_role/README.rst
  project_role/__init__.py
  project_role/__manifest__.py
  project_role/i18n/de.po
  project_role/i18n/project_role.pot
  project_role/i18n/sl.po
  project_role/migrations/12.0.2.1.0/pre-migration.py
  project_role/models/__init__.py
  project_role/models/project_assignment.py
  project_role/models/project_project.py
  project_role/models/project_role.py
  project_role/models/res_company.py
  project_role/models/res_config_settings.py
  project_role/readme/CONFIGURE.rst
  project_role/readme/CONTRIBUTORS.rst
  project_role/readme/DESCRIPTION.rst
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/icon.png
  project_role/static/description/index.html
  project_role/tests/__init__.py
  project_role/tests/test_project_role.py
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
  setup/project_role/odoo/addons/project_role
  setup/project_role/setup.py
Labels: approved, bot is merging ⏳

#683 [FIX] project_custom_info: mode=custom_info
  project_custom_info/views/project_project_view.xml
Labels: approved, bot is merging ⏳

#638 [13.0][MIG] project_task_pull_request
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/readme/CONTRIBUTORS.rst
  project_task_pull_request/readme/DESCRIPTION.rst
  project_task_pull_request/readme/USAGE.rst
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
  setup/project_task_pull_request/odoo/addons/project_task_pull_request
  setup/project_task_pull_request/setup.py
Labels: bot is merging ⏳

#673 [MIG] project_task_send_by_mail: Migration to 13.0
  oca_dependencies.txt
  project_task_send_by_mail/README.rst
  project_task_send_by_mail/__init__.py
  project_task_send_by_mail/__manifest__.py
  project_task_send_by_mail/data/task_template.xml
  project_task_send_by_mail/i18n/ar.po
  project_task_send_by_mail/i18n/ca.po
  project_task_send_by_mail/i18n/de.po
  project_task_send_by_mail/i18n/el.po
  project_task_send_by_mail/i18n/es.po
  project_task_send_by_mail/i18n/es_CR.po
  project_task_send_by_mail/i18n/es_MX.po
  project_task_send_by_mail/i18n/es_VE.po
  project_task_send_by_mail/i18n/fi.po
  project_task_send_by_mail/i18n/fr.po
  project_task_send_by_mail/i18n/gl.po
  project_task_send_by_mail/i18n/hr.po
  project_task_send_by_mail/i18n/hr_HR.po
  project_task_send_by_mail/i18n/hu.po
  project_task_send_by_mail/i18n/it.po
  project_task_send_by_mail/i18n/ja.po
  project_task_send_by_mail/i18n/lt.po
  project_task_send_by_mail/i18n/lv.po
  project_task_send_by_mail/i18n/mk.po
  project_task_send_by_mail/i18n/mn.po
  project_task_send_by_mail/i18n/nl.po
  project_task_send_by_mail/i18n/pl.po
  project_task_send_by_mail/i18n/project_task_send_by_mail.pot
  project_task_send_by_mail/i18n/pt.po
  project_task_send_by_mail/i18n/pt_BR.po
  project_task_send_by_mail/i18n/pt_PT.po
  project_task_send_by_mail/i18n/ro.po
  project_task_send_by_mail/i18n/sl.po
  project_task_send_by_mail/i18n/sv.po
  project_task_send_by_mail/i18n/tr.po
  project_task_send_by_mail/i18n/uk.po
  project_task_send_by_mail/i18n/zh_CN.po
  project_task_send_by_mail/models/__init__.py
  project_task_send_by_mail/models/project.py
  project_task_send_by_mail/readme/CONTRIBUTORS.rst
  project_task_send_by_mail/readme/DESCRIPTION.rst
  project_task_send_by_mail/readme/USAGE.rst
  project_task_send_by_mail/static/description/icon.png
  project_task_send_by_mail/static/description/index.html
  project_task_send_by_mail/tests/__init__.py
  project_task_send_by_mail/tests/test_project_task_send_by_mail.py
  project_task_send_by_mail/views/project_task_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#664 [12.0] porting project_task_digitized_signature
  project_task_digitized_signature/README.rst
  project_task_digitized_signature/__init__.py
  project_task_digitized_signature/__manifest__.py
  project_task_digitized_signature/i18n/ar.po
  project_task_digitized_signature/i18n/ca.po
  project_task_digitized_signature/i18n/de.po
  project_task_digitized_signature/i18n/el.po
  project_task_digitized_signature/i18n/es.po
  project_task_digitized_signature/i18n/es_CR.po
  project_task_digitized_signature/i18n/es_MX.po
  project_task_digitized_signature/i18n/es_VE.po
  project_task_digitized_signature/i18n/fi.po
  project_task_digitized_signature/i18n/fr.po
  project_task_digitized_signature/i18n/gl.po
  project_task_digitized_signature/i18n/hr.po
  project_task_digitized_signature/i18n/hr_HR.po
  project_task_digitized_signature/i18n/hu.po
  project_task_digitized_signature/i18n/it.po
  project_task_digitized_signature/i18n/ja.po
  project_task_digitized_signature/i18n/lt.po
  project_task_digitized_signature/i18n/lv.po
  project_task_digitized_signature/i18n/mk.po
  project_task_digitized_signature/i18n/mn.po
  project_task_digitized_signature/i18n/nl.po
  project_task_digitized_signature/i18n/pl.po
  project_task_digitized_signature/i18n/project_task_digitized_signature.pot
  project_task_digitized_signature/i18n/pt.po
  project_task_digitized_signature/i18n/pt_BR.po
  project_task_digitized_signature/i18n/pt_PT.po
  project_task_digitized_signature/i18n/ro.po
  project_task_digitized_signature/i18n/sl.po
  project_task_digitized_signature/i18n/sv.po
  project_task_digitized_signature/i18n/tr.po
  project_task_digitized_signature/i18n/uk.po
  project_task_digitized_signature/i18n/zh_CN.po
  project_task_digitized_signature/models/__init__.py
  project_task_digitized_signature/models/project.py
  project_task_digitized_signature/readme/CONTRIBUTORS.rst
  project_task_digitized_signature/readme/DESCRIPTION.rst
  project_task_digitized_signature/readme/INSTALL.rst
  project_task_digitized_signature/readme/USAGE.rst
  project_task_digitized_signature/report/project_task_report.xml
  project_task_digitized_signature/static/description/icon.png
  project_task_digitized_signature/static/description/index.html
  project_task_digitized_signature/tests/__init__.py
  project_task_digitized_signature/tests/test_project_task_digitized_signature.py
  project_task_digitized_signature/views/project_task_views.xml
  setup/project_task_digitized_signature/odoo/addons/project_task_digitized_signature
  setup/project_task_digitized_signature/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#667 [FIX][13.0] project_category can now be migrated from 11.0 to 13.0
  project_category/views/project_type_views.xml
Labels: approved, bot is merging ⏳

#675 [MIG] project_purchase_link: Migration to 13.0
  project_purchase_link/README.rst
  project_purchase_link/__init__.py
  project_purchase_link/__manifest__.py
  project_purchase_link/i18n/es.po
  project_purchase_link/i18n/project_purchase_link.pot
  project_purchase_link/i18n/sl.po
  project_purchase_link/models/__init__.py
  project_purchase_link/models/project_project.py
  project_purchase_link/readme/CONTRIBUTORS.rst
  project_purchase_link/readme/DESCRIPTION.rst
  project_purchase_link/readme/USAGE.rst
  project_purchase_link/static/description/icon.png
  project_purchase_link/static/description/index.html
  project_purchase_link/tests/__init__.py
  project_purchase_link/tests/test_project_purchase_link.py
  project_purchase_link/views/project_project_view.xml
  setup/project_purchase_link/odoo/addons/project_purchase_link
  setup/project_purchase_link/setup.py
Labels: approved, bot is merging ⏳, ready to merge
