Repository OCA/project, pull requests merged in 2020-05, with the labels that each got.

#656 [13.0][MIG] project_timeline: Migration to 13.0
  oca_dependencies.txt
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_project_demo.xml
  project_timeline/demo/project_task_demo.xml
  project_timeline/i18n/ar.po
  project_timeline/i18n/ca.po
  project_timeline/i18n/de.po
  project_timeline/i18n/el.po
  project_timeline/i18n/es.po
  project_timeline/i18n/es_CR.po
  project_timeline/i18n/es_MX.po
  project_timeline/i18n/es_VE.po
  project_timeline/i18n/fi.po
  project_timeline/i18n/fr.po
  project_timeline/i18n/gl.po
  project_timeline/i18n/hr.po
  project_timeline/i18n/hr_HR.po
  project_timeline/i18n/hu.po
  project_timeline/i18n/it.po
  project_timeline/i18n/ja.po
  project_timeline/i18n/lt.po
  project_timeline/i18n/lv.po
  project_timeline/i18n/mk.po
  project_timeline/i18n/mn.po
  project_timeline/i18n/nl.po
  project_timeline/i18n/nl_NL.po
  project_timeline/i18n/pl.po
  project_timeline/i18n/project_timeline.pot
  project_timeline/i18n/pt.po
  project_timeline/i18n/pt_BR.po
  project_timeline/i18n/pt_PT.po
  project_timeline/i18n/ro.po
  project_timeline/i18n/sl.po
  project_timeline/i18n/sv.po
  project_timeline/i18n/tr.po
  project_timeline/i18n/uk.po
  project_timeline/i18n/zh_CN.po
  project_timeline/models/__init__.py
  project_timeline/models/project_task.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/readme/DESCRIPTION.rst
  project_timeline/readme/USAGE.rst
  project_timeline/static/description/icon.png
  project_timeline/static/description/icon.svg
  project_timeline/static/description/index.html
  project_timeline/static/src/scss/project_timeline.scss
  project_timeline/templates/assets.xml
  project_timeline/tests/__init__.py
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_project_view.xml
  project_timeline/views/project_task_view.xml
  setup/project_timeline/odoo/addons/project_timeline
  setup/project_timeline/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#658 [13.0][MIG] project_timeline_hr_timesheet: Migration to 13.0
  project_timeline_hr_timesheet/README.rst
  project_timeline_hr_timesheet/__init__.py
  project_timeline_hr_timesheet/__manifest__.py
  project_timeline_hr_timesheet/i18n/de.po
  project_timeline_hr_timesheet/i18n/es.po
  project_timeline_hr_timesheet/i18n/project_timeline_hr_timesheet.pot
  project_timeline_hr_timesheet/readme/CONTRIBUTORS.rst
  project_timeline_hr_timesheet/readme/DESCRIPTION.rst
  project_timeline_hr_timesheet/static/description/icon.png
  project_timeline_hr_timesheet/static/description/index.html
  project_timeline_hr_timesheet/static/src/scss/project_timeline_hr_timesheet.scss
  project_timeline_hr_timesheet/templates/assets.xml
  project_timeline_hr_timesheet/views/project_task_view.xml
  setup/project_timeline_hr_timesheet/odoo/addons/project_timeline_hr_timesheet
  setup/project_timeline_hr_timesheet/setup.py
Labels: approved, bot is merging ⏳

#659 [13.0][MIG] project_timeline_task_dependency: Migration to 13.0
  project_timeline_task_dependency/README.rst
  project_timeline_task_dependency/__init__.py
  project_timeline_task_dependency/__manifest__.py
  project_timeline_task_dependency/i18n/de.po
  project_timeline_task_dependency/i18n/es.po
  project_timeline_task_dependency/i18n/project_timeline_task_dependency.pot
  project_timeline_task_dependency/readme/CONTRIBUTORS.rst
  project_timeline_task_dependency/readme/DESCRIPTION.rst
  project_timeline_task_dependency/static/description/icon.png
  project_timeline_task_dependency/static/description/index.html
  project_timeline_task_dependency/static/description/screenshot.png
  project_timeline_task_dependency/views/project_task_view.xml
  setup/project_timeline_task_dependency/odoo/addons/project_timeline_task_dependency
  setup/project_timeline_task_dependency/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#666 [FIX][12.0] project_category can now be migrated from 11.0 to 12.0
  project_category/views/project_type_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#662 [13.0][MIG] project_status
  project_status/README.rst
  project_status/__init__.py
  project_status/__manifest__.py
  project_status/data/data.xml
  project_status/i18n/de.po
  project_status/i18n/es.po
  project_status/i18n/project_status.pot
  project_status/i18n/sl.po
  project_status/models/__init__.py
  project_status/models/project.py
  project_status/models/project_status.py
  project_status/readme/CONTRIBUTORS.rst
  project_status/readme/DESCRIPTION.rst
  project_status/readme/USAGE.rst
  project_status/security/ir.model.access.csv
  project_status/static/description/icon.png
  project_status/views/project.xml
  project_status/views/project_status.xml
Labels: approved, bot is merging ⏳, work in progress

#674 [FIX] 13.0 product_task_material sudo
  project_task_material/tests/common.py
Labels: approved, bot is merging ⏳, ready to merge
