Repository OCA/project, pull requests merged in 2020-09, with the labels that each got.

#705 [Updated] Icons to macth Odoo's design
  project_timeline/static/description/icon.png
  project_timeline/static/description/icon.svg
Labels: approved, bot is merging ⏳, ready to merge

#708 [12.0] FIX project_timesheet_time_control when not using employees
  project_timesheet_time_control/models/account_analytic_line.py
Labels: approved, bot is merging ⏳

#709 [13.0] FIX project_timesheet_time_control when not using employees
  project_timesheet_time_control/models/account_analytic_line.py
Labels: bot is merging ⏳
