Repository OCA/project, pull requests merged in 2020-07, with the labels that each got.

#684 [MIG] project_template: Migration to 13.0
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/es.po
  project_template/i18n/fr.po
  project_template/i18n/it.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/sl.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
Labels: approved, bot is merging ⏳, ready to merge

#689 [11.0][FIX] project_task_material_with_sale_timesheet: The value of super is not returned
  project_task_material_with_sale_timesheet/README.rst
  project_task_material_with_sale_timesheet/models/project_task.py
Labels: approved, bot is merging ⏳

#626 [13.0][MIG] project_stage_state
  project_stage_state/README.rst
  project_stage_state/__init__.py
  project_stage_state/__manifest__.py
  project_stage_state/i18n/ar.po
  project_stage_state/i18n/bg.po
  project_stage_state/i18n/ca.po
  project_stage_state/i18n/de.po
  project_stage_state/i18n/el.po
  project_stage_state/i18n/el_GR.po
  project_stage_state/i18n/es.po
  project_stage_state/i18n/es_CR.po
  project_stage_state/i18n/es_MX.po
  project_stage_state/i18n/es_VE.po
  project_stage_state/i18n/fi.po
  project_stage_state/i18n/fr.po
  project_stage_state/i18n/gl.po
  project_stage_state/i18n/hr.po
  project_stage_state/i18n/hr_HR.po
  project_stage_state/i18n/hu.po
  project_stage_state/i18n/it.po
  project_stage_state/i18n/ja.po
  project_stage_state/i18n/lt.po
  project_stage_state/i18n/lv.po
  project_stage_state/i18n/mk.po
  project_stage_state/i18n/mn.po
  project_stage_state/i18n/nb.po
  project_stage_state/i18n/nb_NO.po
  project_stage_state/i18n/nl.po
  project_stage_state/i18n/nl_NL.po
  project_stage_state/i18n/pl.po
  project_stage_state/i18n/project_stage_state.pot
  project_stage_state/i18n/pt.po
  project_stage_state/i18n/pt_BR.po
  project_stage_state/i18n/pt_PT.po
  project_stage_state/i18n/ro.po
  project_stage_state/i18n/ru.po
  project_stage_state/i18n/sk.po
  project_stage_state/i18n/sl.po
  project_stage_state/i18n/sv.po
  project_stage_state/i18n/tr.po
  project_stage_state/i18n/uk.po
  project_stage_state/i18n/zh_CN.po
  project_stage_state/models/__init__.py
  project_stage_state/models/project_task.py
  project_stage_state/models/project_task_type.py
  project_stage_state/readme/CONFIGURE.rst
  project_stage_state/readme/CONTRIBUTORS.rst
  project_stage_state/readme/DESCRIPTION.rst
  project_stage_state/readme/USAGE.rst
  project_stage_state/security/ir.model.access.csv
  project_stage_state/static/description/icon.png
  project_stage_state/static/description/index.html
  project_stage_state/views/project_view.xml
  setup/project_stage_state/odoo/addons/project_stage_state
  setup/project_stage_state/setup.py
Labels: bot is merging ⏳

#663 [12.0] remove criticalpath from .travis.yml
  .travis.yml
Labels: approved, bot is merging ⏳, ready to merge

#692 Time scheduling group is shown for all
  project_timeline/views/project_project_view.xml
Labels: approved, bot is merging ⏳

#623 [IMP] Search project tasks with code
  project_task_code/models/project_task.py
Labels: approved, bot is merging ⏳

#584 [13.0] Add addons summary table to main README file
  README.md
Labels: bot is merging ⏳

#691 [FIX]field date_assign appear in form view twice
  project_timeline/views/project_task_view.xml
Labels: bot is merging ⏳
