Repository OCA/project, pull requests merged in 2021-03, with the labels that each got.

#703 [13.0][MIG] project_parent module
  project_parent/README.rst
  project_parent/__init__.py
  project_parent/__manifest__.py
  project_parent/demo/project_project_demo.xml
  project_parent/i18n/es.po
  project_parent/i18n/fr.po
  project_parent/i18n/hr.po
  project_parent/i18n/nl_NL.po
  project_parent/i18n/project_parent.pot
  project_parent/i18n/pt_BR.po
  project_parent/i18n/sl.po
  project_parent/models/__init__.py
  project_parent/models/project_project.py
  project_parent/readme/CONTRIBUTORS.rst
  project_parent/readme/DESCRIPTION.rst
  project_parent/readme/USAGE.rst
  project_parent/static/description/icon.png
  project_parent/tests/__init__.py
  project_parent/tests/test_project_parent.py
  project_parent/views/project_parent_views.xml
  setup/project_parent/odoo/addons/project_parent
  setup/project_parent/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#753 [14.0] [MIG] Project_tag
  project_tag/README.rst
  project_tag/__init__.py
  project_tag/__manifest__.py
  project_tag/i18n/he.po
  project_tag/i18n/project_tag.pot
  project_tag/models/__init__.py
  project_tag/models/project.py
  project_tag/readme/CONTRIBUTORS.rst
  project_tag/readme/DESCRIPTION.rst
  project_tag/readme/USAGE.rst
  project_tag/static/description/icon.png
  project_tag/static/description/index.html
  project_tag/views/project.xml
  setup/project_tag/odoo/addons/project_tag
  setup/project_tag/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#770 14.0 mig project key
  project_key/README.rst
  project_key/__init__.py
  project_key/__manifest__.py
  project_key/controllers/__init__.py
  project_key/controllers/main.py
  project_key/hooks.py
  project_key/i18n/de.po
  project_key/i18n/project_key.pot
  project_key/models/__init__.py
  project_key/models/project_project.py
  project_key/models/project_task.py
  project_key/readme/CONTRIBUTORS.rst
  project_key/readme/DESCRIPTION.rst
  project_key/readme/USAGE.rst
  project_key/static/description/icon.png
  project_key/static/description/index.html
  project_key/tests/__init__.py
  project_key/tests/test_common.py
  project_key/tests/test_controller.py
  project_key/tests/test_project.py
  project_key/tests/test_task.py
  project_key/views/project_key_views.xml
  requirements.txt
  setup/project_key/odoo/addons/project_key
  setup/project_key/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#782 [14.0][MIG] project task code
  project_task_code/README.rst
  project_task_code/__init__.py
  project_task_code/__manifest__.py
  project_task_code/data/task_sequence.xml
  project_task_code/hooks.py
  project_task_code/i18n/ar.po
  project_task_code/i18n/bg.po
  project_task_code/i18n/ca.po
  project_task_code/i18n/de.po
  project_task_code/i18n/el.po
  project_task_code/i18n/en.po
  project_task_code/i18n/es.po
  project_task_code/i18n/es_CR.po
  project_task_code/i18n/es_MX.po
  project_task_code/i18n/es_VE.po
  project_task_code/i18n/fi.po
  project_task_code/i18n/fr.po
  project_task_code/i18n/gl.po
  project_task_code/i18n/hr.po
  project_task_code/i18n/hr_HR.po
  project_task_code/i18n/hu.po
  project_task_code/i18n/it.po
  project_task_code/i18n/ja.po
  project_task_code/i18n/lt.po
  project_task_code/i18n/lv.po
  project_task_code/i18n/mk.po
  project_task_code/i18n/mn.po
  project_task_code/i18n/nl.po
  project_task_code/i18n/nl_NL.po
  project_task_code/i18n/pl.po
  project_task_code/i18n/project_task_code.pot
  project_task_code/i18n/pt.po
  project_task_code/i18n/pt_BR.po
  project_task_code/i18n/pt_PT.po
  project_task_code/i18n/ro.po
  project_task_code/i18n/sk.po
  project_task_code/i18n/sl.po
  project_task_code/i18n/sv.po
  project_task_code/i18n/tr.po
  project_task_code/i18n/uk.po
  project_task_code/i18n/zh_CN.po
  project_task_code/models/__init__.py
  project_task_code/models/project_task.py
  project_task_code/readme/CONFIGURE.rst
  project_task_code/readme/CONTRIBUTORS.rst
  project_task_code/readme/DESCRIPTION.rst
  project_task_code/readme/USAGE.rst
  project_task_code/static/description/icon.png
  project_task_code/static/description/index.html
  project_task_code/tests/__init__.py
  project_task_code/tests/test_project_task_code.py
  project_task_code/views/project_view.xml
  setup/project_task_code/odoo/addons/project_task_code
  setup/project_task_code/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#796 [11.0] [MIG] project_list: Backport from 13.0 to 11.0
  project_list/README.rst
  project_list/__init__.py
  project_list/__manifest__.py
  project_list/i18n/de.po
  project_list/i18n/project_list.pot
  project_list/readme/CONTRIBUTORS.rst
  project_list/readme/DESCRIPTION.rst
  project_list/static/description/icon.png
  project_list/static/description/index.html
  project_list/views/project_project.xml
Labels: approved, bot is merging ⏳

#788 14.0 mig project milestone
  project_milestone/README.rst
  project_milestone/__init__.py
  project_milestone/__manifest__.py
  project_milestone/i18n/de.po
  project_milestone/i18n/es.po
  project_milestone/i18n/es_ES.po
  project_milestone/i18n/it.po
  project_milestone/i18n/project_milestone.pot
  project_milestone/i18n/sl.po
  project_milestone/models/__init__.py
  project_milestone/models/project.py
  project_milestone/models/project_milestone.py
  project_milestone/models/project_task.py
  project_milestone/readme/CONTRIBUTORS.rst
  project_milestone/readme/DESCRIPTION.rst
  project_milestone/readme/USAGE.rst
  project_milestone/security/ir.model.access.csv
  project_milestone/static/description/icon.png
  project_milestone/static/description/index.html
  project_milestone/tests/__init__.py
  project_milestone/tests/test_project_milestone.py
  project_milestone/views/project.xml
  project_milestone/views/project_milestone.xml
  project_milestone/views/project_task.xml
  setup/project_milestone/odoo/addons/project_milestone
  setup/project_milestone/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#797 [11.0][MIG] backport project_template from 12.0 to 11.0
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/es.po
  project_template/i18n/fr.po
  project_template/i18n/it.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/sl.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
Labels: approved, bot is merging ⏳

#806 [11.0][FIX] project_risk: fix response o2m relation in project risk
  project_risk/models/project_risk_response.py
Labels: approved, merged 🎉

#805 [12.0][FIX] project_risk: fix response o2m relation in project risk
  project_risk/models/project_risk_response.py
Labels: approved, bot is merging ⏳

#803 [13.0][MIG] project_risk: Migration to 13.0
  project_risk/README.rst
  project_risk/__init__.py
  project_risk/__manifest__.py
  project_risk/data/project_risk_category_data.xml
  project_risk/data/project_risk_response_category_data.xml
  project_risk/i18n/es.po
  project_risk/i18n/it.po
  project_risk/i18n/project_risk.pot
  project_risk/i18n/sl.po
  project_risk/models/__init__.py
  project_risk/models/project_project.py
  project_risk/models/project_risk.py
  project_risk/models/project_risk_category.py
  project_risk/models/project_risk_response.py
  project_risk/models/project_risk_response_category.py
  project_risk/readme/CONFIGURE.rst
  project_risk/readme/CONTRIBUTORS.rst
  project_risk/readme/DESCRIPTION.rst
  project_risk/readme/ROADMAP.rst
  project_risk/readme/USAGE.rst
  project_risk/security/ir_model_access.xml
  project_risk/static/description/icon.png
  project_risk/static/description/index.html
  project_risk/static/description/matrix.png
  project_risk/tests/__init__.py
  project_risk/tests/test_project_risk.py
  project_risk/views/menuitems.xml
  project_risk/views/project_project_view.xml
  project_risk/views/project_risk_category_view.xml
  project_risk/views/project_risk_response_category_view.xml
  project_risk/views/project_risk_view.xml
  setup/project_risk/odoo/addons/project_risk
  setup/project_risk/setup.py
Labels: approved, bot is merging ⏳
