Repository OCA/project, pull requests merged in 2021-07, with the labels that each got.

#817 [14.0][MIG] project_stock_request.
  project_stock_request/README.rst
  project_stock_request/__init__.py
  project_stock_request/__manifest__.py
  project_stock_request/i18n/it.po
  project_stock_request/i18n/project_stock_request.pot
  project_stock_request/i18n/pt_BR.po
  project_stock_request/models/__init__.py
  project_stock_request/models/project.py
  project_stock_request/models/project_task.py
  project_stock_request/models/stock_request_order.py
  project_stock_request/readme/CONTRIBUTORS.rst
  project_stock_request/readme/CREDITS.rst
  project_stock_request/readme/DESCRIPTION.rst
  project_stock_request/readme/USAGE.rst
  project_stock_request/security/ir.model.access.csv
  project_stock_request/static/description/icon.png
  project_stock_request/static/description/index.html
  project_stock_request/views/project_task_views.xml
  project_stock_request/views/project_views.xml
  project_stock_request/views/stock_request_order_views.xml
  setup/project_stock_request/odoo/addons/project_stock_request
  setup/project_stock_request/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#837 [14.0][FIX] Add custom embedded tree view in project.project for project.task.type
  project_task_default_stage/views/project_view.xml
Labels: approved, bot is merging ⏳

#810 [ADD] project_duplicate_subtask
  project_duplicate_subtask/__init__.py
  project_duplicate_subtask/__manifest__.py
  project_duplicate_subtask/models/__init__.py
  project_duplicate_subtask/models/project_task.py
  project_duplicate_subtask/readme/CONTRIBUTORS.rst
  project_duplicate_subtask/readme/DESCRIPTION.rst
  project_duplicate_subtask/readme/USAGE.rst
  project_duplicate_subtask/static/description/icon.png
  project_duplicate_subtask/tests/__init__.py
  project_duplicate_subtask/tests/test_project_duplicate_subtask.py
  project_duplicate_subtask/views/project_duplicate_action.xml
  setup/project_duplicate_subtask/odoo/addons/project_duplicate_subtask
  setup/project_duplicate_subtask/setup.py
Labels: bot is merging ⏳

#750 [12.0][IMP] project_parent_task_filter: Activate subtasks on installation
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/data/res_config_data.xml
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳, ready to merge

#747 [13.0][IMP] project_parent_task_filter: Activate subtasks on installation
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/data/res_config_data.xml
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳, ready to merge

#812 [IMP] project_purchase_link: only users with access to purchase shoul…
  project_purchase_link/views/project_project_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#798 [11.0][MIG] project_milestone: backport from 12.0 to 11.0
  project_milestone/README.rst
  project_milestone/__init__.py
  project_milestone/__manifest__.py
  project_milestone/i18n/de.po
  project_milestone/i18n/es.po
  project_milestone/i18n/es_ES.po
  project_milestone/i18n/it.po
  project_milestone/i18n/project_milestone.pot
  project_milestone/i18n/sl.po
  project_milestone/models/__init__.py
  project_milestone/models/project.py
  project_milestone/models/project_milestone.py
  project_milestone/models/project_task.py
  project_milestone/readme/CONTRIBUTORS.rst
  project_milestone/readme/DESCRIPTION.rst
  project_milestone/readme/USAGE.rst
  project_milestone/security/ir.model.access.csv
  project_milestone/static/description/icon.png
  project_milestone/static/description/index.html
  project_milestone/tests/__init__.py
  project_milestone/tests/test_project_milestone.py
  project_milestone/views/project.xml
  project_milestone/views/project_milestone.xml
  project_milestone/views/project_task.xml
Labels: approved, bot is merging ⏳
