Repository OCA/project, pull requests merged in 2022-10, with the labels that each got.

#991 [FIX] project_task_code: in place argument modification
  project_task_code/models/project_task.py
Labels: approved, bot is merging ⏳

#992 [FIX] project_task_code: in place argument modification
  project_task_code/models/project_task.py
Labels: bot is merging ⏳

#994 Fix project forecast line remove setting
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/hr_leave.py
  project_forecast_line/models/res_company.py
  project_forecast_line/models/res_config_settings.py
  project_forecast_line/tests/test_forecast_line.py
  project_forecast_line/views/forecast_line_views.xml
  project_forecast_line/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#950 [15.0] [MIG] project_category->project_type
  project_type/README.rst
  project_type/__init__.py
  project_type/__manifest__.py
  project_type/i18n/ca.po
  project_type/i18n/de.po
  project_type/i18n/es.po
  project_type/i18n/es_AR.po
  project_type/i18n/fr.po
  project_type/i18n/fr_FR.po
  project_type/i18n/it.po
  project_type/i18n/project_type.pot
  project_type/models/__init__.py
  project_type/models/project_project.py
  project_type/models/project_task.py
  project_type/models/project_type.py
  project_type/readme/CONTRIBUTORS.rst
  project_type/readme/DESCRIPTION.rst
  project_type/readme/USAGE.rst
  project_type/security/ir.model.access.csv
  project_type/static/description/icon.png
  project_type/static/description/index.html
  project_type/tests/__init__.py
  project_type/tests/test_project_type.py
  project_type/views/project_project_views.xml
  project_type/views/project_task_views.xml
  project_type/views/project_type_views.xml
  setup/project_type/odoo/addons/project_type
  setup/project_type/setup.py
Labels: approved, bot is merging ⏳

#832 [13.0][FIX] project_hr: add missing technical fields to view to trigger co…
  project_hr/views/project_task_views.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#998 [16.0][MIG] project_type: migration to 16.0
  project_type/README.rst
  project_type/__init__.py
  project_type/__manifest__.py
  project_type/i18n/ca.po
  project_type/i18n/de.po
  project_type/i18n/es.po
  project_type/i18n/es_AR.po
  project_type/i18n/fr.po
  project_type/i18n/fr_FR.po
  project_type/i18n/it.po
  project_type/i18n/project_type.pot
  project_type/models/__init__.py
  project_type/models/project_project.py
  project_type/models/project_task.py
  project_type/models/project_type.py
  project_type/readme/CONTRIBUTORS.rst
  project_type/readme/DESCRIPTION.rst
  project_type/readme/USAGE.rst
  project_type/security/ir.model.access.csv
  project_type/static/description/icon.png
  project_type/static/description/index.html
  project_type/tests/__init__.py
  project_type/tests/test_project_type.py
  project_type/views/project_project_views.xml
  project_type/views/project_task_views.xml
  project_type/views/project_type_views.xml
  setup/project_type/odoo/addons/project_type
  setup/project_type/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1003 [14.0][FIX] project_timesheet_time_control: Avoid texts on buttons
  project_timesheet_time_control/views/account_analytic_line_view.xml
  project_timesheet_time_control/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1002 [16.0][MIG] project_template: Migration
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/it.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
  setup/project_template/odoo/addons/project_template
  setup/project_template/setup.py
Labels: approved, bot is merging ⏳
