Repository OCA/project, pull requests merged in 2022-07, with the labels that each got.

#884 [IMP] project_task_project_required : project field mandatory by default
  project_task_project_required/__manifest__.py
  project_task_project_required/demo/res_company.xml
  project_task_project_required/models/res_company.py
  project_task_project_required/readme/CONFIGURE.rst
Labels: approved, ready to merge, bot is merging ⏳

#889 [15.0][MIG] project_milestone
  project_milestone/README.rst
  project_milestone/__init__.py
  project_milestone/__manifest__.py
  project_milestone/migrations/15.0.1.0.0/pre-migration.py
  project_milestone/readme/CONTRIBUTORS.rst
  project_milestone/readme/DESCRIPTION.rst
  project_milestone/static/description/icon.png
  project_milestone/static/description/index.html
  setup/project_milestone/odoo/addons/project_milestone
  setup/project_milestone/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#932 [15.0] [MIG] project_department
  project_department/README.rst
  project_department/__init__.py
  project_department/__manifest__.py
  project_department/i18n/ar.po
  project_department/i18n/ca.po
  project_department/i18n/de.po
  project_department/i18n/el.po
  project_department/i18n/es.po
  project_department/i18n/es_CR.po
  project_department/i18n/es_MX.po
  project_department/i18n/es_VE.po
  project_department/i18n/fi.po
  project_department/i18n/fr.po
  project_department/i18n/gl.po
  project_department/i18n/hr.po
  project_department/i18n/hr_HR.po
  project_department/i18n/hu.po
  project_department/i18n/it.po
  project_department/i18n/ja.po
  project_department/i18n/lt.po
  project_department/i18n/lv.po
  project_department/i18n/mk.po
  project_department/i18n/mn.po
  project_department/i18n/nl.po
  project_department/i18n/nl_NL.po
  project_department/i18n/pl.po
  project_department/i18n/project_department.pot
  project_department/i18n/pt.po
  project_department/i18n/pt_BR.po
  project_department/i18n/pt_PT.po
  project_department/i18n/ro.po
  project_department/i18n/sl.po
  project_department/i18n/sv.po
  project_department/i18n/tr.po
  project_department/i18n/uk.po
  project_department/i18n/zh_CN.po
  project_department/models/__init__.py
  project_department/models/project.py
  project_department/readme/CONTRIBUTORS.rst
  project_department/readme/DESCRIPTION.rst
  project_department/static/description/icon.png
  project_department/static/description/index.html
  project_department/views/project.xml
  setup/project_department/odoo/addons/project_department
  setup/project_department/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#918 [13.0][FIX] project_stock: Change the visibility group of the configuration sections.
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#949 [15.0][MIG] project_role
  project_role/README.rst
  project_role/__init__.py
  project_role/__manifest__.py
  project_role/i18n/de.po
  project_role/i18n/es_AR.po
  project_role/i18n/es_PA.po
  project_role/i18n/fr.po
  project_role/i18n/project_role.pot
  project_role/i18n/sl.po
  project_role/models/__init__.py
  project_role/models/project_assignment.py
  project_role/models/project_project.py
  project_role/models/project_role.py
  project_role/models/res_company.py
  project_role/models/res_config_settings.py
  project_role/readme/CONFIGURE.rst
  project_role/readme/CONTRIBUTORS.rst
  project_role/readme/DESCRIPTION.rst
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/icon.png
  project_role/static/description/index.html
  project_role/tests/__init__.py
  project_role/tests/test_project_role.py
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
  setup/project_role/odoo/addons/project_role
  setup/project_role/setup.py
Labels: needs review, approved, bot is merging ⏳

#947 [14.0][UPD]project_milestone: new features added
  project_milestone/models/project.py
  project_milestone/models/project_task.py
  project_milestone/readme/CONTRIBUTORS.rst
  project_milestone/readme/HISTORY.rst
  project_milestone/readme/USAGE.rst
  project_milestone/tests/test_project_milestone.py
  project_milestone/views/project.xml
  project_milestone/views/project_task.xml
Labels: approved, bot is merging ⏳
