Repository OCA/project, pull requests merged in 2022-06, with the labels that each got.

#921 [15.0][FIX] project_list: view projects as list
  project_list/views/project_project.xml
Labels: approved, ready to merge, bot is merging ⏳

#917 14.0 mig project mail chatter
  project_mail_chatter/README.rst
  project_mail_chatter/__init__.py
  project_mail_chatter/__manifest__.py
  project_mail_chatter/i18n/project_mail_chatter.pot
  project_mail_chatter/i18n/pt_BR.po
  project_mail_chatter/models/__init__.py
  project_mail_chatter/models/project.py
  project_mail_chatter/readme/CONTRIBUTORS.rst
  project_mail_chatter/readme/CREDITS.rst
  project_mail_chatter/readme/DESCRIPTION.rst
  project_mail_chatter/static/description/icon.png
  project_mail_chatter/static/description/index.html
  project_mail_chatter/views/project_view.xml
  setup/project_mail_chatter/odoo/addons/project_mail_chatter
  setup/project_mail_chatter/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#934 [14.0][IMP] project_task_pull_request: PR URI in main task view
  project_task_pull_request/readme/CONTRIBUTORS.rst
  project_task_pull_request/readme/USAGE.rst
  project_task_pull_request/views/project_task_pull_request_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#936 [13.0][FIX+IMP] project_stock: Prevent merge moves + Show buttons when they are really needed..
  project_stock/__manifest__.py
  project_stock/migrations/13.0.2.0.0/post-migration.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#938 [13.0][OU-FIX] project_stock: Prevent unhashable type: 'dict' error.
  project_stock/migrations/13.0.2.0.0/post-migration.py
Labels: bot is merging ⏳

#888 [15.0][ADD] project_task_milestone: added module
  project_task_milestone/README.rst
  project_task_milestone/__init__.py
  project_task_milestone/__manifest__.py
  project_task_milestone/models/__init__.py
  project_task_milestone/models/project_milestone.py
  project_task_milestone/models/project_task.py
  project_task_milestone/readme/CONTRIBUTORS.rst
  project_task_milestone/readme/CREDITS.rst
  project_task_milestone/readme/DESCRIPTION.rst
  project_task_milestone/static/description/icon.png
  project_task_milestone/static/description/index.html
  project_task_milestone/tests/__init__.py
  project_task_milestone/tests/test_project_milestone.py
  project_task_milestone/views/project_task.xml
  setup/project_task_milestone/odoo/addons/project_task_milestone
  setup/project_task_milestone/setup.py
Labels: approved, ready to merge, bot is merging ⏳
