Repository OCA/project, pull requests merged in 2022-09, with the labels that each got.

#973 [FIX] project_forecast_line consolidated capacity
  project_forecast_line/models/forecast_line.py
Labels: bot is merging ⏳

#972 [IMP] project_forecast_line_bokeh_chart
  project_forecast_line_bokeh_chart/report/forecast_line_reporting.py
Labels: bot is merging ⏳

#744 [13.0][IMP] project_purchase_link: Add tests for purchase invoice buttons
  project_purchase_link/tests/test_project_purchase_link.py
Labels: bot is merging ⏳, stale

#791 [IMP] Add a filter for template projects tasks
  project_template/models/project.py
  project_template/views/project.xml
Labels: bot is merging ⏳, stale

#942 [15.0][MIG] project_timeline: Migration to 15.0
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_project_demo.xml
  project_timeline/demo/project_task_demo.xml
  project_timeline/hooks.py
  project_timeline/i18n/ar.po
  project_timeline/i18n/ca.po
  project_timeline/i18n/de.po
  project_timeline/i18n/el.po
  project_timeline/i18n/es.po
  project_timeline/i18n/es_AR.po
  project_timeline/i18n/es_CR.po
  project_timeline/i18n/es_MX.po
  project_timeline/i18n/es_VE.po
  project_timeline/i18n/fi.po
  project_timeline/i18n/fr.po
  project_timeline/i18n/fr_FR.po
  project_timeline/i18n/gl.po
  project_timeline/i18n/he.po
  project_timeline/i18n/hr.po
  project_timeline/i18n/hr_HR.po
  project_timeline/i18n/hu.po
  project_timeline/i18n/it.po
  project_timeline/i18n/ja.po
  project_timeline/i18n/lt.po
  project_timeline/i18n/lv.po
  project_timeline/i18n/mk.po
  project_timeline/i18n/mn.po
  project_timeline/i18n/nl.po
  project_timeline/i18n/nl_NL.po
  project_timeline/i18n/pl.po
  project_timeline/i18n/project_timeline.pot
  project_timeline/i18n/pt.po
  project_timeline/i18n/pt_BR.po
  project_timeline/i18n/pt_PT.po
  project_timeline/i18n/ro.po
  project_timeline/i18n/sl.po
  project_timeline/i18n/sv.po
  project_timeline/i18n/tr.po
  project_timeline/i18n/uk.po
  project_timeline/i18n/zh_CN.po
  project_timeline/models/__init__.py
  project_timeline/models/project_task.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/readme/DESCRIPTION.rst
  project_timeline/readme/USAGE.rst
  project_timeline/static/description/icon.png
  project_timeline/static/description/icon.svg
  project_timeline/static/description/index.html
  project_timeline/static/src/scss/project_timeline.scss
  project_timeline/tests/__init__.py
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_project_view.xml
  project_timeline/views/project_task_view.xml
  setup/project_timeline/odoo/addons/project_timeline
  setup/project_timeline/setup.py
Labels: bot is merging ⏳

#977 [15.0][IMP] project_forecast_line_holidays_public: Add a setting `Recompute forecast lines immediately`
  project_forecast_line_holidays_public/__manifest__.py
  project_forecast_line_holidays_public/i18n/fr.po
  project_forecast_line_holidays_public/i18n/project_forecast_line_holidays_public.pot
  project_forecast_line_holidays_public/models/__init__.py
  project_forecast_line_holidays_public/models/hr_holidays_public.py
  project_forecast_line_holidays_public/models/res_company.py
  project_forecast_line_holidays_public/models/res_config_settings.py
  project_forecast_line_holidays_public/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#978 [15.0][IMP] project_forecast_line_bokeh_chart: dev status
  project_forecast_line_bokeh_chart/__manifest__.py
Labels: bot is merging ⏳

#951 [15.0][FIX] project_milestone: fixed migration scripts.
  project_milestone/migrations/15.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#974 [15.0][FIX] project_forecast_line: add missing access rights
  project_forecast_line/__manifest__.py
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/hr_employee.py
  project_forecast_line/models/product_template.py
  project_forecast_line/models/project_task.py
  project_forecast_line/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#920 [FIX][project_sequence_task] Share project task code sequence over companies
  project_task_code/data/task_sequence.xml
Labels: bot is merging ⏳

#980 [15.0][FIX] project_timeline: missing action
  project_timeline/views/project_project_view.xml
Labels: approved, bot is merging ⏳

#982 [13.0][IMP] project_stock: Add analytic date
  project_stock/i18n/es.po
  project_stock/i18n/project_stock.pot
  project_stock/models/project_project.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#983 [14.0][IMP] project_stock: Add analytic date
  project_stock/i18n/es.po
  project_stock/i18n/project_stock.pot
  project_stock/models/project_project.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#979 [FIX] project_forecast_line: error in consolidated capacity
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/hr_leave.py
  project_forecast_line/tests/test_forecast_line.py
Labels: approved, ready to merge, bot is merging ⏳

#915 13.0 mig project budget
  oca_dependencies.txt
  project_budget/README.rst
  project_budget/__init__.py
  project_budget/__manifest__.py
  project_budget/i18n/hr.po
  project_budget/i18n/project_budget.pot
  project_budget/i18n/sl.po
  project_budget/models/__init__.py
  project_budget/models/account_budget.py
  project_budget/models/project.py
  project_budget/readme/CONTRIBUTORS.rst
  project_budget/readme/DESCRIPTION.rst
  project_budget/readme/USAGE.rst
  project_budget/security/ir.model.access.csv
  project_budget/security/project_security.xml
  project_budget/static/description/icon.png
  project_budget/static/description/index.html
  project_budget/views/account_budget.xml
  project_budget/views/project.xml
  setup/project_budget/odoo/addons/project_budget
  setup/project_budget/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#984 [IMP][14.0]project_parent_task_filter
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳
