Repository OCA/project, pull requests merged in 2022-08, with the labels that each got.

#956 [14.0][FIX] project_mail_chatter: We need to replace oe_chatter div to place it after the sheet and show as expected.
  project_mail_chatter/README.rst
  project_mail_chatter/readme/ROADMAP.rst
  project_mail_chatter/static/description/index.html
  project_mail_chatter/views/project_view.xml
Labels: approved, bot is merging ⏳

#948 [14.0][MIG] project_stock: Migration to 14.0
  project_stock/README.rst
  project_stock/__init__.py
  project_stock/__manifest__.py
  project_stock/i18n/es.po
  project_stock/i18n/project_stock.pot
  project_stock/migrations/13.0.2.0.0/post-migration.py
  project_stock/models/__init__.py
  project_stock/models/account_analytic_line.py
  project_stock/models/project_project.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/models/stock_scrap.py
  project_stock/readme/CONFIGURE.rst
  project_stock/readme/CONTRIBUTORS.rst
  project_stock/readme/DESCRIPTION.rst
  project_stock/readme/USAGE.rst
  project_stock/static/description/icon.png
  project_stock/static/description/index.html
  project_stock/tests/__init__.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_type_view.xml
  project_stock/views/project_task_view.xml
  project_stock/views/stock_move_view.xml
  setup/project_stock/odoo/addons/project_stock
  setup/project_stock/setup.py
Labels: approved, bot is merging ⏳

#952 [14.0][MIG] project_stock_product_set: Migration to 14.0
  project_stock_product_set/README.rst
  project_stock_product_set/__init__.py
  project_stock_product_set/__manifest__.py
  project_stock_product_set/i18n/es.po
  project_stock_product_set/i18n/project_stock_product_set.pot
  project_stock_product_set/models/__init__.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/readme/CONFIGURE.rst
  project_stock_product_set/readme/CONTRIBUTORS.rst
  project_stock_product_set/readme/DESCRIPTION.rst
  project_stock_product_set/readme/USAGE.rst
  project_stock_product_set/security/ir.model.access.csv
  project_stock_product_set/static/description/icon.png
  project_stock_product_set/static/description/index.html
  project_stock_product_set/tests/__init__.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/views/project_task_view.xml
  project_stock_product_set/wizard/__init__.py
  project_stock_product_set/wizard/product_set_add.py
  project_stock_product_set/wizard/product_set_add.xml
  setup/project_stock_product_set/odoo/addons/project_stock_product_set
  setup/project_stock_product_set/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#960 [12.0][IMP] project_task_dependency: added button to open dep. task.
  project_task_dependency/models/project_task.py
  project_task_dependency/tests/test_project_task_dependency.py
  project_task_dependency/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#957 [15.0][ADD] `project_forecast_line`
  project_forecast_line/README.rst
  project_forecast_line/__init__.py
  project_forecast_line/__manifest__.py
  project_forecast_line/data/ir_cron.xml
  project_forecast_line/data/project_data.xml
  project_forecast_line/i18n/fr.po
  project_forecast_line/i18n/project_forecast_line.pot
  project_forecast_line/models/__init__.py
  project_forecast_line/models/account_analytic_line.py
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/forecast_role.py
  project_forecast_line/models/hr_employee.py
  project_forecast_line/models/hr_leave.py
  project_forecast_line/models/product_template.py
  project_forecast_line/models/project_project.py
  project_forecast_line/models/project_project_stage.py
  project_forecast_line/models/project_task.py
  project_forecast_line/models/res_company.py
  project_forecast_line/models/res_config_settings.py
  project_forecast_line/models/resource_calendar_leaves.py
  project_forecast_line/models/sale_order.py
  project_forecast_line/models/sale_order_line.py
  project_forecast_line/readme/CONTRIBUTORS.rst
  project_forecast_line/readme/DESCRIPTION.rst
  project_forecast_line/security/forecast_line_security.xml
  project_forecast_line/security/ir.model.access.csv
  project_forecast_line/static/description/icon.png
  project_forecast_line/static/description/index.html
  project_forecast_line/tests/__init__.py
  project_forecast_line/tests/test_forecast_line.py
  project_forecast_line/views/forecast_line_views.xml
  project_forecast_line/views/forecast_role_views.xml
  project_forecast_line/views/hr_employee_views.xml
  project_forecast_line/views/product_views.xml
  project_forecast_line/views/project_project_stage_views.xml
  project_forecast_line/views/project_task_views.xml
  project_forecast_line/views/res_config_settings_views.xml
  project_forecast_line/views/sale_order_views.xml
  setup/project_forecast_line/odoo/addons/project_forecast_line
  setup/project_forecast_line/setup.py
Labels: approved, bot is merging ⏳

#940 [13.0] Add project_sale_link
  project_sale_link/README.rst
  project_sale_link/__init__.py
  project_sale_link/__manifest__.py
  project_sale_link/models/__init__.py
  project_sale_link/models/project_project.py
  project_sale_link/readme/CONTRIBUTORS.rst
  project_sale_link/readme/DESCRIPTION.rst
  project_sale_link/readme/USAGE.rst
  project_sale_link/static/description/icon.png
  project_sale_link/static/description/index.html
  project_sale_link/tests/__init__.py
  project_sale_link/tests/test_project_sale_link.py
  project_sale_link/views/project_project.xml
  setup/project_sale_link/odoo/addons/project_sale_link
  setup/project_sale_link/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#958 [15.0][ADD] project_forecast_line_holidays_public
  oca_dependencies.txt
  project_forecast_line_holidays_public/README.rst
  project_forecast_line_holidays_public/__init__.py
  project_forecast_line_holidays_public/__manifest__.py
  project_forecast_line_holidays_public/i18n/fr.po
  project_forecast_line_holidays_public/i18n/project_forecast_line_holidays_public.pot
  project_forecast_line_holidays_public/models/__init__.py
  project_forecast_line_holidays_public/models/forecast_line.py
  project_forecast_line_holidays_public/models/hr_holidays_public.py
  project_forecast_line_holidays_public/readme/CONTRIBUTORS.rst
  project_forecast_line_holidays_public/readme/DESCRIPTION.rst
  project_forecast_line_holidays_public/static/description/icon.png
  project_forecast_line_holidays_public/static/description/index.html
  project_forecast_line_holidays_public/tests/__init__.py
  project_forecast_line_holidays_public/tests/test_forecast_line.py
  setup/project_forecast_line_holidays_public/odoo/addons/project_forecast_line_holidays_public
  setup/project_forecast_line_holidays_public/setup.py
Labels: approved, bot is merging ⏳

#959 [15.0][ADD] `project_forecast_line_bokeh_chart`
  oca_dependencies.txt
  project_forecast_line_bokeh_chart/README.rst
  project_forecast_line_bokeh_chart/__init__.py
  project_forecast_line_bokeh_chart/__manifest__.py
  project_forecast_line_bokeh_chart/i18n/fr.po
  project_forecast_line_bokeh_chart/i18n/project_forecast_line_bokeh_chart.pot
  project_forecast_line_bokeh_chart/readme/CONTRIBUTORS.rst
  project_forecast_line_bokeh_chart/readme/DESCRIPTION.rst
  project_forecast_line_bokeh_chart/report/__init__.py
  project_forecast_line_bokeh_chart/report/forecast_line_reporting.py
  project_forecast_line_bokeh_chart/report/forecast_line_reporting_views.xml
  project_forecast_line_bokeh_chart/security/ir.model.access.csv
  project_forecast_line_bokeh_chart/static/description/icon.png
  project_forecast_line_bokeh_chart/static/description/index.html
  setup/project_forecast_line_bokeh_chart/odoo/addons/project_forecast_line_bokeh_chart
  setup/project_forecast_line_bokeh_chart/setup.py
Labels: approved, bot is merging ⏳

#919 [15.0][ADD] project_purchase_analytic_global
  oca_dependencies.txt
  project_purchase_analytic_global/README.rst
  project_purchase_analytic_global/__init__.py
  project_purchase_analytic_global/__manifest__.py
  project_purchase_analytic_global/models/__init__.py
  project_purchase_analytic_global/models/project.py
  project_purchase_analytic_global/readme/CONTRIBUTORS.rst
  project_purchase_analytic_global/readme/DESCRIPTION.rst
  project_purchase_analytic_global/static/description/icon.png
  project_purchase_analytic_global/static/description/index.html
  setup/project_purchase_analytic_global/odoo/addons/project_purchase_analytic_global
  setup/project_purchase_analytic_global/setup.py
Labels: approved, bot is merging ⏳

#964 [IMP][12.0] project_task_material_stock: improve code for multi compa…
  project_task_material_stock/i18n/es.po
  project_task_material_stock/i18n/project_task_material_stock.pot
  project_task_material_stock/models/project_task.py
  project_task_material_stock/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#965 [12.0][IMP] project_task_material_stock: add domain to picking type
  project_task_material_stock/models/project_task.py
  project_task_material_stock/views/project_task_view.xml
Labels: bot is merging ⏳

#961 [14.0][IMP] project_task_dependency: add open dep. task button
  project_task_dependency/models/project_task.py
  project_task_dependency/tests/test_project_task_dependency.py
  project_task_dependency/views/project_task_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#967 [14.0] [IMP] add function to generate unique project key automatically.
  project_key/models/project_project.py
  project_key/tests/test_project.py
Labels: approved, bot is merging ⏳

#968 [13.0][FIX] project_stock: Avoid task deletion error.
  project_stock/models/project_task.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳

#969 [14.0][FIX] project_stock: Avoid task deletion error.
  project_stock/models/project_task.py
  project_stock/tests/test_project_stock.py
Labels: bot is merging ⏳

#970 [14.0][DCK] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  project_timesheet_time_control/__manifest__.py
Labels: bot is merging ⏳

#962 project_forecast_line: improve documentation
  project_forecast_line/README.rst
  project_forecast_line/readme/CONFIGURATION.rst
  project_forecast_line/readme/DESCRIPTION.rst
  project_forecast_line/readme/USAGE.rst
  project_forecast_line/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳
