Repository OCA/project, pull requests merged in 2022-02, with the labels that each got.

#868 [15.0][MIG] project_parent_task_filter
  project_parent_task_filter/README.rst
  project_parent_task_filter/__init__.py
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/data/res_config_data.xml
  project_parent_task_filter/i18n/ca.po
  project_parent_task_filter/i18n/de.po
  project_parent_task_filter/i18n/es.po
  project_parent_task_filter/i18n/es_AR.po
  project_parent_task_filter/i18n/es_ES.po
  project_parent_task_filter/i18n/fr.po
  project_parent_task_filter/i18n/fr_FR.po
  project_parent_task_filter/i18n/nl_NL.po
  project_parent_task_filter/i18n/project_parent_task_filter.pot
  project_parent_task_filter/models/__init__.py
  project_parent_task_filter/models/project_task.py
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
  project_parent_task_filter/readme/USAGE.rst
  project_parent_task_filter/static/description/icon.png
  project_parent_task_filter/static/description/index.html
  project_parent_task_filter/views/project_task.xml
  setup/project_parent_task_filter/odoo/addons/project_parent_task_filter
  setup/project_parent_task_filter/setup.py
Labels: approved, bot is merging ⏳

#873 [15.0][MIG] project_task_default_stage
  project_task_default_stage/README.rst
  project_task_default_stage/__init__.py
  project_task_default_stage/__manifest__.py
  project_task_default_stage/data/project_data.xml
  project_task_default_stage/i18n/bg.po
  project_task_default_stage/i18n/ca.po
  project_task_default_stage/i18n/cs_CZ.po
  project_task_default_stage/i18n/de.po
  project_task_default_stage/i18n/el_GR.po
  project_task_default_stage/i18n/en.po
  project_task_default_stage/i18n/es.po
  project_task_default_stage/i18n/es_AR.po
  project_task_default_stage/i18n/es_CO.po
  project_task_default_stage/i18n/es_MX.po
  project_task_default_stage/i18n/fi.po
  project_task_default_stage/i18n/fr.po
  project_task_default_stage/i18n/fr_FR.po
  project_task_default_stage/i18n/gl.po
  project_task_default_stage/i18n/hr.po
  project_task_default_stage/i18n/hu.po
  project_task_default_stage/i18n/it.po
  project_task_default_stage/i18n/nb.po
  project_task_default_stage/i18n/nb_NO.po
  project_task_default_stage/i18n/nl.po
  project_task_default_stage/i18n/nl_NL.po
  project_task_default_stage/i18n/pl.po
  project_task_default_stage/i18n/project_task_default_stage.pot
  project_task_default_stage/i18n/pt.po
  project_task_default_stage/i18n/pt_BR.po
  project_task_default_stage/i18n/pt_PT.po
  project_task_default_stage/i18n/ru.po
  project_task_default_stage/i18n/sk.po
  project_task_default_stage/i18n/sl.po
  project_task_default_stage/i18n/tr.po
  project_task_default_stage/i18n/zh_CN.po
  project_task_default_stage/models/__init__.py
  project_task_default_stage/models/project.py
  project_task_default_stage/models/project_task_type.py
  project_task_default_stage/readme/CONFIGURE.rst
  project_task_default_stage/readme/CONTRIBUTORS.rst
  project_task_default_stage/readme/DESCRIPTION.rst
  project_task_default_stage/static/description/icon.png
  project_task_default_stage/static/description/index.html
  project_task_default_stage/tests/__init__.py
  project_task_default_stage/tests/test_project_task_default_stage.py
  project_task_default_stage/views/project_view.xml
  setup/project_task_default_stage/odoo/addons/project_task_default_stage
  setup/project_task_default_stage/setup.py
Labels: approved, bot is merging ⏳

#874 [15.0][MIG] project_task_add_very_high
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/hooks.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_AR.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/fr_FR.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/readme/CONTRIBUTORS.rst
  project_task_add_very_high/readme/DESCRIPTION.rst
  project_task_add_very_high/readme/USAGE.rst
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/views/project_task_view.xml
  setup/project_task_add_very_high/odoo/addons/project_task_add_very_high
  setup/project_task_add_very_high/setup.py
Labels: approved, bot is merging ⏳

#875 [15.0][MIG] project_list
  project_list/README.rst
  project_list/__init__.py
  project_list/__manifest__.py
  project_list/i18n/de.po
  project_list/i18n/es_AR.po
  project_list/i18n/project_list.pot
  project_list/readme/CONTRIBUTORS.rst
  project_list/readme/DESCRIPTION.rst
  project_list/static/description/icon.png
  project_list/static/description/index.html
  project_list/views/project_project.xml
  setup/project_list/odoo/addons/project_list
  setup/project_list/setup.py
Labels: approved, bot is merging ⏳

#901 [ADD] Auto fold task on Personal Stage when is closed
  project_task_personal_stage_auto_fold/README.rst
  project_task_personal_stage_auto_fold/__init__.py
  project_task_personal_stage_auto_fold/__manifest__.py
  project_task_personal_stage_auto_fold/models/__init__.py
  project_task_personal_stage_auto_fold/models/project_task.py
  project_task_personal_stage_auto_fold/readme/CONTRIBUTORS.rst
  project_task_personal_stage_auto_fold/readme/DESCRIPTION.rst
  project_task_personal_stage_auto_fold/static/description/icon.png
  project_task_personal_stage_auto_fold/static/description/index.html
  setup/project_task_personal_stage_auto_fold/odoo/addons/project_task_personal_stage_auto_fold
  setup/project_task_personal_stage_auto_fold/setup.py
Labels: needs review, approved, bot is merging ⏳

#903 [IMP] Add tests on project_task_personal_stage_auto_fold
  project_task_personal_stage_auto_fold/tests/__init__.py
  project_task_personal_stage_auto_fold/tests/test_personal_stages.py
Labels: needs review, approved
