Repository OCA/project, pull requests merged in 2022-11, with the labels that each got.

#985 [13.0][FIX] project_stock: Change cancel process (set as quantity_done = 0)
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳

#1018 [FIX] pre-commit py-lint error
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  project_task_personal_stage_auto_fold/tests/test_personal_stages.py
Labels: approved, bot is merging ⏳

#1017 [14.0][FIX] project_stock: Change cancel process (set as quantity_done = 0)
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: bot is merging ⏳

#1021 [15.0][FIX] project_role + project_type: Add recursive=True parameter to complete_name field to prevent error.
  project_role/models/project_role.py
  project_type/models/project_type.py
Labels: bot is merging ⏳

#1000 [14.0][ADD] project_stage_mgmt
  project_stage_mgmt/README.rst
  project_stage_mgmt/__init__.py
  project_stage_mgmt/__manifest__.py
  project_stage_mgmt/readme/CONTRIBUTORS.rst
  project_stage_mgmt/readme/DESCRIPTION.rst
  project_stage_mgmt/views/project.xml
  setup/project_stage_mgmt/odoo/addons/project_stage_mgmt
  setup/project_stage_mgmt/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1007 16.0 mig project department
  project_department/README.rst
  project_department/__init__.py
  project_department/__manifest__.py
  project_department/i18n/ar.po
  project_department/i18n/ca.po
  project_department/i18n/de.po
  project_department/i18n/el.po
  project_department/i18n/es.po
  project_department/i18n/es_CR.po
  project_department/i18n/es_MX.po
  project_department/i18n/es_VE.po
  project_department/i18n/fi.po
  project_department/i18n/fr.po
  project_department/i18n/gl.po
  project_department/i18n/hr.po
  project_department/i18n/hr_HR.po
  project_department/i18n/hu.po
  project_department/i18n/it.po
  project_department/i18n/ja.po
  project_department/i18n/lt.po
  project_department/i18n/lv.po
  project_department/i18n/mk.po
  project_department/i18n/mn.po
  project_department/i18n/nl.po
  project_department/i18n/nl_NL.po
  project_department/i18n/pl.po
  project_department/i18n/project_department.pot
  project_department/i18n/pt.po
  project_department/i18n/pt_BR.po
  project_department/i18n/pt_PT.po
  project_department/i18n/ro.po
  project_department/i18n/sl.po
  project_department/i18n/sv.po
  project_department/i18n/tr.po
  project_department/i18n/uk.po
  project_department/i18n/zh_CN.po
  project_department/models/__init__.py
  project_department/models/project.py
  project_department/readme/CONTRIBUTORS.rst
  project_department/readme/DESCRIPTION.rst
  project_department/static/description/icon.png
  project_department/static/description/index.html
  project_department/views/project.xml
  setup/project_department/odoo/addons/project_department
  setup/project_department/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1004 [16.0][MIG] project_list: Migration to 16.0
  project_list/README.rst
  project_list/__init__.py
  project_list/__manifest__.py
  project_list/i18n/de.po
  project_list/i18n/es_AR.po
  project_list/i18n/project_list.pot
  project_list/readme/CONTRIBUTORS.rst
  project_list/readme/DESCRIPTION.rst
  project_list/static/description/icon.png
  project_list/static/description/index.html
  project_list/views/project_project.xml
  setup/project_list/odoo/addons/project_list
  setup/project_list/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1020 [15.0][MIG] project_stock: Migration to 15.0
  project_stock/README.rst
  project_stock/__init__.py
  project_stock/__manifest__.py
  project_stock/demo/project_data.xml
  project_stock/demo/stock_picking_type_data.xml
  project_stock/i18n/es.po
  project_stock/i18n/hr.po
  project_stock/i18n/it.po
  project_stock/i18n/project_stock.pot
  project_stock/migrations/15.0.1.0.0/pre-migration.py
  project_stock/models/__init__.py
  project_stock/models/account_analytic_line.py
  project_stock/models/project_project.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/models/stock_scrap.py
  project_stock/readme/CONFIGURE.rst
  project_stock/readme/CONTRIBUTORS.rst
  project_stock/readme/DESCRIPTION.rst
  project_stock/readme/USAGE.rst
  project_stock/static/description/icon.png
  project_stock/static/description/index.html
  project_stock/tests/__init__.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_type_view.xml
  project_stock/views/project_task_view.xml
  project_stock/views/stock_move_view.xml
  setup/project_stock/odoo/addons/project_stock
  setup/project_stock/setup.py
Labels: approved, bot is merging ⏳

#1023 [15.0][MIG] project_stock_product_set: Migration to 15.0
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock_product_set/README.rst
  project_stock_product_set/__init__.py
  project_stock_product_set/__manifest__.py
  project_stock_product_set/i18n/es.po
  project_stock_product_set/i18n/it.po
  project_stock_product_set/i18n/project_stock_product_set.pot
  project_stock_product_set/models/__init__.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/readme/CONFIGURE.rst
  project_stock_product_set/readme/CONTRIBUTORS.rst
  project_stock_product_set/readme/DESCRIPTION.rst
  project_stock_product_set/readme/USAGE.rst
  project_stock_product_set/security/ir.model.access.csv
  project_stock_product_set/static/description/icon.png
  project_stock_product_set/static/description/index.html
  project_stock_product_set/tests/__init__.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/views/project_task_view.xml
  project_stock_product_set/wizard/__init__.py
  project_stock_product_set/wizard/product_set_add.py
  project_stock_product_set/wizard/product_set_add.xml
  setup/project_stock_product_set/odoo/addons/project_stock_product_set
  setup/project_stock_product_set/setup.py
Labels: approved, bot is merging ⏳

#1015 [16.0] [MIG] project_task_add_very_high: Migration to 16.0
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/hooks.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_AR.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/fr_FR.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/readme/CONTRIBUTORS.rst
  project_task_add_very_high/readme/DESCRIPTION.rst
  project_task_add_very_high/readme/USAGE.rst
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/views/project_task_view.xml
  setup/project_task_add_very_high/odoo/addons/project_task_add_very_high
  setup/project_task_add_very_high/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#999 [15.0][IMP] project_forecast_line: Some improvements
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/project_project.py
  project_forecast_line/models/project_task.py
  project_forecast_line/models/sale_order_line.py
  project_forecast_line/utils.py
  project_forecast_line/views/forecast_line_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1014 16.0 mig project task default stage
  project_task_default_stage/README.rst
  project_task_default_stage/__init__.py
  project_task_default_stage/__manifest__.py
  project_task_default_stage/data/project_data.xml
  project_task_default_stage/i18n/bg.po
  project_task_default_stage/i18n/ca.po
  project_task_default_stage/i18n/cs_CZ.po
  project_task_default_stage/i18n/de.po
  project_task_default_stage/i18n/el_GR.po
  project_task_default_stage/i18n/en.po
  project_task_default_stage/i18n/es.po
  project_task_default_stage/i18n/es_AR.po
  project_task_default_stage/i18n/es_CO.po
  project_task_default_stage/i18n/es_MX.po
  project_task_default_stage/i18n/fi.po
  project_task_default_stage/i18n/fr.po
  project_task_default_stage/i18n/fr_FR.po
  project_task_default_stage/i18n/gl.po
  project_task_default_stage/i18n/hr.po
  project_task_default_stage/i18n/hu.po
  project_task_default_stage/i18n/it.po
  project_task_default_stage/i18n/nb.po
  project_task_default_stage/i18n/nb_NO.po
  project_task_default_stage/i18n/nl.po
  project_task_default_stage/i18n/nl_NL.po
  project_task_default_stage/i18n/pl.po
  project_task_default_stage/i18n/project_task_default_stage.pot
  project_task_default_stage/i18n/pt.po
  project_task_default_stage/i18n/pt_BR.po
  project_task_default_stage/i18n/pt_PT.po
  project_task_default_stage/i18n/ru.po
  project_task_default_stage/i18n/sk.po
  project_task_default_stage/i18n/sl.po
  project_task_default_stage/i18n/tr.po
  project_task_default_stage/i18n/zh_CN.po
  project_task_default_stage/models/__init__.py
  project_task_default_stage/models/project.py
  project_task_default_stage/models/project_task_type.py
  project_task_default_stage/readme/CONFIGURE.rst
  project_task_default_stage/readme/CONTRIBUTORS.rst
  project_task_default_stage/readme/DESCRIPTION.rst
  project_task_default_stage/static/description/icon.png
  project_task_default_stage/static/description/index.html
  project_task_default_stage/tests/__init__.py
  project_task_default_stage/tests/test_project_task_default_stage.py
  project_task_default_stage/views/project_view.xml
  setup/project_task_default_stage/odoo/addons/project_task_default_stage
  setup/project_task_default_stage/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#802 [13.0] [MIG] project_task_digitized_signature
  project_task_digitized_signature/README.rst
  project_task_digitized_signature/__init__.py
  project_task_digitized_signature/__manifest__.py
  project_task_digitized_signature/i18n/ar.po
  project_task_digitized_signature/i18n/ca.po
  project_task_digitized_signature/i18n/de.po
  project_task_digitized_signature/i18n/el.po
  project_task_digitized_signature/i18n/es.po
  project_task_digitized_signature/i18n/es_CR.po
  project_task_digitized_signature/i18n/es_MX.po
  project_task_digitized_signature/i18n/es_VE.po
  project_task_digitized_signature/i18n/fi.po
  project_task_digitized_signature/i18n/fr.po
  project_task_digitized_signature/i18n/gl.po
  project_task_digitized_signature/i18n/hr.po
  project_task_digitized_signature/i18n/hr_HR.po
  project_task_digitized_signature/i18n/hu.po
  project_task_digitized_signature/i18n/it.po
  project_task_digitized_signature/i18n/ja.po
  project_task_digitized_signature/i18n/lt.po
  project_task_digitized_signature/i18n/lv.po
  project_task_digitized_signature/i18n/mk.po
  project_task_digitized_signature/i18n/mn.po
  project_task_digitized_signature/i18n/nl.po
  project_task_digitized_signature/i18n/pl.po
  project_task_digitized_signature/i18n/project_task_digitized_signature.pot
  project_task_digitized_signature/i18n/pt.po
  project_task_digitized_signature/i18n/pt_BR.po
  project_task_digitized_signature/i18n/pt_PT.po
  project_task_digitized_signature/i18n/ro.po
  project_task_digitized_signature/i18n/sl.po
  project_task_digitized_signature/i18n/sv.po
  project_task_digitized_signature/i18n/tr.po
  project_task_digitized_signature/i18n/uk.po
  project_task_digitized_signature/i18n/zh_CN.po
  project_task_digitized_signature/models/__init__.py
  project_task_digitized_signature/models/project.py
  project_task_digitized_signature/readme/CONTRIBUTORS.rst
  project_task_digitized_signature/readme/DESCRIPTION.rst
  project_task_digitized_signature/readme/INSTALL.rst
  project_task_digitized_signature/readme/ROADMAP.rst
  project_task_digitized_signature/readme/USAGE.rst
  project_task_digitized_signature/report/project_task_report.xml
  project_task_digitized_signature/static/description/icon.png
  project_task_digitized_signature/static/description/index.html
  project_task_digitized_signature/tests/__init__.py
  project_task_digitized_signature/tests/test_project_task_digitized_signature.py
  project_task_digitized_signature/views/project_task_views.xml
  setup/project_task_digitized_signature/odoo/addons/project_task_digitized_signature
  setup/project_task_digitized_signature/setup.py
Labels: bot is merging ⏳, stale

#1025 [FIX] project_task_personal_stage_auto_fold: improve readme
  project_task_personal_stage_auto_fold/README.rst
  project_task_personal_stage_auto_fold/readme/CONFIGURE.rst
  project_task_personal_stage_auto_fold/readme/DESCRIPTION.rst
  project_task_personal_stage_auto_fold/readme/USAGE.rst
  project_task_personal_stage_auto_fold/static/description/index.html
Labels: needs review, approved, bot is merging ⏳

#908 [13.0][PORT][WIP] 829 from 12.0 ADD project_timesheet_time_control_sale
  project_timesheet_time_control_sale/README.rst
  project_timesheet_time_control_sale/__init__.py
  project_timesheet_time_control_sale/__manifest__.py
  project_timesheet_time_control_sale/models/__init__.py
  project_timesheet_time_control_sale/models/account_move_line.py
  project_timesheet_time_control_sale/readme/CONTRIBUTORS.rst
  project_timesheet_time_control_sale/readme/DESCRIPTION.rst
  project_timesheet_time_control_sale/static/description/icon.png
  project_timesheet_time_control_sale/static/description/icon.svg
  project_timesheet_time_control_sale/static/description/index.html
  setup/project_timesheet_time_control_sale/.eggs/README.txt
  setup/project_timesheet_time_control_sale/odoo/addons/project_timesheet_time_control_sale
  setup/project_timesheet_time_control_sale/setup.py
Labels: needs review, approved, bot is merging ⏳

#1024 [14.0][IMP] project_tag: added 'Tags Required' field
  project_tag/__manifest__.py
  project_tag/models/__init__.py
  project_tag/models/project.py
  project_tag/models/project_task.py
  project_tag/readme/CONTRIBUTORS.rst
  project_tag/readme/USAGE.rst
  project_tag/views/project.xml
  project_tag/views/project_task.xml
Labels: approved, bot is merging ⏳

#911 [14.0][PORT] 908 from 13.0 project_timesheet_control_sale
  project_timesheet_time_control_sale/README.rst
  project_timesheet_time_control_sale/__init__.py
  project_timesheet_time_control_sale/__manifest__.py
  project_timesheet_time_control_sale/models/__init__.py
  project_timesheet_time_control_sale/models/account_analytic_line.py
  project_timesheet_time_control_sale/models/account_move_line.py
  project_timesheet_time_control_sale/readme/CONTRIBUTORS.rst
  project_timesheet_time_control_sale/readme/DESCRIPTION.rst
  project_timesheet_time_control_sale/static/description/icon.png
  project_timesheet_time_control_sale/static/description/icon.svg
  project_timesheet_time_control_sale/static/description/index.html
  project_timesheet_time_control_sale/wizards/__init__.py
  project_timesheet_time_control_sale/wizards/hr_timesheet_switch.py
  setup/project_timesheet_time_control_sale/.eggs/README.txt
  setup/project_timesheet_time_control_sale/odoo/addons/project_timesheet_time_control_sale
  setup/project_timesheet_time_control_sale/setup.py
Labels: approved, bot is merging ⏳
