Repository OCA/project, pull requests merged in 2022-01, with the labels that each got.

#869 [14.0][FIX] Added timeline view type on project.task actions
  project_timeline/views/project_task_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#854 [14.0] Migration of project_timeline_hr_timesheet
  project_timeline_hr_timesheet/README.rst
  project_timeline_hr_timesheet/__init__.py
  project_timeline_hr_timesheet/__manifest__.py
  project_timeline_hr_timesheet/i18n/de.po
  project_timeline_hr_timesheet/i18n/es.po
  project_timeline_hr_timesheet/i18n/he.po
  project_timeline_hr_timesheet/i18n/project_timeline_hr_timesheet.pot
  project_timeline_hr_timesheet/readme/CONTRIBUTORS.rst
  project_timeline_hr_timesheet/readme/DESCRIPTION.rst
  project_timeline_hr_timesheet/static/description/icon.png
  project_timeline_hr_timesheet/static/description/index.html
  project_timeline_hr_timesheet/static/src/scss/project_timeline_hr_timesheet.scss
  project_timeline_hr_timesheet/templates/assets.xml
  project_timeline_hr_timesheet/views/project_task_view.xml
  setup/project_timeline_hr_timesheet/odoo/addons/project_timeline_hr_timesheet
  setup/project_timeline_hr_timesheet/setup.py
Labels: approved, bot is merging ⏳

#882 [IMP] [12.0] project_timeline : change task display in timeline view.
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#883 [IMP] [14.0] project_timeline : change task display in timeline view
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#885 [FIX] project_timeline remove task view mode
  project_timeline/views/project_task_view.xml
Labels: bot is merging ⏳
