Repository OCA/project, pull requests merged in 2022-04, with the labels that each got.

#894 [IMP][15.0] project_parent_task_filter
  project_parent_task_filter/models/project_task.py
Labels: approved, bot is merging ⏳

#900 [MIG][15.0]project_task_pull_request: Migration v15
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_AR.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/readme/CONTRIBUTORS.rst
  project_task_pull_request/readme/DESCRIPTION.rst
  project_task_pull_request/readme/USAGE.rst
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
  setup/project_task_pull_request/odoo/addons/project_task_pull_request
  setup/project_task_pull_request/setup.py
Labels: needs review, approved, bot is merging ⏳

#905 [13.0][ADD] project_stock: New addon
  project_stock/README.rst
  project_stock/__init__.py
  project_stock/__manifest__.py
  project_stock/i18n/es.po
  project_stock/i18n/project_stock.pot
  project_stock/models/__init__.py
  project_stock/models/account_analytic_line.py
  project_stock/models/project_project.py
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/models/stock_scrap.py
  project_stock/readme/CONFIGURE.rst
  project_stock/readme/CONTRIBUTORS.rst
  project_stock/readme/DESCRIPTION.rst
  project_stock/readme/USAGE.rst
  project_stock/static/description/icon.png
  project_stock/static/description/index.html
  project_stock/tests/__init__.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_project_view.xml
  project_stock/views/project_task_type_view.xml
  project_stock/views/project_task_view.xml
  project_stock/views/stock_move_view.xml
  setup/project_stock/odoo/addons/project_stock
  setup/project_stock/setup.py
Labels: bot is merging ⏳

#912 [13.0][FIX] project_stock: Avoid permissions error if the user does not have access to stock.
  project_stock/models/project_task.py
Labels: bot is merging ⏳

#887 [15.0][MIG] project_template: migration to `15.0`
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/it.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/readme/CONTRIBUTORS.rst
  project_template/readme/DESCRIPTION.rst
  project_template/readme/USAGE.rst
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
  setup/project_template/odoo/addons/project_template
  setup/project_template/setup.py
Labels: approved, bot is merging ⏳

#914 [13.0][IMP] project_stock: Confirm the new stock movements in the "Check availability materials" button
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳
