Repository OCA/project, pull requests merged in 2022-12, with the labels that each got.

#1032 [15.0][FIX] project_task_code: Fix null value in column code, that violates not-null constraint
  project_task_code/models/project_task.py
Labels: approved, bot is merging ⏳

#986 [IMP] project_milestone: task search and tree
  project_milestone/__manifest__.py
  project_milestone/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#1029 [15.0][UPD] project_forecast_line: update forecast lines even if employee is not active
  project_forecast_line/models/project_task.py
Labels: approved, bot is merging ⏳

#995 project_forecast_line: add demo data
  project_forecast_line/__manifest__.py
  project_forecast_line/demo/forecast_role.xml
  project_forecast_line/demo/hr_employee.xml
  project_forecast_line/demo/hr_job.xml
  project_forecast_line/demo/product.xml
  project_forecast_line/demo/project.xml
  project_forecast_line/demo/res_users.xml
  project_forecast_line/demo/sale.xml
  project_forecast_line/models/hr_employee.py
Labels: approved, ready to merge, bot is merging ⏳

#1046 [15.0][FIX] project_stock: Set the warehouse_id field correctly.
  project_stock/models/project_task.py
Labels: approved, bot is merging ⏳

#1047 [14.0][IMP] project_stock: Avoid defining the project in the analytic items to avoid incoherence.
  project_stock/models/stock_move.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳

#1048 [15.0][IMP] project_stock: Avoid defining the project in the analytic items to avoid incoherence.
  project_stock/models/stock_move.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳

#1040 15.0 fix project forecast perf issues
  project_forecast_line/models/__init__.py
  project_forecast_line/models/account_analytic_line.py
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/forecast_line_mixin.py
  project_forecast_line/models/hr_employee.py
  project_forecast_line/models/hr_leave.py
  project_forecast_line/models/project_project.py
  project_forecast_line/models/project_project_stage.py
  project_forecast_line/models/project_task.py
  project_forecast_line/models/res_company.py
  project_forecast_line/models/resource_calendar_leaves.py
  project_forecast_line/models/sale_order.py
  project_forecast_line/models/sale_order_line.py
  project_forecast_line/security/ir.model.access.csv
  project_forecast_line/tests/test_forecast_line.py
  project_forecast_line/utils.py
  project_forecast_line_holidays_public/models/forecast_line.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1049 16.0 mig project_role
  project_role/README.rst
  project_role/__init__.py
  project_role/__manifest__.py
  project_role/i18n/de.po
  project_role/i18n/es_AR.po
  project_role/i18n/es_PA.po
  project_role/i18n/fr.po
  project_role/i18n/project_role.pot
  project_role/i18n/sl.po
  project_role/models/__init__.py
  project_role/models/project_assignment.py
  project_role/models/project_project.py
  project_role/models/project_role.py
  project_role/models/res_company.py
  project_role/models/res_config_settings.py
  project_role/readme/CONFIGURE.rst
  project_role/readme/CONTRIBUTORS.rst
  project_role/readme/DESCRIPTION.rst
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/icon.png
  project_role/static/description/index.html
  project_role/tests/__init__.py
  project_role/tests/test_project_role.py
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
  setup/project_role/odoo/addons/project_role
  setup/project_role/setup.py
Labels: bot is merging ⏳
