Repository OCA/project, pull requests merged in 2023-07, with the labels that each got.

#1094 [14.0][FIX] project_timesheet_time_control: compatibility with hr_timesheet_sheet
  project_timesheet_time_control/wizards/hr_timesheet_switch.py
Labels: bot is merging ⏳

#1034 [14.0][MIG] project_purchase_link
  project_purchase_link/README.rst
  project_purchase_link/__init__.py
  project_purchase_link/__manifest__.py
  project_purchase_link/i18n/es.po
  project_purchase_link/i18n/project_purchase_link.pot
  project_purchase_link/i18n/sl.po
  project_purchase_link/models/__init__.py
  project_purchase_link/models/project_project.py
  project_purchase_link/readme/CONTRIBUTORS.rst
  project_purchase_link/readme/DESCRIPTION.rst
  project_purchase_link/readme/USAGE.rst
  project_purchase_link/static/description/icon.png
  project_purchase_link/static/description/index.html
  project_purchase_link/tests/__init__.py
  project_purchase_link/tests/test_project_purchase_link.py
  project_purchase_link/views/project_project_view.xml
  setup/project_purchase_link/odoo/addons/project_purchase_link
  setup/project_purchase_link/setup.py
Labels: needs review, migration, bot is merging ⏳

#1106 [FIX] project_forecast_line issues
  project_forecast_line/models/hr_employee.py
  project_forecast_line/models/hr_leave.py
  project_forecast_line/models/project_task.py
  project_forecast_line/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1152 [14.0][FIX]project_timeline: Add timeline view to model report.project task…
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1161 [16.0][FIX]project_timeline: Add timeline view to model report.project.task
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1160 [15.0][FIX]project_timeline: Add timeline view to model report.project.task
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1155 [16.0][MIG] project_sequence: Migration to version 16.0
  project_sequence/README.rst
  project_sequence/__init__.py
  project_sequence/__manifest__.py
  project_sequence/data/ir_sequence.xml
  project_sequence/i18n/es.po
  project_sequence/i18n/it.po
  project_sequence/i18n/project_sequence.pot
  project_sequence/models/__init__.py
  project_sequence/models/project_project.py
  project_sequence/readme/CONFIGURE.rst
  project_sequence/readme/CONTRIBUTORS.rst
  project_sequence/readme/CREDITS.rst
  project_sequence/readme/DESCRIPTION.rst
  project_sequence/readme/USAGE.rst
  project_sequence/static/description/icon.png
  project_sequence/static/description/index.html
  project_sequence/tests/__init__.py
  project_sequence/tests/test_project_sequence.py
  project_sequence/views/project_project.xml
  project_sequence/wizards/__init__.py
  project_sequence/wizards/res_config_settings.py
  project_sequence/wizards/res_config_settings_view.xml
  setup/project_sequence/odoo/addons/project_sequence
  setup/project_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1163 [15.0][FIX] project_stock: Filter valid stock moves (avoiding those done and cancelled) in action_done() to avoid side effects.
  project_stock/models/project_task.py
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳

#1166 [15.0][FIX] project_sequence: Change SavepointCase to TransactionCase
  project_sequence/tests/test_project_sequence.py
Labels: bot is merging ⏳

#1165 [15.0][FIX] project_stock: Avoid creating multiple analytical items in the "Transfer Materials" process.
  project_stock/models/project_task.py
  project_stock/tests/test_project_stock.py
Labels: approved, bot is merging ⏳
