Repository OCA/project, pull requests merged in 2023-03, with the labels that each got.

#1083 [13.0][FIX] project_stock_product_set: Set group_id allways in new stock moves from wizard
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/wizard/product_set_add.py
Labels: approved, bot is merging ⏳

#1085 [14.0][FIX] project_stock_product_set: Set group_id allways in new stock moves from wizard
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/wizard/product_set_add.py
Labels: approved, bot is merging ⏳

#1086 [15.0][FIX] project_stock_product_set: Set group_id allways in new stock moves from wizard
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/wizard/product_set_add.py
Labels: approved, bot is merging ⏳

#1088 [15.0][MIG] project_timeline_hr_timesheet: Migration to 15.0
  project_timeline_hr_timesheet/README.rst
  project_timeline_hr_timesheet/__init__.py
  project_timeline_hr_timesheet/__manifest__.py
  project_timeline_hr_timesheet/i18n/de.po
  project_timeline_hr_timesheet/i18n/es.po
  project_timeline_hr_timesheet/i18n/fr.po
  project_timeline_hr_timesheet/i18n/he.po
  project_timeline_hr_timesheet/i18n/project_timeline_hr_timesheet.pot
  project_timeline_hr_timesheet/readme/CONTRIBUTORS.rst
  project_timeline_hr_timesheet/readme/DESCRIPTION.rst
  project_timeline_hr_timesheet/static/description/icon.png
  project_timeline_hr_timesheet/static/description/index.html
  project_timeline_hr_timesheet/static/src/scss/project_timeline_hr_timesheet.scss
  project_timeline_hr_timesheet/views/project_task_view.xml
  setup/project_timeline_hr_timesheet/odoo/addons/project_timeline_hr_timesheet
  setup/project_timeline_hr_timesheet/setup.py
Labels: approved, bot is merging ⏳

#1089 [MIG] project_timeline: Migration to 16.0
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_project_demo.xml
  project_timeline/demo/project_task_demo.xml
  project_timeline/hooks.py
  project_timeline/i18n/ar.po
  project_timeline/i18n/ca.po
  project_timeline/i18n/de.po
  project_timeline/i18n/el.po
  project_timeline/i18n/es.po
  project_timeline/i18n/es_AR.po
  project_timeline/i18n/es_CR.po
  project_timeline/i18n/es_MX.po
  project_timeline/i18n/es_VE.po
  project_timeline/i18n/fi.po
  project_timeline/i18n/fr.po
  project_timeline/i18n/fr_FR.po
  project_timeline/i18n/gl.po
  project_timeline/i18n/he.po
  project_timeline/i18n/hr.po
  project_timeline/i18n/hr_HR.po
  project_timeline/i18n/hu.po
  project_timeline/i18n/it.po
  project_timeline/i18n/ja.po
  project_timeline/i18n/lt.po
  project_timeline/i18n/lv.po
  project_timeline/i18n/mk.po
  project_timeline/i18n/mn.po
  project_timeline/i18n/nl.po
  project_timeline/i18n/nl_NL.po
  project_timeline/i18n/pl.po
  project_timeline/i18n/project_timeline.pot
  project_timeline/i18n/pt.po
  project_timeline/i18n/pt_BR.po
  project_timeline/i18n/pt_PT.po
  project_timeline/i18n/ro.po
  project_timeline/i18n/sl.po
  project_timeline/i18n/sv.po
  project_timeline/i18n/tr.po
  project_timeline/i18n/uk.po
  project_timeline/i18n/zh_CN.po
  project_timeline/models/__init__.py
  project_timeline/models/project_task.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/readme/DESCRIPTION.rst
  project_timeline/readme/USAGE.rst
  project_timeline/static/description/icon.png
  project_timeline/static/description/icon.svg
  project_timeline/static/description/index.html
  project_timeline/static/src/scss/project_timeline.scss
  project_timeline/tests/__init__.py
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_project_view.xml
  project_timeline/views/project_task_view.xml
  setup/project_timeline/odoo/addons/project_timeline
  setup/project_timeline/setup.py
Labels: approved, bot is merging ⏳

#1092 [15.0][FIX][project_timesheet_time_control] Error: AttributeError: type object 'expression' has no attribute AND
  project_timesheet_time_control/wizards/hr_timesheet_switch.py
Labels: bot is merging ⏳

#1098 [IMP][14.0] project_tag: Similar view as Odoo 15
  project_tag/views/project.xml
Labels: needs review, approved, bot is merging ⏳
