Repository OCA/project, pull requests merged in 2023-12, with the labels that each got.

#1200 [16.0][MIG] project_stock_product_set: Migration to 16.0
  project_stock/tests/common.py
  project_stock_product_set/README.rst
  project_stock_product_set/__init__.py
  project_stock_product_set/__manifest__.py
  project_stock_product_set/i18n/es.po
  project_stock_product_set/i18n/it.po
  project_stock_product_set/i18n/project_stock_product_set.pot
  project_stock_product_set/models/__init__.py
  project_stock_product_set/models/product_set_line.py
  project_stock_product_set/readme/CONFIGURE.rst
  project_stock_product_set/readme/CONTRIBUTORS.rst
  project_stock_product_set/readme/DESCRIPTION.rst
  project_stock_product_set/readme/USAGE.rst
  project_stock_product_set/security/ir.model.access.csv
  project_stock_product_set/static/description/icon.png
  project_stock_product_set/static/description/index.html
  project_stock_product_set/tests/__init__.py
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/views/project_task_view.xml
  project_stock_product_set/wizard/__init__.py
  project_stock_product_set/wizard/product_set_add.py
  project_stock_product_set/wizard/product_set_add.xml
  setup/project_stock_product_set/odoo/addons/project_stock_product_set
  setup/project_stock_product_set/setup.py
Labels: approved, bot is merging ⏳

#1198 [16.0][IMP] project_role: Add unaccent=False to parent_path field
  project_role/models/project_role.py
Labels: approved, ready to merge, bot is merging ⏳

#1202 [FIX] project_task_link: Fix 'xpath by class' warning
  project_task_link/views/project_project_views.xml
Labels: approved, bot is merging ⏳

#1201 [16.0][ADD] project_update_visible
  project_update_visible/README.rst
  project_update_visible/__init__.py
  project_update_visible/__manifest__.py
  project_update_visible/readme/CONTRIBUTORS.rst
  project_update_visible/readme/DESCRIPTION.rst
  project_update_visible/readme/USAGE.rst
  project_update_visible/static/description/icon.png
  project_update_visible/static/description/index.html
  project_update_visible/views/project_update_views.xml
  setup/project_update_visible/odoo/addons/project_update_visible
  setup/project_update_visible/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1188 [15.0][MIG] sale project service tracking copy tasks
  sale_project_copy_tasks/README.rst
  sale_project_copy_tasks/__init__.py
  sale_project_copy_tasks/__manifest__.py
  sale_project_copy_tasks/i18n/es.po
  sale_project_copy_tasks/i18n/sale_project_service_tracking_copy_tasks.pot
  sale_project_copy_tasks/models/__init__.py
  sale_project_copy_tasks/models/product_template.py
  sale_project_copy_tasks/models/sale_order.py
  sale_project_copy_tasks/models/sale_order_line.py
  sale_project_copy_tasks/readme/CONTEXT.rst
  sale_project_copy_tasks/readme/CONTRIBUTORS.rst
  sale_project_copy_tasks/readme/DESCRIPTION.rst
  sale_project_copy_tasks/readme/USAGE.rst
  sale_project_copy_tasks/static/description/icon.png
  sale_project_copy_tasks/static/description/index.html
  sale_project_copy_tasks/tests/__init__.py
  sale_project_copy_tasks/tests/test_copy_task.py
  sale_project_copy_tasks/views/product_template_views.xml
  sale_project_copy_tasks/views/sale_order_views.xml
  setup/sale_project_copy_tasks/odoo/addons/sale_project_copy_tasks
  setup/sale_project_copy_tasks/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1208 [16.0][MIG] project_task_pull_request: Migration to 16.0
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_AR.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/readme/CONTRIBUTORS.rst
  project_task_pull_request/readme/DESCRIPTION.rst
  project_task_pull_request/readme/USAGE.rst
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
  setup/project_task_pull_request/odoo/addons/project_task_pull_request
  setup/project_task_pull_request/setup.py
Labels: approved, ready to merge, bot is merging ⏳
