Repository OCA/project, pull requests merged in 2023-06, with the labels that each got.

#1103 [MIG][16.0] project_parent
  project_parent/README.rst
  project_parent/__init__.py
  project_parent/__manifest__.py
  project_parent/demo/project_project_demo.xml
  project_parent/i18n/es.po
  project_parent/i18n/fr.po
  project_parent/i18n/hr.po
  project_parent/i18n/nl_NL.po
  project_parent/i18n/project_parent.pot
  project_parent/i18n/pt_BR.po
  project_parent/i18n/sl.po
  project_parent/models/__init__.py
  project_parent/models/project_project.py
  project_parent/readme/CONTRIBUTORS.rst
  project_parent/readme/DESCRIPTION.rst
  project_parent/readme/USAGE.rst
  project_parent/static/description/icon.png
  project_parent/static/description/index.html
  project_parent/tests/__init__.py
  project_parent/tests/test_project_parent.py
  project_parent/views/project_parent_views.xml
  setup/project_parent/odoo/addons/project_parent
  setup/project_parent/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1061 [MIG] project_purchase_link: Migration to 16.
  project_purchase_link/README.rst
  project_purchase_link/__init__.py
  project_purchase_link/__manifest__.py
  project_purchase_link/i18n/es.po
  project_purchase_link/i18n/project_purchase_link.pot
  project_purchase_link/i18n/sl.po
  project_purchase_link/models/__init__.py
  project_purchase_link/models/project_project.py
  project_purchase_link/readme/CONTRIBUTORS.rst
  project_purchase_link/readme/DESCRIPTION.rst
  project_purchase_link/readme/USAGE.rst
  project_purchase_link/static/description/icon.png
  project_purchase_link/static/description/index.html
  project_purchase_link/tests/__init__.py
  project_purchase_link/tests/test_project_purchase_link.py
  project_purchase_link/views/project_project_view.xml
  setup/project_purchase_link/odoo/addons/project_purchase_link
  setup/project_purchase_link/setup.py
Labels: needs review, migration, bot is merging ⏳, stale

#1143 [15.0][MIG] project_administrator_restricted_visibility: Migration to version 15.0
  project_administrator_restricted_visibility/README.rst
  project_administrator_restricted_visibility/__init__.py
  project_administrator_restricted_visibility/__manifest__.py
  project_administrator_restricted_visibility/hooks.py
  project_administrator_restricted_visibility/i18n/it.po
  project_administrator_restricted_visibility/i18n/project_administrator_restricted_visibility.pot
  project_administrator_restricted_visibility/readme/CONFIGURE.rst
  project_administrator_restricted_visibility/readme/CONTRIBUTORS.rst
  project_administrator_restricted_visibility/readme/DESCRIPTION.rst
  project_administrator_restricted_visibility/readme/USAGE.rst
  project_administrator_restricted_visibility/security/project_security.xml
  project_administrator_restricted_visibility/static/description/icon.png
  project_administrator_restricted_visibility/static/description/index.html
  project_administrator_restricted_visibility/tests/__init__.py
  project_administrator_restricted_visibility/tests/test_project_administrator_restricted_visibility.py
  setup/project_administrator_restricted_visibility/odoo/addons/project_administrator_restricted_visibility
  setup/project_administrator_restricted_visibility/setup.py
Labels: approved, bot is merging ⏳

#1116 [16.0][MIG] project_timeline_hr_timesheet: Migration to version 16.0
  project_timeline_hr_timesheet/README.rst
  project_timeline_hr_timesheet/__init__.py
  project_timeline_hr_timesheet/__manifest__.py
  project_timeline_hr_timesheet/i18n/de.po
  project_timeline_hr_timesheet/i18n/es.po
  project_timeline_hr_timesheet/i18n/fr.po
  project_timeline_hr_timesheet/i18n/he.po
  project_timeline_hr_timesheet/i18n/it.po
  project_timeline_hr_timesheet/i18n/project_timeline_hr_timesheet.pot
  project_timeline_hr_timesheet/readme/CONTRIBUTORS.rst
  project_timeline_hr_timesheet/readme/DESCRIPTION.rst
  project_timeline_hr_timesheet/static/description/icon.png
  project_timeline_hr_timesheet/static/description/index.html
  project_timeline_hr_timesheet/static/src/scss/project_timeline_hr_timesheet.scss
  project_timeline_hr_timesheet/views/project_task_view.xml
  setup/project_timeline_hr_timesheet/odoo/addons/project_timeline_hr_timesheet
  setup/project_timeline_hr_timesheet/setup.py
Labels: approved, bot is merging ⏳
