Repository OCA/project, pull requests merged in 2023-04, with the labels that each got.

#1078 [15.0][MIG]project_stock_request : Migration to V15
  project_stock_request/README.rst
  project_stock_request/__init__.py
  project_stock_request/__manifest__.py
  project_stock_request/i18n/es_AR.po
  project_stock_request/i18n/hr.po
  project_stock_request/i18n/it.po
  project_stock_request/i18n/project_stock_request.pot
  project_stock_request/i18n/pt_BR.po
  project_stock_request/models/__init__.py
  project_stock_request/models/project.py
  project_stock_request/models/project_task.py
  project_stock_request/models/stock_request_order.py
  project_stock_request/readme/CONTRIBUTORS.rst
  project_stock_request/readme/CREDITS.rst
  project_stock_request/readme/DESCRIPTION.rst
  project_stock_request/readme/USAGE.rst
  project_stock_request/security/ir.model.access.csv
  project_stock_request/static/description/icon.png
  project_stock_request/static/description/index.html
  project_stock_request/views/project_task_views.xml
  project_stock_request/views/project_views.xml
  project_stock_request/views/stock_request_order_views.xml
  setup/project_stock_request/odoo/addons/project_stock_request
  setup/project_stock_request/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1063 [15.0][MIG] project_template_milestone: Migration to 15.0.
  project_template_milestone/README.rst
  project_template_milestone/__init__.py
  project_template_milestone/__manifest__.py
  project_template_milestone/i18n/de.po
  project_template_milestone/i18n/it.po
  project_template_milestone/i18n/project_template_milestone.pot
  project_template_milestone/i18n/pt.po
  project_template_milestone/i18n/pt_BR.po
  project_template_milestone/i18n/sl.po
  project_template_milestone/models/__init__.py
  project_template_milestone/models/project.py
  project_template_milestone/readme/CONTRIBUTORS.rst
  project_template_milestone/readme/DESCRIPTION.rst
  project_template_milestone/readme/USAGE.rst
  project_template_milestone/static/description/icon.png
  project_template_milestone/static/description/index.html
  project_template_milestone/tests/__init__.py
  project_template_milestone/tests/test_project_template.py
  setup/project_template_milestone/odoo/addons/project_template_milestone
  setup/project_template_milestone/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1100 [FIX] project_forecast_line: disappearing forecast
  project_forecast_line/models/hr_employee.py
Labels: bot is merging ⏳

#1099 [14.0][IMP] project_task_add_very_high: add message in chatter
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/readme/DESCRIPTION.rst
  project_task_add_very_high/static/description/image_add_chatter.png
Labels: approved, bot is merging ⏳

#1102 [14.0][MIG] project_task_send_by_mail: Migration to 14.0
  project_task_send_by_mail/README.rst
  project_task_send_by_mail/__init__.py
  project_task_send_by_mail/__manifest__.py
  project_task_send_by_mail/data/task_template.xml
  project_task_send_by_mail/i18n/ar.po
  project_task_send_by_mail/i18n/ca.po
  project_task_send_by_mail/i18n/de.po
  project_task_send_by_mail/i18n/el.po
  project_task_send_by_mail/i18n/es.po
  project_task_send_by_mail/i18n/es_CR.po
  project_task_send_by_mail/i18n/es_MX.po
  project_task_send_by_mail/i18n/es_VE.po
  project_task_send_by_mail/i18n/fi.po
  project_task_send_by_mail/i18n/fr.po
  project_task_send_by_mail/i18n/gl.po
  project_task_send_by_mail/i18n/hr.po
  project_task_send_by_mail/i18n/hr_HR.po
  project_task_send_by_mail/i18n/hu.po
  project_task_send_by_mail/i18n/it.po
  project_task_send_by_mail/i18n/ja.po
  project_task_send_by_mail/i18n/lt.po
  project_task_send_by_mail/i18n/lv.po
  project_task_send_by_mail/i18n/mk.po
  project_task_send_by_mail/i18n/mn.po
  project_task_send_by_mail/i18n/nl.po
  project_task_send_by_mail/i18n/pl.po
  project_task_send_by_mail/i18n/project_task_send_by_mail.pot
  project_task_send_by_mail/i18n/pt.po
  project_task_send_by_mail/i18n/pt_BR.po
  project_task_send_by_mail/i18n/pt_PT.po
  project_task_send_by_mail/i18n/ro.po
  project_task_send_by_mail/i18n/sl.po
  project_task_send_by_mail/i18n/sv.po
  project_task_send_by_mail/i18n/tr.po
  project_task_send_by_mail/i18n/uk.po
  project_task_send_by_mail/i18n/zh_CN.po
  project_task_send_by_mail/models/__init__.py
  project_task_send_by_mail/models/project.py
  project_task_send_by_mail/readme/CONTRIBUTORS.rst
  project_task_send_by_mail/readme/DESCRIPTION.rst
  project_task_send_by_mail/readme/USAGE.rst
  project_task_send_by_mail/static/description/icon.png
  project_task_send_by_mail/static/description/index.html
  project_task_send_by_mail/tests/__init__.py
  project_task_send_by_mail/tests/test_project_task_send_by_mail.py
  project_task_send_by_mail/views/project_task_views.xml
  setup/project_task_send_by_mail/odoo/addons/project_task_send_by_mail
  setup/project_task_send_by_mail/setup.py
Labels: bot is merging ⏳

#1090 [14.0][ADD] project_task_recurring_activity
  project_task_recurring_activity/README.rst
  project_task_recurring_activity/__init__.py
  project_task_recurring_activity/__manifest__.py
  project_task_recurring_activity/data/recurring_activity.xml
  project_task_recurring_activity/models/__init__.py
  project_task_recurring_activity/models/project_task.py
  project_task_recurring_activity/models/project_task_recurrence.py
  project_task_recurring_activity/models/recurring_activity.py
  project_task_recurring_activity/readme/CONFIGURE.rst
  project_task_recurring_activity/readme/CONTRIBUTORS.rst
  project_task_recurring_activity/readme/DESCRIPTION.rst
  project_task_recurring_activity/readme/USAGE.rst
  project_task_recurring_activity/security/ir.model.access.csv
  project_task_recurring_activity/static/description/icon.png
  project_task_recurring_activity/tests/__init__.py
  project_task_recurring_activity/tests/test_project_recurrence.py
  project_task_recurring_activity/views/project_task.xml
  project_task_recurring_activity/views/recurring_activity.xml
  setup/project_task_recurring_activity/odoo/addons/project_task_recurring_activity
  setup/project_task_recurring_activity/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1108 [15.0][IMP] project_timesheet_time_control: Add base.group_multi_company group to company_id field from wizard
  project_timesheet_time_control/wizards/hr_timesheet_switch_view.xml
Labels: bot is merging ⏳
