Repository OCA/project, pull requests merged in 2023-05, with the labels that each got.

#1035 [16.0] [MIG] project_parent_task_filter
  project_parent_task_filter/README.rst
  project_parent_task_filter/__init__.py
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/data/res_config_data.xml
  project_parent_task_filter/i18n/ca.po
  project_parent_task_filter/i18n/de.po
  project_parent_task_filter/i18n/es.po
  project_parent_task_filter/i18n/es_AR.po
  project_parent_task_filter/i18n/es_ES.po
  project_parent_task_filter/i18n/fr.po
  project_parent_task_filter/i18n/fr_FR.po
  project_parent_task_filter/i18n/nl_NL.po
  project_parent_task_filter/i18n/project_parent_task_filter.pot
  project_parent_task_filter/models/__init__.py
  project_parent_task_filter/models/project_task.py
  project_parent_task_filter/readme/CONTRIBUTORS.rst
  project_parent_task_filter/readme/DESCRIPTION.rst
  project_parent_task_filter/readme/ROADMAP.rst
  project_parent_task_filter/readme/USAGE.rst
  project_parent_task_filter/static/description/icon.png
  project_parent_task_filter/static/description/index.html
  project_parent_task_filter/views/project_task.xml
  setup/project_parent_task_filter/odoo/addons/project_parent_task_filter
  setup/project_parent_task_filter/setup.py
Labels: bot is merging ⏳

#1101 [14.0][ADD] project_sequence
  .copier-answers.yml
  .github/workflows/test.yml
  project_sequence/README.rst
  project_sequence/__init__.py
  project_sequence/__manifest__.py
  project_sequence/data/ir_sequence.xml
  project_sequence/i18n/es.po
  project_sequence/models/__init__.py
  project_sequence/models/project_project.py
  project_sequence/readme/CONTRIBUTORS.rst
  project_sequence/readme/CREDITS.rst
  project_sequence/readme/DESCRIPTION.rst
  project_sequence/readme/USAGE.rst
  project_sequence/static/description/icon.png
  project_sequence/tests/__init__.py
  project_sequence/tests/test_project_sequence.py
  project_sequence/views/project_project.xml
  project_wbs/models/project_project.py
  setup/project_sequence/odoo/addons/project_sequence
  setup/project_sequence/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1114 [MIG] project_sequence: migrate to v15
  project_sequence/README.rst
  project_sequence/__init__.py
  project_sequence/__manifest__.py
  project_sequence/data/ir_sequence.xml
  project_sequence/i18n/es.po
  project_sequence/i18n/project_sequence.pot
  project_sequence/models/__init__.py
  project_sequence/models/project_project.py
  project_sequence/readme/CONFIGURE.rst
  project_sequence/readme/CONTRIBUTORS.rst
  project_sequence/readme/CREDITS.rst
  project_sequence/readme/DESCRIPTION.rst
  project_sequence/readme/USAGE.rst
  project_sequence/static/description/icon.png
  project_sequence/static/description/index.html
  project_sequence/tests/__init__.py
  project_sequence/tests/test_project_sequence.py
  project_sequence/views/project_project.xml
  project_sequence/wizards/__init__.py
  project_sequence/wizards/res_config_settings.py
  project_sequence/wizards/res_config_settings_view.xml
  setup/project_sequence/odoo/addons/project_sequence
  setup/project_sequence/setup.py
Labels: migration, bot is merging ⏳

#1120 [15.0][OU-ADD] project_hr: Convert m2o to m2m in project.task
  project_hr/migrations/15.0.1.0.0/post-migration.py
Labels: approved

#1117 [16.0][MIG] project_hr: Migration to version 16.0
  project_hr/README.rst
  project_hr/__init__.py
  project_hr/__manifest__.py
  project_hr/i18n/ca.po
  project_hr/i18n/de.po
  project_hr/i18n/es.po
  project_hr/i18n/hr.po
  project_hr/i18n/it.po
  project_hr/i18n/project_hr.pot
  project_hr/i18n/sl.po
  project_hr/models/__init__.py
  project_hr/models/hr_employee.py
  project_hr/models/project_project.py
  project_hr/models/project_task.py
  project_hr/models/res_users.py
  project_hr/readme/CONFIGURE.rst
  project_hr/readme/CONTRIBUTORS.rst
  project_hr/readme/DESCRIPTION.rst
  project_hr/readme/ROADMAP.rst
  project_hr/readme/USAGE.rst
  project_hr/static/description/icon.png
  project_hr/static/description/index.html
  project_hr/tests/__init__.py
  project_hr/tests/test_project_hr.py
  project_hr/views/project_project_views.xml
  project_hr/views/project_task_views.xml
  setup/project_hr/odoo/addons/project_hr
  setup/project_hr/setup.py
Labels: approved, bot is merging ⏳
