Repository OCA/project, pull requests merged in 2024-05, with the labels that each got.

#1226 [14.0][FIX] project_wbs: Manager consistency between project and analytic account
  project_wbs/README.rst
  project_wbs/models/project_project.py
  project_wbs/readme/DESCRIPTION.rst
  project_wbs/static/description/index.html
Labels: approved, bot is merging ⏳

#1255 [15.0][FIX] project_wbs: respect the code that user manually puts in the project
  project_wbs/models/project_project.py
Labels: approved, ready to merge, bot is merging ⏳

#1258 [16.0][ADD] project_milestone_tree
  project_milestone_tree/README.rst
  project_milestone_tree/__init__.py
  project_milestone_tree/__manifest__.py
  project_milestone_tree/readme/DESCRIPTION.rst
  project_milestone_tree/static/description/icon.png
  project_milestone_tree/static/description/index.html
  project_milestone_tree/views/project_milestone.xml
  setup/project_milestone_tree/odoo/addons/project_milestone_tree
  setup/project_milestone_tree/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1249 [14.0][ADD] new module: project_forecast_line_milestone
  project_forecast_line_milestone/README.rst
  project_forecast_line_milestone/__init__.py
  project_forecast_line_milestone/__manifest__.py
  project_forecast_line_milestone/models/__init__.py
  project_forecast_line_milestone/models/project_task.py
  project_forecast_line_milestone/readme/CONTRIBUTORS.rst
  project_forecast_line_milestone/readme/DESCRIPTION.rst
  project_forecast_line_milestone/static/description/icon.png
  project_forecast_line_milestone/static/description/index.html
  project_forecast_line_milestone/tests/__init__.py
  project_forecast_line_milestone/tests/test_forecast_line_milestone.py
  setup/project_forecast_line_milestone/odoo/addons/project_forecast_line_milestone
  setup/project_forecast_line_milestone/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1263 [15.0][MIG] project_forecast_line_deadline
  project_forecast_line_deadline/README.rst
  project_forecast_line_deadline/__init__.py
  project_forecast_line_deadline/__manifest__.py
  project_forecast_line_deadline/i18n/es.po
  project_forecast_line_deadline/i18n/project_forecast_line_deadline.pot
  project_forecast_line_deadline/models/__init__.py
  project_forecast_line_deadline/models/project_task.py
  project_forecast_line_deadline/readme/CONTRIBUTORS.rst
  project_forecast_line_deadline/readme/DESCRIPTION.rst
  project_forecast_line_deadline/readme/USAGE.rst
  project_forecast_line_deadline/static/description/icon.png
  project_forecast_line_deadline/static/description/index.html
  project_forecast_line_deadline/tests/__init__.py
  project_forecast_line_deadline/tests/test_forecast_line_deadline.py
  setup/project_forecast_line_deadline/odoo/addons/project_forecast_line_deadline
  setup/project_forecast_line_deadline/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1277 [17.0][MIG] project_task_tag: Migration to 17.0
  project_task_tag/README.rst
  project_task_tag/__init__.py
  project_task_tag/__manifest__.py
  project_task_tag/pyproject.toml
  project_task_tag/readme/CONTRIBUTORS.md
  project_task_tag/readme/DESCRIPTION.md
  project_task_tag/static/description/index.html
  project_task_tag/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#1279 [14.0][FIX] project_wbs: Don't change project.project description
  project_wbs/models/project_project.py
Labels: approved, bot is merging ⏳

#1280 [15.0][FIX] project_wbs: Don't change project.project description
  project_wbs/models/project_project.py
Labels: approved, bot is merging ⏳

#1254 [14.0][backport] project_forecast_line_bokeh_chart
  project_forecast_line_bokeh_chart/README.rst
  project_forecast_line_bokeh_chart/__init__.py
  project_forecast_line_bokeh_chart/__manifest__.py
  project_forecast_line_bokeh_chart/i18n/fr.po
  project_forecast_line_bokeh_chart/i18n/project_forecast_line_bokeh_chart.pot
  project_forecast_line_bokeh_chart/models/__init__.py
  project_forecast_line_bokeh_chart/models/forecast_line.py
  project_forecast_line_bokeh_chart/readme/CONTRIBUTORS.rst
  project_forecast_line_bokeh_chart/readme/DESCRIPTION.rst
  project_forecast_line_bokeh_chart/report/__init__.py
  project_forecast_line_bokeh_chart/report/forecast_line_reporting.py
  project_forecast_line_bokeh_chart/report/forecast_line_reporting_views.xml
  project_forecast_line_bokeh_chart/security/ir.model.access.csv
  project_forecast_line_bokeh_chart/static/description/icon.png
  project_forecast_line_bokeh_chart/static/description/index.html
  setup/project_forecast_line_bokeh_chart/odoo/addons/project_forecast_line_bokeh_chart
  setup/project_forecast_line_bokeh_chart/setup.py
Labels: approved, bot is merging ⏳
