Repository OCA/project, pull requests merged in 2024-04, with the labels that each got.

#1195 [17.0][MIG] project_task_stage_mgmt: Migration to 17.0
  project_task_stage_mgmt/README.rst
  project_task_stage_mgmt/__init__.py
  project_task_stage_mgmt/__manifest__.py
  project_task_stage_mgmt/i18n/it.po
  project_task_stage_mgmt/i18n/project_task_stage_mgmt.pot
  project_task_stage_mgmt/i18n/pt_BR.po
  project_task_stage_mgmt/pyproject.toml
  project_task_stage_mgmt/readme/CONTRIBUTORS.md
  project_task_stage_mgmt/readme/DESCRIPTION.md
  project_task_stage_mgmt/static/description/icon.png
  project_task_stage_mgmt/static/description/index.html
  project_task_stage_mgmt/views/project.xml
Labels: approved, bot is merging ⏳, stale

#1192 [14.0][ADD] project_task_description_template: new module
  project_task_description_template/README.rst
  project_task_description_template/__init__.py
  project_task_description_template/__manifest__.py
  project_task_description_template/data/demo.xml
  project_task_description_template/models/__init__.py
  project_task_description_template/models/project_project.py
  project_task_description_template/models/project_task.py
  project_task_description_template/models/project_task_template.py
  project_task_description_template/readme/CONTRIBUTORS.md
  project_task_description_template/readme/DESCRIPTION.md
  project_task_description_template/readme/USAGE.md
  project_task_description_template/security/ir.model.access.csv
  project_task_description_template/static/description/icon.png
  project_task_description_template/static/description/index.html
  project_task_description_template/static/src/js/onchange_confirm_widget.js
  project_task_description_template/tests/__init__.py
  project_task_description_template/tests/test_task_template.py
  project_task_description_template/views/assets.xml
  project_task_description_template/views/project_task_template_views.xml
  project_task_description_template/views/project_views.xml
  setup/project_task_description_template/odoo/addons/project_task_description_template
  setup/project_task_description_template/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1259 [16.0][FIX] project_timeline: Fix demo task dates
  project_timeline/demo/project_task_demo.xml
Labels: approved, bot is merging ⏳

#1248 [14.0][ADD] new module: project_forecast_line_priority
  project_forecast_line_priority/README.rst
  project_forecast_line_priority/__init__.py
  project_forecast_line_priority/__manifest__.py
  project_forecast_line_priority/data/ir_actions_server.xml
  project_forecast_line_priority/models/__init__.py
  project_forecast_line_priority/models/project_task.py
  project_forecast_line_priority/models/res_company.py
  project_forecast_line_priority/models/res_config_settings.py
  project_forecast_line_priority/readme/CONTRIBUTORS.rst
  project_forecast_line_priority/readme/DESCRIPTION.rst
  project_forecast_line_priority/static/description/icon.png
  project_forecast_line_priority/static/description/index.html
  project_forecast_line_priority/tests/__init__.py
  project_forecast_line_priority/tests/test_forecast_line_priority.py
  project_forecast_line_priority/views/res_config_settings.xml
  setup/project_forecast_line_priority/odoo/addons/project_forecast_line_priority
  setup/project_forecast_line_priority/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1270 [16.0][FIX] project_role: pass company from env
  project_role/models/project_project.py
  project_role/tests/test_project_role.py
Labels: bot is merging ⏳

#1227 [15.0][FIX] project_wbs: Manager consistency between project and analytic accunt
  project_wbs/README.rst
  project_wbs/models/project_project.py
  project_wbs/readme/DESCRIPTION.rst
  project_wbs/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1251 [17.0][MIG] project_parent
  project_parent/README.rst
  project_parent/__init__.py
  project_parent/__manifest__.py
  project_parent/demo/project_project_demo.xml
  project_parent/i18n/es.po
  project_parent/i18n/fr.po
  project_parent/i18n/hr.po
  project_parent/i18n/it.po
  project_parent/i18n/nl.po
  project_parent/i18n/nl_NL.po
  project_parent/i18n/project_parent.pot
  project_parent/i18n/pt_BR.po
  project_parent/i18n/sl.po
  project_parent/models/__init__.py
  project_parent/models/project_project.py
  project_parent/pyproject.toml
  project_parent/readme/CONTRIBUTORS.md
  project_parent/readme/DESCRIPTION.md
  project_parent/readme/USAGE.md
  project_parent/static/description/icon.png
  project_parent/static/description/index.html
  project_parent/tests/__init__.py
  project_parent/tests/test_project_parent.py
  project_parent/views/project_parent_views.xml
Labels: approved, ready to merge, bot is merging ⏳
