Repository OCA/project, pull requests merged in 2024-07, with the labels that each got.

#1308 [15.0][FIX] project_hr: remove unnecessary migration causing errors
  project_hr/migrations/15.0.1.0.0/post-migration.py
Labels: approved

#1310 [14.0][MIG] project_task_note: Migration to 14.0
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/readme/CONTEXT.rst
  project_task_note/readme/CONTRIBUTORS.rst
  project_task_note/readme/DESCRIPTION.rst
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
  setup/project_task_note/odoo/addons/project_task_note
  setup/project_task_note/setup.py
Labels: bot is merging ⏳

#1304 [16.0][MIG] project_task_project_required
  project_task_project_required/README.rst
  project_task_project_required/__init__.py
  project_task_project_required/__manifest__.py
  project_task_project_required/demo/res_company.xml
  project_task_project_required/i18n/es.po
  project_task_project_required/i18n/it.po
  project_task_project_required/i18n/project_task_project_required.pot
  project_task_project_required/i18n/pt_BR.po
  project_task_project_required/models/__init__.py
  project_task_project_required/models/project_task.py
  project_task_project_required/models/res_company.py
  project_task_project_required/models/res_config_settings.py
  project_task_project_required/readme/CONFIGURE.rst
  project_task_project_required/readme/CONTRIBUTORS.rst
  project_task_project_required/readme/DESCRIPTION.rst
  project_task_project_required/static/description/icon.png
  project_task_project_required/static/description/index.html
  project_task_project_required/tests/__init__.py
  project_task_project_required/tests/test_project_task_project_required.py
  project_task_project_required/views/project_task.xml
  project_task_project_required/views/res_config_settings_views.xml
  setup/project_task_project_required/odoo/addons/project_task_project_required
  setup/project_task_project_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳
