Repository OCA/project, pull requests merged in 2024-01, with the labels that each got.

#1213 [15.0][FIX] project_wbs: fix code, indent consistency and list view
  project_wbs/models/project_project.py
  project_wbs/view/project_project_view.xml
Labels: approved, bot is merging ⏳

#1215 [16.0][FIX] project_timeline: Remove redundant view
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/views/project_project_view.xml
Labels: approved, bot is merging ⏳

#1196 [15.0][ADD] project_sale_order_link
  project_sale_order_link/README.rst
  project_sale_order_link/__init__.py
  project_sale_order_link/__manifest__.py
  project_sale_order_link/i18n/es.po
  project_sale_order_link/i18n/project_sale_order_link.pot
  project_sale_order_link/models/__init__.py
  project_sale_order_link/models/project.py
  project_sale_order_link/readme/CONTEXT.rst
  project_sale_order_link/readme/CONTRIBUTORS.rst
  project_sale_order_link/readme/DESCRIPTION.rst
  project_sale_order_link/readme/USAGE.rst
  project_sale_order_link/static/description/icon.png
  project_sale_order_link/static/description/index.html
  project_sale_order_link/tests/__init__.py
  project_sale_order_link/tests/test_project_sale_order_link.py
  project_sale_order_link/views/project_views.xml
  setup/project_sale_order_link/odoo/addons/project_sale_order_link
  setup/project_sale_order_link/setup.py
Labels: needs review, approved, bot is merging ⏳

#1211 [16.0][MIG] sale_project_copy_tasks
  sale_project_copy_tasks/README.rst
  sale_project_copy_tasks/__init__.py
  sale_project_copy_tasks/__manifest__.py
  sale_project_copy_tasks/i18n/es.po
  sale_project_copy_tasks/i18n/it.po
  sale_project_copy_tasks/i18n/sale_project_copy_tasks.pot
  sale_project_copy_tasks/i18n/sale_project_service_tracking_copy_tasks.pot
  sale_project_copy_tasks/models/__init__.py
  sale_project_copy_tasks/models/product_template.py
  sale_project_copy_tasks/models/sale_order.py
  sale_project_copy_tasks/models/sale_order_line.py
  sale_project_copy_tasks/readme/CONTEXT.rst
  sale_project_copy_tasks/readme/CONTRIBUTORS.rst
  sale_project_copy_tasks/readme/DESCRIPTION.rst
  sale_project_copy_tasks/readme/USAGE.rst
  sale_project_copy_tasks/static/description/icon.png
  sale_project_copy_tasks/static/description/index.html
  sale_project_copy_tasks/tests/__init__.py
  sale_project_copy_tasks/tests/test_copy_task.py
  sale_project_copy_tasks/views/product_template_views.xml
  sale_project_copy_tasks/views/sale_order_views.xml
  setup/sale_project_copy_tasks/odoo/addons/sale_project_copy_tasks
  setup/sale_project_copy_tasks/setup.py
Labels: approved, bot is merging ⏳

#1209 [16.0][MIG] project_task_code : alternative without functionality change
  project_task_code/README.rst
  project_task_code/__init__.py
  project_task_code/__manifest__.py
  project_task_code/data/task_sequence.xml
  project_task_code/hooks.py
  project_task_code/i18n/ar.po
  project_task_code/i18n/bg.po
  project_task_code/i18n/ca.po
  project_task_code/i18n/de.po
  project_task_code/i18n/el.po
  project_task_code/i18n/es.po
  project_task_code/i18n/es_AR.po
  project_task_code/i18n/es_CR.po
  project_task_code/i18n/es_MX.po
  project_task_code/i18n/es_VE.po
  project_task_code/i18n/fi.po
  project_task_code/i18n/fr.po
  project_task_code/i18n/fr_FR.po
  project_task_code/i18n/gl.po
  project_task_code/i18n/hr.po
  project_task_code/i18n/hr_HR.po
  project_task_code/i18n/hu.po
  project_task_code/i18n/it.po
  project_task_code/i18n/ja.po
  project_task_code/i18n/lt.po
  project_task_code/i18n/lv.po
  project_task_code/i18n/mk.po
  project_task_code/i18n/mn.po
  project_task_code/i18n/nl.po
  project_task_code/i18n/nl_NL.po
  project_task_code/i18n/pl.po
  project_task_code/i18n/project_task_code.pot
  project_task_code/i18n/pt.po
  project_task_code/i18n/pt_BR.po
  project_task_code/i18n/pt_PT.po
  project_task_code/i18n/ro.po
  project_task_code/i18n/sk.po
  project_task_code/i18n/sl.po
  project_task_code/i18n/sv.po
  project_task_code/i18n/tr.po
  project_task_code/i18n/uk.po
  project_task_code/i18n/zh_CN.po
  project_task_code/models/__init__.py
  project_task_code/models/project_task.py
  project_task_code/readme/CONFIGURE.rst
  project_task_code/readme/CONTRIBUTORS.rst
  project_task_code/readme/DESCRIPTION.rst
  project_task_code/readme/USAGE.rst
  project_task_code/static/description/icon.png
  project_task_code/static/description/index.html
  project_task_code/tests/__init__.py
  project_task_code/tests/test_project_task_code.py
  project_task_code/views/project_view.xml
  setup/project_task_code/odoo/addons/project_task_code
  setup/project_task_code/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#975 [14.0][BACKPORT] project_forecast_line from 15.0 to 14.0
  project_forecast_line/README.rst
  project_forecast_line/__init__.py
  project_forecast_line/__manifest__.py
  project_forecast_line/data/ir_cron.xml
  project_forecast_line/data/project_status.xml
  project_forecast_line/demo/forecast_role.xml
  project_forecast_line/demo/hr_employee.xml
  project_forecast_line/demo/hr_job.xml
  project_forecast_line/demo/product.xml
  project_forecast_line/demo/project.xml
  project_forecast_line/demo/res_users.xml
  project_forecast_line/demo/sale.xml
  project_forecast_line/i18n/fr.po
  project_forecast_line/i18n/project_forecast_line.pot
  project_forecast_line/models/__init__.py
  project_forecast_line/models/forecast_line.py
  project_forecast_line/models/forecast_line_mixin.py
  project_forecast_line/models/forecast_role.py
  project_forecast_line/models/hr_employee.py
  project_forecast_line/models/hr_leave.py
  project_forecast_line/models/product_template.py
  project_forecast_line/models/project_project.py
  project_forecast_line/models/project_status.py
  project_forecast_line/models/project_task.py
  project_forecast_line/models/res_company.py
  project_forecast_line/models/res_config_settings.py
  project_forecast_line/models/resource_calendar_leaves.py
  project_forecast_line/models/sale_order.py
  project_forecast_line/models/sale_order_line.py
  project_forecast_line/readme/CONFIGURATION.rst
  project_forecast_line/readme/CONTRIBUTORS.rst
  project_forecast_line/readme/DESCRIPTION.rst
  project_forecast_line/readme/USAGE.rst
  project_forecast_line/security/forecast_line_security.xml
  project_forecast_line/security/ir.model.access.csv
  project_forecast_line/static/description/icon.png
  project_forecast_line/static/description/index.html
  project_forecast_line/tests/__init__.py
  project_forecast_line/tests/test_forecast_line.py
  project_forecast_line/views/forecast_line_views.xml
  project_forecast_line/views/forecast_role_views.xml
  project_forecast_line/views/hr_employee_views.xml
  project_forecast_line/views/product_views.xml
  project_forecast_line/views/project_status_views.xml
  project_forecast_line/views/project_task_views.xml
  project_forecast_line/views/res_config_settings_views.xml
  project_forecast_line/views/sale_order_views.xml
  project_timesheet_time_control/tests/test_project_timesheet_time_control.py
  setup/project_forecast_line/odoo/addons/project_forecast_line
  setup/project_forecast_line/setup.py
Labels: bot is merging ⏳, no stale

#1113 [16.0][ADD] project_stage_extra_info
  project_stage_extra_info/README.rst
  project_stage_extra_info/__init__.py
  project_stage_extra_info/__manifest__.py
  project_stage_extra_info/models/__init__.py
  project_stage_extra_info/models/project_project_stage.py
  project_stage_extra_info/readme/CONTRIBUTORS.rst
  project_stage_extra_info/readme/DESCRIPTION.rst
  project_stage_extra_info/readme/USAGE.rst
  project_stage_extra_info/static/description/icon.png
  project_stage_extra_info/static/description/index.html
  project_stage_extra_info/views/project_stage_view.xml
  project_stage_extra_info/views/project_view.xml
  setup/project_stage_extra_info/odoo/addons/project_stage_extra_info
  setup/project_stage_extra_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1220 [16.0][FIX]project_task_code: fix view kanban
  project_task_code/views/project_view.xml
Labels: approved, bot is merging ⏳

#1223 [15.0][FIX] project_wbs: calculation of root analytic account
  project_wbs/models/account_analytic_account.py
Labels: approved, bot is merging ⏳

#1222 [16.0][MIG] project_administrator_restricted_visibility: Migration to 16.0
  project_administrator_restricted_visibility/README.rst
  project_administrator_restricted_visibility/__init__.py
  project_administrator_restricted_visibility/__manifest__.py
  project_administrator_restricted_visibility/hooks.py
  project_administrator_restricted_visibility/i18n/it.po
  project_administrator_restricted_visibility/i18n/project_administrator_restricted_visibility.pot
  project_administrator_restricted_visibility/readme/CONFIGURE.rst
  project_administrator_restricted_visibility/readme/CONTRIBUTORS.rst
  project_administrator_restricted_visibility/readme/DESCRIPTION.rst
  project_administrator_restricted_visibility/readme/USAGE.rst
  project_administrator_restricted_visibility/security/project_security.xml
  project_administrator_restricted_visibility/static/description/icon.png
  project_administrator_restricted_visibility/static/description/index.html
  project_administrator_restricted_visibility/tests/__init__.py
  project_administrator_restricted_visibility/tests/test_project_administrator_restricted_visibility.py
  project_administrator_restricted_visibility/tests/test_uninstall_hook.py
  setup/project_administrator_restricted_visibility/odoo/addons/project_administrator_restricted_visibility
  setup/project_administrator_restricted_visibility/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
