Repository OCA/project, pull requests merged in 2024-06, with the labels that each got.

#1275 [17.0][MIG] project_task_description_template
  project_task_description_template/README.rst
  project_task_description_template/__init__.py
  project_task_description_template/__manifest__.py
  project_task_description_template/i18n/es_MX.po
  project_task_description_template/i18n/it.po
  project_task_description_template/i18n/project_task_description_template.pot
  project_task_description_template/models/__init__.py
  project_task_description_template/models/project_task.py
  project_task_description_template/models/project_task_description_template.py
  project_task_description_template/pyproject.toml
  project_task_description_template/readme/CONTRIBUTORS.md
  project_task_description_template/readme/DESCRIPTION.md
  project_task_description_template/readme/USAGE.md
  project_task_description_template/security/ir.model.access.csv
  project_task_description_template/security/ir_rule_data.xml
  project_task_description_template/static/description/icon.png
  project_task_description_template/static/description/index.html
  project_task_description_template/views/project_task_description_template_view.xml
  project_task_description_template/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1281 [16.0][FIX] project_task_parent_filter: Recover create option in "My Tasks" tree view
  project_parent_task_filter/views/project_task.xml
Labels: approved, bot is merging ⏳

#1296 [16.0][FIX] project_stock: Avoid AccessError in the form view of tasks for users without permissions in stock.move
  project_stock/tests/common.py
  project_stock/tests/test_project_stock.py
  project_stock/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1302 [17.0][FIX] project_type: read access to group_project_user
  project_type/security/ir.model.access.csv
Labels: enhancement, needs review, bot is merging ⏳

#1295 [16.0][FIX] project_key: remove unnecessary French (France) translation file
  project_key/i18n/fr_FR.po
Labels: bot is merging ⏳
