Repository OCA/project, pull requests merged in 2024-11, with the labels that each got.

#1365 [17.0][MIG] project_task_note: Migration to version 17.0
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/it.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/pyproject.toml
  project_task_note/readme/CONTEXT.md
  project_task_note/readme/CONTRIBUTORS.md
  project_task_note/readme/DESCRIPTION.md
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
Labels: approved, bot is merging ⏳

#1368 [17.0][MIG] project_task_pull_request: Migration to 17.0
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_AR.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/pyproject.toml
  project_task_pull_request/readme/CONTRIBUTORS.md
  project_task_pull_request/readme/DESCRIPTION.md
  project_task_pull_request/readme/USAGE.md
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1329 [16.0][ADD] project_scrum
  project_scrum/README.rst
  project_scrum/__init__.py
  project_scrum/__manifest__.py
  project_scrum/data/ir_cron_data.xml
  project_scrum/models/__init__.py
  project_scrum/models/project.py
  project_scrum/models/project_sprint.py
  project_scrum/models/project_task.py
  project_scrum/readme/CONTRIBUTORS.rst
  project_scrum/readme/DESCRIPTION.rst
  project_scrum/readme/USAGE.rst
  project_scrum/security/ir.model.access.csv
  project_scrum/static/description/icon.png
  project_scrum/static/description/index.html
  project_scrum/tests/__init__.py
  project_scrum/tests/test_project_project.py
  project_scrum/tests/test_project_sprint.py
  project_scrum/tests/test_project_task.py
  project_scrum/views/project_sprint_views.xml
  project_scrum/views/project_task_views.xml
  project_scrum/views/project_views.xml
  setup/project_scrum/odoo/addons/project_scrum
  setup/project_scrum/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1369 [16.0][FIX] project_timeline: Remove overshadowing of date_end functionality
  project_timeline/models/project_task.py
Labels: approved, bot is merging ⏳

#1372 [16.0] [FIX] project_timeline: Add list view on projects
  project_timeline/views/project_project_view.xml
Labels: approved, bot is merging ⏳

#1297 [16.0][FIX] project_task_default_stage: Add group on task stages page
  project_task_default_stage/views/project_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1375 [17.0] [FIX] project_timeline: Add list view on projects
  project_timeline/views/project_project_view.xml
Labels: approved, bot is merging ⏳

#1374 [17.0][FIX] project_timeline: Remove overshadowing of date_end functionality
  project_timeline/models/project_task.py
Labels: approved, bot is merging ⏳

#1377 [16.0][IMP] project_timeline: Move planning fields out of notebook page
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳
