Repository OCA/project, pull requests merged in 2024-03, with the labels that each got.

#1246 [IMP] project_task_code: enable name search by Task Number
  project_task_code/__manifest__.py
  project_task_code/models/project_task.py
  project_task_code/tests/test_project_task_code.py
Labels: approved, bot is merging ⏳

#1252 [16.0][IMP] project_stock_product_set: Adapt wizard to changes in product_set
  project_stock_product_set/README.rst
  project_stock_product_set/__manifest__.py
  project_stock_product_set/readme/CONTRIBUTORS.rst
  project_stock_product_set/security/ir.model.access.csv
  project_stock_product_set/static/description/index.html
  project_stock_product_set/tests/test_project_stock_product_set.py
  project_stock_product_set/wizard/__init__.py
  project_stock_product_set/wizard/project_stock_product_set_wizard.py
  project_stock_product_set/wizard/project_stock_product_set_wizard_view.xml
Labels: approved, bot is merging ⏳

#1253 [16.0][FIX] project_timeline: Fix unassigned task color
  project_timeline/views/project_task_view.xml
Labels: bot is merging ⏳

#1219 [17.0][MIG] project_task_add_very_high
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/hooks.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_AR.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/fr_FR.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/pyproject.toml
  project_task_add_very_high/readme/CONTRIBUTORS.md
  project_task_add_very_high/readme/DESCRIPTION.md
  project_task_add_very_high/readme/USAGE.md
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/views/project_task_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1224 [17.0][MIG] project_type: Migration to 17.0
  project_type/README.rst
  project_type/__init__.py
  project_type/__manifest__.py
  project_type/i18n/ca.po
  project_type/i18n/de.po
  project_type/i18n/es.po
  project_type/i18n/es_AR.po
  project_type/i18n/fr.po
  project_type/i18n/fr_FR.po
  project_type/i18n/it.po
  project_type/i18n/nl.po
  project_type/i18n/project_type.pot
  project_type/i18n/pt_BR.po
  project_type/models/__init__.py
  project_type/models/project_project.py
  project_type/models/project_task.py
  project_type/models/project_type.py
  project_type/pyproject.toml
  project_type/readme/CONTRIBUTORS.md
  project_type/readme/DESCRIPTION.md
  project_type/readme/USAGE.md
  project_type/security/ir.model.access.csv
  project_type/static/description/icon.png
  project_type/static/description/index.html
  project_type/tests/__init__.py
  project_type/tests/test_project_type.py
  project_type/views/project_project_views.xml
  project_type/views/project_task_views.xml
  project_type/views/project_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1232 [17.0][MIG] project_task_default_stage: Migration to 17.0
  project_task_default_stage/README.rst
  project_task_default_stage/__init__.py
  project_task_default_stage/__manifest__.py
  project_task_default_stage/data/project_data.xml
  project_task_default_stage/i18n/bg.po
  project_task_default_stage/i18n/ca.po
  project_task_default_stage/i18n/cs_CZ.po
  project_task_default_stage/i18n/de.po
  project_task_default_stage/i18n/el_GR.po
  project_task_default_stage/i18n/es.po
  project_task_default_stage/i18n/es_AR.po
  project_task_default_stage/i18n/es_CO.po
  project_task_default_stage/i18n/es_MX.po
  project_task_default_stage/i18n/fi.po
  project_task_default_stage/i18n/fr.po
  project_task_default_stage/i18n/fr_FR.po
  project_task_default_stage/i18n/gl.po
  project_task_default_stage/i18n/hr.po
  project_task_default_stage/i18n/hu.po
  project_task_default_stage/i18n/it.po
  project_task_default_stage/i18n/nb.po
  project_task_default_stage/i18n/nb_NO.po
  project_task_default_stage/i18n/nl.po
  project_task_default_stage/i18n/nl_NL.po
  project_task_default_stage/i18n/pl.po
  project_task_default_stage/i18n/project_task_default_stage.pot
  project_task_default_stage/i18n/pt.po
  project_task_default_stage/i18n/pt_BR.po
  project_task_default_stage/i18n/pt_PT.po
  project_task_default_stage/i18n/ru.po
  project_task_default_stage/i18n/sk.po
  project_task_default_stage/i18n/sl.po
  project_task_default_stage/i18n/tr.po
  project_task_default_stage/i18n/zh_CN.po
  project_task_default_stage/models/__init__.py
  project_task_default_stage/models/project.py
  project_task_default_stage/models/project_task_type.py
  project_task_default_stage/pyproject.toml
  project_task_default_stage/readme/CONFIGURE.md
  project_task_default_stage/readme/CONTRIBUTORS.md
  project_task_default_stage/readme/DESCRIPTION.md
  project_task_default_stage/static/description/icon.png
  project_task_default_stage/static/description/index.html
  project_task_default_stage/tests/__init__.py
  project_task_default_stage/tests/test_project_task_default_stage.py
  project_task_default_stage/views/project_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1210 [16.0][MIG] project_key
  project_key/README.rst
  project_key/__init__.py
  project_key/__manifest__.py
  project_key/controllers/__init__.py
  project_key/controllers/main.py
  project_key/hooks.py
  project_key/i18n/de.po
  project_key/i18n/es_AR.po
  project_key/i18n/fr.po
  project_key/i18n/fr_FR.po
  project_key/i18n/it.po
  project_key/i18n/project_key.pot
  project_key/models/__init__.py
  project_key/models/project_project.py
  project_key/models/project_task.py
  project_key/readme/CONTRIBUTORS.rst
  project_key/readme/DESCRIPTION.rst
  project_key/readme/USAGE.rst
  project_key/static/description/icon.png
  project_key/static/description/index.html
  project_key/tests/__init__.py
  project_key/tests/test_common.py
  project_key/tests/test_controller.py
  project_key/tests/test_project.py
  project_key/tests/test_task.py
  project_key/views/project_key_views.xml
  setup/project_key/odoo/addons/project_key
  setup/project_key/setup.py
Labels: approved, ready to merge, bot is merging ⏳
