Repository OCA/project, pull requests merged in 2024-09, with the labels that each got.

#1288 [14.0][ADD] project_milestone: Enable chatter on project milestone form
  project_milestone/__manifest__.py
  project_milestone/models/project_milestone.py
  project_milestone/views/project_milestone.xml
Labels: approved, bot is merging ⏳

#1338 [17.0][IMP] project_type: copy type_id on project/task duplicate
  project_type/models/project_project.py
  project_type/models/project_task.py
Labels: approved, bot is merging ⏳

#1339 [16.0][IMP] project_type: copy type_id on project/task duplicate
  project_type/models/project_project.py
  project_type/models/project_task.py
Labels: approved, merged 🎉

#1335 [14.0][IMP]project_timeline: improved timeline handling for project tasks
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_task_demo.xml
  project_timeline/hooks.py
  project_timeline/migrations/14.0.2.0.0/post-migration.py
  project_timeline/migrations/14.0.2.0.0/pre-migration.py
  project_timeline/models/project_task.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/readme/USAGE.rst
  project_timeline/static/description/index.html
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1284 [14.0][FIX] project_milestone : Wrong assignment of tasks to milestones when duplicating a project #1283
  project_milestone/models/project.py
  project_milestone/tests/test_project_milestone.py
Labels: approved, bot is merging ⏳

#1311 [16.0] [ADD] project_merge
  project_merge/README.rst
  project_merge/__init__.py
  project_merge/__manifest__.py
  project_merge/readme/CONTRIBUTORS.rst
  project_merge/readme/DESCRIPTION.rst
  project_merge/readme/USAGE.rst
  project_merge/security/ir.model.access.csv
  project_merge/static/description/icon.png
  project_merge/static/description/index.html
  project_merge/tests/__init__.py
  project_merge/tests/test_project_merge.py
  project_merge/wizard/__init__.py
  project_merge/wizard/project_task_merge.py
  project_merge/wizard/project_task_merge_views.xml
  setup/project_merge/odoo/addons/project_merge
  setup/project_merge/setup.py
Labels: approved, ready to merge, bot is merging ⏳
