Repository OCA/project, pull requests merged in 2024-12, with the labels that each got.

#1291 [17.0][MIG] project_administrator_restricted_visibility: Migration to 17.0
  project_administrator_restricted_visibility/README.rst
  project_administrator_restricted_visibility/__init__.py
  project_administrator_restricted_visibility/__manifest__.py
  project_administrator_restricted_visibility/hooks.py
  project_administrator_restricted_visibility/i18n/it.po
  project_administrator_restricted_visibility/i18n/project_administrator_restricted_visibility.pot
  project_administrator_restricted_visibility/pyproject.toml
  project_administrator_restricted_visibility/readme/CONFIGURE.md
  project_administrator_restricted_visibility/readme/CONTRIBUTORS.md
  project_administrator_restricted_visibility/readme/DESCRIPTION.md
  project_administrator_restricted_visibility/readme/USAGE.md
  project_administrator_restricted_visibility/security/project_security.xml
  project_administrator_restricted_visibility/static/description/icon.png
  project_administrator_restricted_visibility/static/description/index.html
  project_administrator_restricted_visibility/tests/__init__.py
  project_administrator_restricted_visibility/tests/test_project_administrator_restricted_visibility.py
  project_administrator_restricted_visibility/tests/test_uninstall_hook.py
Labels: approved, ready to merge, bot is merging ⏳

#1298 [14.0] Replace 'Camptocamp SA' with 'Camptocamp'
  project_forecast_line/__manifest__.py
  project_forecast_line_bokeh_chart/__manifest__.py
Labels: approved, bot is merging ⏳

#1299 [15.0] Replace 'Camptocamp SA' with 'Camptocamp'
  project_forecast_line/README.rst
  project_forecast_line/__manifest__.py
  project_forecast_line/static/description/index.html
  project_forecast_line_bokeh_chart/README.rst
  project_forecast_line_bokeh_chart/__manifest__.py
  project_forecast_line_bokeh_chart/static/description/index.html
  project_forecast_line_holidays_public/README.rst
  project_forecast_line_holidays_public/__manifest__.py
  project_forecast_line_holidays_public/static/description/index.html
Labels: approved, bot is merging ⏳

#1394 [17.0][IMP] sale_project_task_recurrency: Allow forcing a specific month when the recurrence is yearly
  sale_project_task_recurrency/models/product_template.py
  sale_project_task_recurrency/models/sale_order_line.py
  sale_project_task_recurrency/tests/test_product_task_recurrency.py
  sale_project_task_recurrency/views/product_template_views.xml
Labels: bot is merging ⏳

#1370 [MIG] project_sequence: Migration to 18.0
  project_sequence/README.rst
  project_sequence/__init__.py
  project_sequence/__manifest__.py
  project_sequence/data/ir_sequence.xml
  project_sequence/i18n/de.po
  project_sequence/i18n/es.po
  project_sequence/i18n/it.po
  project_sequence/i18n/nl.po
  project_sequence/i18n/project_sequence.pot
  project_sequence/models/__init__.py
  project_sequence/models/project_project.py
  project_sequence/pyproject.toml
  project_sequence/readme/CONFIGURE.md
  project_sequence/readme/CONTRIBUTORS.md
  project_sequence/readme/CREDITS.md
  project_sequence/readme/DESCRIPTION.md
  project_sequence/readme/USAGE.md
  project_sequence/static/description/icon.png
  project_sequence/static/description/index.html
  project_sequence/tests/__init__.py
  project_sequence/tests/test_project_sequence.py
  project_sequence/views/project_project.xml
  project_sequence/wizards/__init__.py
  project_sequence/wizards/res_config_settings.py
  project_sequence/wizards/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1363 [16.0][IMP][project_parent] Hide button box if no children projects
  project_parent/views/project_parent_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1396 [17.0][IMP] sale_project_task_recurrency: Add options to force month intervals for Quarter and Semester
  sale_project_task_recurrency/models/product_template.py
  sale_project_task_recurrency/models/sale_order_line.py
  sale_project_task_recurrency/tests/test_product_task_recurrency.py
  sale_project_task_recurrency/views/product_template_views.xml
Labels: approved, bot is merging ⏳
