Repository OCA/project, pull requests merged in 2024-10, with the labels that each got.

#1345 [14.0][IMP] project_timeline: Add planned_date_* fields to the task tree view
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1342 [15.0][IMP] project_timeline: improved timeline handling for project tasks
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_task_demo.xml
  project_timeline/hooks.py
  project_timeline/migrations/15.0.2.0.0/post-migration.py
  project_timeline/migrations/15.0.2.0.0/pre-migration.py
  project_timeline/models/project_task.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/readme/USAGE.rst
  project_timeline/static/description/index.html
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1346 [16.0][IMP] project_timeline: improved timeline handling for project tasks
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_task_demo.xml
  project_timeline/hooks.py
  project_timeline/migrations/16.0.2.0.0/post-migration.py
  project_timeline/migrations/16.0.2.0.0/pre-migration.py
  project_timeline/models/project_task.py
  project_timeline/readme/CONTRIBUTORS.rst
  project_timeline/readme/USAGE.rst
  project_timeline/static/description/index.html
  project_timeline/tests/__init__.py
  project_timeline/tests/test_project_timeline.py
  project_timeline/tests/test_task_date_constraints.py
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1340 [16.0][FIX]project_key: Fixed Installation of module on fresh database with demo data.
  project_key/models/project_project.py
Labels: approved, ready to merge, bot is merging ⏳

#1348 [16.0][ADD] project_tag_hierarchy: New module
  project_tag_hierarchy/README.rst
  project_tag_hierarchy/__init__.py
  project_tag_hierarchy/__manifest__.py
  project_tag_hierarchy/i18n/es.po
  project_tag_hierarchy/i18n/project_tag_hierarchy.pot
  project_tag_hierarchy/models/__init__.py
  project_tag_hierarchy/models/project_tags.py
  project_tag_hierarchy/readme/CONTRIBUTORS.rst
  project_tag_hierarchy/readme/DESCRIPTION.rst
  project_tag_hierarchy/static/description/icon.png
  project_tag_hierarchy/static/description/index.html
  project_tag_hierarchy/tests/__init__.py
  project_tag_hierarchy/tests/test_project_tag_hierarchy.py
  project_tag_hierarchy/views/project_tags_views.xml
  setup/project_tag_hierarchy/odoo/addons/project_tag_hierarchy
  setup/project_tag_hierarchy/setup.py
Labels: approved, bot is merging ⏳

#1349 [16.0][ADD] project_tag_security: New module
  project_tag_security/README.rst
  project_tag_security/__init__.py
  project_tag_security/__manifest__.py
  project_tag_security/i18n/es.po
  project_tag_security/i18n/project_tag_security.pot
  project_tag_security/models/__init__.py
  project_tag_security/models/project_tags.py
  project_tag_security/readme/CONTRIBUTORS.rst
  project_tag_security/readme/DESCRIPTION.rst
  project_tag_security/readme/USAGE.rst
  project_tag_security/static/description/icon.png
  project_tag_security/static/description/index.html
  project_tag_security/tests/__init__.py
  project_tag_security/tests/test_project_tag_security.py
  project_tag_security/views/project_project_views.xml
  project_tag_security/views/project_tags_views.xml
  project_tag_security/views/project_task_views.xml
  setup/project_tag_security/odoo/addons/project_tag_security
  setup/project_tag_security/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1353 17.0 mig project_purchase_link
  project_purchase_link/README.rst
  project_purchase_link/__init__.py
  project_purchase_link/__manifest__.py
  project_purchase_link/i18n/es.po
  project_purchase_link/i18n/it.po
  project_purchase_link/i18n/project_purchase_link.pot
  project_purchase_link/i18n/pt_BR.po
  project_purchase_link/i18n/sl.po
  project_purchase_link/models/__init__.py
  project_purchase_link/models/project_project.py
  project_purchase_link/pyproject.toml
  project_purchase_link/readme/CONTRIBUTORS.md
  project_purchase_link/readme/DESCRIPTION.md
  project_purchase_link/readme/USAGE.md
  project_purchase_link/static/description/icon.png
  project_purchase_link/static/description/index.html
  project_purchase_link/tests/__init__.py
  project_purchase_link/tests/test_project_purchase_link.py
  project_purchase_link/views/project_project_view.xml
Labels: bot is merging ⏳

#1327 [16.0][ADD] task_project_status
  setup/task_project_status/odoo/addons/task_project_status
  setup/task_project_status/setup.py
  task_project_status/README.rst
  task_project_status/__init__.py
  task_project_status/__manifest__.py
  task_project_status/i18n/es.po
  task_project_status/models/__init__.py
  task_project_status/models/project.py
  task_project_status/readme/CONTRIBUTORS.rst
  task_project_status/readme/DESCRIPTION.rst
  task_project_status/static/description/icon.png
  task_project_status/static/description/index.html
  task_project_status/tests/__init__.py
  task_project_status/tests/task_project_status.py
  task_project_status/tests/test_task_project_status.py
  task_project_status/views/project_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1303 [16.0][FIX] project_sequence: Force generate sequence_code when creating project from list view
  project_sequence/models/project_project.py
  project_sequence/tests/test_project_sequence.py
Labels: enhancement, approved, bot is merging ⏳

#1354 [17.0][MIG] project_timeline: Migration to version 17.0
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_project_demo.xml
  project_timeline/demo/project_task_demo.xml
  project_timeline/i18n/ar.po
  project_timeline/i18n/ca.po
  project_timeline/i18n/de.po
  project_timeline/i18n/el.po
  project_timeline/i18n/es.po
  project_timeline/i18n/es_AR.po
  project_timeline/i18n/es_CR.po
  project_timeline/i18n/es_MX.po
  project_timeline/i18n/es_VE.po
  project_timeline/i18n/fi.po
  project_timeline/i18n/fr.po
  project_timeline/i18n/fr_FR.po
  project_timeline/i18n/gl.po
  project_timeline/i18n/he.po
  project_timeline/i18n/hr.po
  project_timeline/i18n/hr_HR.po
  project_timeline/i18n/hu.po
  project_timeline/i18n/it.po
  project_timeline/i18n/ja.po
  project_timeline/i18n/lt.po
  project_timeline/i18n/lv.po
  project_timeline/i18n/mk.po
  project_timeline/i18n/mn.po
  project_timeline/i18n/nl.po
  project_timeline/i18n/nl_NL.po
  project_timeline/i18n/pl.po
  project_timeline/i18n/project_timeline.pot
  project_timeline/i18n/pt.po
  project_timeline/i18n/pt_BR.po
  project_timeline/i18n/pt_PT.po
  project_timeline/i18n/ro.po
  project_timeline/i18n/sl.po
  project_timeline/i18n/sv.po
  project_timeline/i18n/tr.po
  project_timeline/i18n/uk.po
  project_timeline/i18n/zh_CN.po
  project_timeline/models/__init__.py
  project_timeline/models/project_task.py
  project_timeline/pyproject.toml
  project_timeline/readme/CONTRIBUTORS.md
  project_timeline/readme/DESCRIPTION.md
  project_timeline/readme/USAGE.md
  project_timeline/static/description/icon.png
  project_timeline/static/description/icon.svg
  project_timeline/static/description/index.html
  project_timeline/static/src/scss/project_timeline.scss
  project_timeline/tests/__init__.py
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_project_view.xml
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1356 [14.0][FIX] project_timeline: add fields in report.project.task.user to prevent errors on timeline view
  project_timeline/__init__.py
  project_timeline/report/__init__.py
  project_timeline/report/project_report.py
Labels: approved, bot is merging ⏳

#1358 [16.0][FIX] project_timeline: add fields in report.project.task.user to prevent errors on timeline view
  project_timeline/__init__.py
  project_timeline/report/__init__.py
  project_timeline/report/project_report.py
Labels: approved, bot is merging ⏳

#1357 [15.0][FIX] project_timeline: add fields in report.project.task.user to prevent errors on timeline view
  project_timeline/__init__.py
  project_timeline/report/__init__.py
  project_timeline/report/project_report.py
Labels: approved, bot is merging ⏳

#1359 [17.0][FIX] project_timeline: add fields in report.project.task.user to prevent errors on timeline view
  project_timeline/__init__.py
  project_timeline/report/__init__.py
  project_timeline/report/project_report.py
  project_timeline/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1360 [16.0][MIG] project_task_description_template: Migration to 16.0
  project_task_description_template/README.rst
  project_task_description_template/__init__.py
  project_task_description_template/__manifest__.py
  project_task_description_template/i18n/es.po
  project_task_description_template/i18n/es_MX.po
  project_task_description_template/i18n/it.po
  project_task_description_template/i18n/project_task_description_template.pot
  project_task_description_template/models/__init__.py
  project_task_description_template/models/project_task.py
  project_task_description_template/models/project_task_description_template.py
  project_task_description_template/readme/CONTRIBUTORS.rst
  project_task_description_template/readme/DESCRIPTION.rst
  project_task_description_template/readme/USAGE.rst
  project_task_description_template/security/ir.model.access.csv
  project_task_description_template/security/ir_rule_data.xml
  project_task_description_template/static/description/icon.png
  project_task_description_template/static/description/index.html
  project_task_description_template/views/project_task_description_template_view.xml
  project_task_description_template/views/project_task_view.xml
  setup/project_task_description_template/odoo/addons/project_task_description_template
  setup/project_task_description_template/setup.py
Labels: approved, bot is merging ⏳
