Repository OCA/project, pull requests merged in 2024-02, with the labels that each got.

#1228 [16.0][MIG] project_task_stage_state: Migration to 16.0
  project_task_stage_state/README.rst
  project_task_stage_state/__init__.py
  project_task_stage_state/__manifest__.py
  project_task_stage_state/i18n/ar.po
  project_task_stage_state/i18n/bg.po
  project_task_stage_state/i18n/ca.po
  project_task_stage_state/i18n/de.po
  project_task_stage_state/i18n/el.po
  project_task_stage_state/i18n/el_GR.po
  project_task_stage_state/i18n/es.po
  project_task_stage_state/i18n/es_AR.po
  project_task_stage_state/i18n/es_CR.po
  project_task_stage_state/i18n/es_MX.po
  project_task_stage_state/i18n/es_PA.po
  project_task_stage_state/i18n/es_VE.po
  project_task_stage_state/i18n/fi.po
  project_task_stage_state/i18n/fr.po
  project_task_stage_state/i18n/fr_FR.po
  project_task_stage_state/i18n/gl.po
  project_task_stage_state/i18n/hr.po
  project_task_stage_state/i18n/hr_HR.po
  project_task_stage_state/i18n/hu.po
  project_task_stage_state/i18n/it.po
  project_task_stage_state/i18n/ja.po
  project_task_stage_state/i18n/lt.po
  project_task_stage_state/i18n/lv.po
  project_task_stage_state/i18n/mk.po
  project_task_stage_state/i18n/mn.po
  project_task_stage_state/i18n/nb.po
  project_task_stage_state/i18n/nb_NO.po
  project_task_stage_state/i18n/nl.po
  project_task_stage_state/i18n/nl_NL.po
  project_task_stage_state/i18n/pl.po
  project_task_stage_state/i18n/project_stage_state.pot
  project_task_stage_state/i18n/project_task_stage_state.pot
  project_task_stage_state/i18n/pt.po
  project_task_stage_state/i18n/pt_BR.po
  project_task_stage_state/i18n/pt_PT.po
  project_task_stage_state/i18n/ro.po
  project_task_stage_state/i18n/ru.po
  project_task_stage_state/i18n/sk.po
  project_task_stage_state/i18n/sl.po
  project_task_stage_state/i18n/sv.po
  project_task_stage_state/i18n/tr.po
  project_task_stage_state/i18n/uk.po
  project_task_stage_state/i18n/zh_CN.po
  project_task_stage_state/models/__init__.py
  project_task_stage_state/models/project_task.py
  project_task_stage_state/models/project_task_type.py
  project_task_stage_state/readme/CONFIGURE.rst
  project_task_stage_state/readme/CONTRIBUTORS.rst
  project_task_stage_state/readme/DESCRIPTION.rst
  project_task_stage_state/readme/USAGE.rst
  project_task_stage_state/security/ir.model.access.csv
  project_task_stage_state/static/description/icon.png
  project_task_stage_state/static/description/index.html
  project_task_stage_state/views/project_view.xml
  setup/project_task_stage_state/odoo/addons/project_task_stage_state
  setup/project_task_stage_state/setup.py
Labels: approved, bot is merging ⏳

#1189 [16.0][ADD] project_task_pull_request_state
  project_task_pull_request_state/README.rst
  project_task_pull_request_state/__init__.py
  project_task_pull_request_state/__manifest__.py
  project_task_pull_request_state/models/__init__.py
  project_task_pull_request_state/models/project_project.py
  project_task_pull_request_state/models/project_task.py
  project_task_pull_request_state/models/res_config_settings.py
  project_task_pull_request_state/readme/CONFIGURE.rst
  project_task_pull_request_state/readme/CONTEXT.rst
  project_task_pull_request_state/readme/CONTRIBUTORS.rst
  project_task_pull_request_state/readme/DESCRIPTION.rst
  project_task_pull_request_state/static/description/icon.png
  project_task_pull_request_state/static/description/index.html
  project_task_pull_request_state/tests/__init__.py
  project_task_pull_request_state/tests/test_project_task_pull_request_state.py
  project_task_pull_request_state/views/project_project_view.xml
  project_task_pull_request_state/views/project_task_view.xml
  project_task_pull_request_state/views/res_config_settings_view.xml
  setup/project_task_pull_request_state/odoo/addons/project_task_pull_request_state
  setup/project_task_pull_request_state/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1234 [14.0][FIX] project_forecast_line: context in settings action
  project_forecast_line/__manifest__.py
  project_forecast_line/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#1237 [15.0][ADD] project_task_note: Add notes in project task
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/readme/CONTEXT.rst
  project_task_note/readme/CONTRIBUTORS.rst
  project_task_note/readme/DESCRIPTION.rst
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
  setup/project_task_note/odoo/addons/project_task_note
  setup/project_task_note/setup.py
Labels: approved, bot is merging ⏳

#1240 [16.0][MIG] project_task_note: Migration to 16.0
  project_task_note/README.rst
  project_task_note/__init__.py
  project_task_note/__manifest__.py
  project_task_note/i18n/es.po
  project_task_note/i18n/project_task_note.pot
  project_task_note/models/__init__.py
  project_task_note/models/project_task.py
  project_task_note/readme/CONTEXT.rst
  project_task_note/readme/CONTRIBUTORS.rst
  project_task_note/readme/DESCRIPTION.rst
  project_task_note/readme/USAGE.srt
  project_task_note/static/description/icon.png
  project_task_note/static/description/index.html
  project_task_note/views/project_task_views.xml
  setup/project_task_note/odoo/addons/project_task_note
  setup/project_task_note/setup.py
Labels: approved, bot is merging ⏳

#1233 [17.0][MIG] project_sequence: migration to 17.0
  project_sequence/README.rst
  project_sequence/__init__.py
  project_sequence/__manifest__.py
  project_sequence/data/ir_sequence.xml
  project_sequence/i18n/de.po
  project_sequence/i18n/es.po
  project_sequence/i18n/it.po
  project_sequence/i18n/nl.po
  project_sequence/i18n/project_sequence.pot
  project_sequence/models/__init__.py
  project_sequence/models/project_project.py
  project_sequence/pyproject.toml
  project_sequence/readme/CONFIGURE.md
  project_sequence/readme/CONTRIBUTORS.md
  project_sequence/readme/CREDITS.md
  project_sequence/readme/DESCRIPTION.md
  project_sequence/readme/USAGE.md
  project_sequence/static/description/icon.png
  project_sequence/static/description/index.html
  project_sequence/tests/__init__.py
  project_sequence/tests/test_project_sequence.py
  project_sequence/views/project_project.xml
  project_sequence/wizards/__init__.py
  project_sequence/wizards/res_config_settings.py
  project_sequence/wizards/res_config_settings_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
