Repository OCA/project, pull requests merged in 2025-02, with the labels that each got.

#1429 [17.0][IMP] project_timeline: Move planning fields out of notebook page
  project_timeline/views/project_task_view.xml
Labels: bot is merging ⏳

#1383 [18.0] [MIG] project_task_default_stage: Migration to 18.0
  project_task_default_stage/README.rst
  project_task_default_stage/__init__.py
  project_task_default_stage/__manifest__.py
  project_task_default_stage/data/project_data.xml
  project_task_default_stage/i18n/bg.po
  project_task_default_stage/i18n/ca.po
  project_task_default_stage/i18n/cs_CZ.po
  project_task_default_stage/i18n/de.po
  project_task_default_stage/i18n/el_GR.po
  project_task_default_stage/i18n/es.po
  project_task_default_stage/i18n/es_AR.po
  project_task_default_stage/i18n/es_CO.po
  project_task_default_stage/i18n/es_MX.po
  project_task_default_stage/i18n/fi.po
  project_task_default_stage/i18n/fr.po
  project_task_default_stage/i18n/fr_FR.po
  project_task_default_stage/i18n/gl.po
  project_task_default_stage/i18n/hr.po
  project_task_default_stage/i18n/hu.po
  project_task_default_stage/i18n/it.po
  project_task_default_stage/i18n/nb.po
  project_task_default_stage/i18n/nb_NO.po
  project_task_default_stage/i18n/nl.po
  project_task_default_stage/i18n/nl_NL.po
  project_task_default_stage/i18n/pl.po
  project_task_default_stage/i18n/project_task_default_stage.pot
  project_task_default_stage/i18n/pt.po
  project_task_default_stage/i18n/pt_BR.po
  project_task_default_stage/i18n/pt_PT.po
  project_task_default_stage/i18n/ru.po
  project_task_default_stage/i18n/sk.po
  project_task_default_stage/i18n/sl.po
  project_task_default_stage/i18n/tr.po
  project_task_default_stage/i18n/zh_CN.po
  project_task_default_stage/models/__init__.py
  project_task_default_stage/models/project.py
  project_task_default_stage/models/project_task_type.py
  project_task_default_stage/pyproject.toml
  project_task_default_stage/readme/CONFIGURE.md
  project_task_default_stage/readme/CONTRIBUTORS.md
  project_task_default_stage/readme/DESCRIPTION.md
  project_task_default_stage/static/description/icon.png
  project_task_default_stage/static/description/index.html
  project_task_default_stage/tests/__init__.py
  project_task_default_stage/tests/test_project_task_default_stage.py
  project_task_default_stage/views/project_view.xml
Labels: bot is merging ⏳

#1378 [18.0][MIG] project_role
  project_role/README.rst
  project_role/__init__.py
  project_role/__manifest__.py
  project_role/i18n/de.po
  project_role/i18n/es.po
  project_role/i18n/es_AR.po
  project_role/i18n/es_PA.po
  project_role/i18n/fr.po
  project_role/i18n/hr.po
  project_role/i18n/it.po
  project_role/i18n/nl.po
  project_role/i18n/project_role.pot
  project_role/i18n/sl.po
  project_role/models/__init__.py
  project_role/models/project_assignment.py
  project_role/models/project_project.py
  project_role/models/project_role.py
  project_role/models/res_company.py
  project_role/models/res_config_settings.py
  project_role/pyproject.toml
  project_role/readme/CONFIGURE.md
  project_role/readme/CONTRIBUTORS.md
  project_role/readme/DESCRIPTION.md
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/icon.png
  project_role/static/description/index.html
  project_role/tests/__init__.py
  project_role/tests/test_project_role.py
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#1204 [17.0][MIG] project_role: Migration to 17.0
  project_role/README.rst
  project_role/__init__.py
  project_role/__manifest__.py
  project_role/i18n/de.po
  project_role/i18n/es.po
  project_role/i18n/es_AR.po
  project_role/i18n/es_PA.po
  project_role/i18n/fr.po
  project_role/i18n/hr.po
  project_role/i18n/it.po
  project_role/i18n/nl.po
  project_role/i18n/project_role.pot
  project_role/i18n/sl.po
  project_role/models/__init__.py
  project_role/models/project_assignment.py
  project_role/models/project_project.py
  project_role/models/project_role.py
  project_role/models/res_company.py
  project_role/models/res_config_settings.py
  project_role/pyproject.toml
  project_role/readme/CONFIGURE.md
  project_role/readme/CONTRIBUTORS.md
  project_role/readme/DESCRIPTION.md
  project_role/security/ir.model.access.csv
  project_role/security/project_role.xml
  project_role/static/description/icon.png
  project_role/static/description/index.html
  project_role/tests/__init__.py
  project_role/tests/test_project_role.py
  project_role/views/project_assignment.xml
  project_role/views/project_project.xml
  project_role/views/project_role.xml
  project_role/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1381 [16.0][MIG] project_risk: Migration to 16.0
  project_risk/README.rst
  project_risk/__init__.py
  project_risk/__manifest__.py
  project_risk/data/project_risk_category_data.xml
  project_risk/data/project_risk_response_category_data.xml
  project_risk/i18n/es.po
  project_risk/i18n/it.po
  project_risk/i18n/project_risk.pot
  project_risk/i18n/sl.po
  project_risk/migration_version.rst
  project_risk/models/__init__.py
  project_risk/models/project_project.py
  project_risk/models/project_risk.py
  project_risk/models/project_risk_category.py
  project_risk/models/project_risk_response.py
  project_risk/models/project_risk_response_category.py
  project_risk/readme/CONFIGURE.rst
  project_risk/readme/CONTRIBUTORS.rst
  project_risk/readme/DESCRIPTION.rst
  project_risk/readme/ROADMAP.rst
  project_risk/readme/USAGE.rst
  project_risk/security/ir_model_access.xml
  project_risk/static/description/icon.png
  project_risk/static/description/index.html
  project_risk/static/description/matrix.png
  project_risk/tests/__init__.py
  project_risk/tests/test_project_risk.py
  project_risk/views/menuitems.xml
  project_risk/views/project_project_view.xml
  project_risk/views/project_risk_category_view.xml
  project_risk/views/project_risk_response_category_view.xml
  project_risk/views/project_risk_view.xml
  setup/project_risk/odoo/addons/project_risk
  setup/project_risk/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1420 [ADD] project_group
  project_group/README.rst
  project_group/__init__.py
  project_group/__manifest__.py
  project_group/models/__init__.py
  project_group/models/project_project.py
  project_group/pyproject.toml
  project_group/readme/CONTRIBUTORS.md
  project_group/readme/DESCRIPTION.md
  project_group/readme/USAGE.md
  project_group/security/project_project.xml
  project_group/static/description/icon.png
  project_group/static/description/index.html
  project_group/views/project_project.xml
Labels: approved, ready to merge, bot is merging ⏳

#1432 [16.0][ADD] project_version: New module project_version
  project_version/README.rst
  project_version/__init__.py
  project_version/__manifest__.py
  project_version/models/__init__.py
  project_version/models/project_project.py
  project_version/models/project_task.py
  project_version/models/project_version.py
  project_version/readme/CONTRIBUTORS.md
  project_version/readme/DESCRIPTION.md
  project_version/readme/USAGE.md
  project_version/security/ir.model.access.csv
  project_version/static/description/icon.png
  project_version/static/description/icon.svg
  project_version/static/description/index.html
  project_version/views/project_project_views.xml
  project_version/views/project_task_views.xml
  project_version/views/project_version_views.xml
  setup/project_version/odoo/addons/project_version
  setup/project_version/setup.py
Labels: approved, ready to merge, bot is merging ⏳
