Repository OCA/project, pull requests merged in 2025-01, with the labels that each got.

#1393 [FIX] [16.0] project_administrator_restricted_visibility: Restricted Project Manager always can manage its own projects
  project_administrator_restricted_visibility/README.rst
  project_administrator_restricted_visibility/readme/CONTRIBUTORS.rst
  project_administrator_restricted_visibility/security/project_security.xml
  project_administrator_restricted_visibility/static/description/index.html
  project_administrator_restricted_visibility/tests/test_project_administrator_restricted_visibility.py
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1413 [17.0][MIG] project_timeline_hr_timesheet: Migration to version 17.0
  project_timeline_hr_timesheet/README.rst
  project_timeline_hr_timesheet/__init__.py
  project_timeline_hr_timesheet/__manifest__.py
  project_timeline_hr_timesheet/i18n/de.po
  project_timeline_hr_timesheet/i18n/es.po
  project_timeline_hr_timesheet/i18n/fr.po
  project_timeline_hr_timesheet/i18n/he.po
  project_timeline_hr_timesheet/i18n/it.po
  project_timeline_hr_timesheet/i18n/project_timeline_hr_timesheet.pot
  project_timeline_hr_timesheet/pyproject.toml
  project_timeline_hr_timesheet/readme/CONTRIBUTORS.md
  project_timeline_hr_timesheet/readme/DESCRIPTION.md
  project_timeline_hr_timesheet/static/description/icon.png
  project_timeline_hr_timesheet/static/description/index.html
  project_timeline_hr_timesheet/static/src/scss/project_timeline_hr_timesheet.scss
  project_timeline_hr_timesheet/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1406 [18.0][MIG] project_type: Migration to 18.0
  project_type/README.rst
  project_type/__init__.py
  project_type/__manifest__.py
  project_type/i18n/ca.po
  project_type/i18n/de.po
  project_type/i18n/es.po
  project_type/i18n/es_AR.po
  project_type/i18n/fr.po
  project_type/i18n/fr_FR.po
  project_type/i18n/it.po
  project_type/i18n/nl.po
  project_type/i18n/project_type.pot
  project_type/i18n/pt_BR.po
  project_type/models/__init__.py
  project_type/models/project_project.py
  project_type/models/project_task.py
  project_type/models/project_type.py
  project_type/pyproject.toml
  project_type/readme/CONTRIBUTORS.md
  project_type/readme/DESCRIPTION.md
  project_type/readme/USAGE.md
  project_type/security/ir.model.access.csv
  project_type/static/description/icon.png
  project_type/static/description/index.html
  project_type/tests/__init__.py
  project_type/tests/test_project_type.py
  project_type/views/project_project_views.xml
  project_type/views/project_task_views.xml
  project_type/views/project_type_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1418 [FIX] sale_project_copy_tasks: find the appropriate `project_id` fiel…
  sale_project_copy_tasks/views/sale_order_views.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1421 [16.0][FIX] project_stock: Do not allow to edit specific fields (product, uom, qty) in confirmed moves.
  project_stock/views/stock_move_view.xml
Labels: approved, bot is merging ⏳

#1422 [14.0][IMP] project_forecast_line: sudo calls updating forecast lines
  project_forecast_line/models/project_task.py
Labels: bot is merging ⏳

#1388 [17.0][ADD] sale_project_reimbursement_cost: New module to display provisions and reimbur…
  sale_project_reimbursement_cost/README.rst
  sale_project_reimbursement_cost/__init__.py
  sale_project_reimbursement_cost/__manifest__.py
  sale_project_reimbursement_cost/demo/product_demo.xml
  sale_project_reimbursement_cost/i18n/es.po
  sale_project_reimbursement_cost/i18n/sale_project_reimbursement_cost.pot
  sale_project_reimbursement_cost/models/__init__.py
  sale_project_reimbursement_cost/models/account_move_line.py
  sale_project_reimbursement_cost/models/product_template.py
  sale_project_reimbursement_cost/models/project_project.py
  sale_project_reimbursement_cost/pyproject.toml
  sale_project_reimbursement_cost/readme/CONFIGURE.md
  sale_project_reimbursement_cost/readme/CONTEXT.md
  sale_project_reimbursement_cost/readme/CONTRIBUTORS.md
  sale_project_reimbursement_cost/readme/DESCRIPTION.md
  sale_project_reimbursement_cost/readme/USAGE.md
  sale_project_reimbursement_cost/static/description/icon.png
  sale_project_reimbursement_cost/static/description/index.html
  sale_project_reimbursement_cost/static/src/components/project_right_side_panel/project_right_side_panel.esm.js
  sale_project_reimbursement_cost/static/src/components/project_right_side_panel/project_right_side_panel.xml
  sale_project_reimbursement_cost/tests/__init__.py
  sale_project_reimbursement_cost/tests/test_reimbursement_cost.py
  sale_project_reimbursement_cost/views/product_template_views.xml
  sale_project_reimbursement_cost/views/sale_order_line_views.xml
Labels: bot is merging ⏳
