Repository OCA/project, pull requests merged in 2025-05, with the labels that each got.

#1489 [18.0][MIG] project_task_parent_completion_blocking: Migration to version 18.0
  project_task_parent_completion_blocking/README.rst
  project_task_parent_completion_blocking/__init__.py
  project_task_parent_completion_blocking/__manifest__.py
  project_task_parent_completion_blocking/i18n/es.po
  project_task_parent_completion_blocking/i18n/it.po
  project_task_parent_completion_blocking/i18n/project_task_parent_completion_blocking.pot
  project_task_parent_completion_blocking/models/__init__.py
  project_task_parent_completion_blocking/models/project_task.py
  project_task_parent_completion_blocking/pyproject.toml
  project_task_parent_completion_blocking/readme/CONTRIBUTORS.md
  project_task_parent_completion_blocking/readme/DESCRIPTION.md
  project_task_parent_completion_blocking/static/description/icon.png
  project_task_parent_completion_blocking/static/description/index.html
  project_task_parent_completion_blocking/tests/__init__.py
  project_task_parent_completion_blocking/tests/test_project_task_parent_completion_blocking.py
Labels: approved, bot is merging ⏳

#1491 [18.0][MIG] project_task_parent_due_auto: Migration to version 18.0
  project_task_parent_due_auto/README.rst
  project_task_parent_due_auto/__init__.py
  project_task_parent_due_auto/__manifest__.py
  project_task_parent_due_auto/i18n/it.po
  project_task_parent_due_auto/i18n/project_task_parent_due_auto.pot
  project_task_parent_due_auto/models/__init__.py
  project_task_parent_due_auto/models/project_task.py
  project_task_parent_due_auto/pyproject.toml
  project_task_parent_due_auto/readme/CONTRIBUTORS.md
  project_task_parent_due_auto/readme/DESCRIPTION.md
  project_task_parent_due_auto/static/description/icon.png
  project_task_parent_due_auto/static/description/index.html
  project_task_parent_due_auto/tests/__init__.py
  project_task_parent_due_auto/tests/test_parent_due_auto.py
Labels: approved, bot is merging ⏳

#1398 [18.0][MIG] project_department: Migration to 18.0
  project_department/README.rst
  project_department/__init__.py
  project_department/__manifest__.py
  project_department/i18n/ar.po
  project_department/i18n/ca.po
  project_department/i18n/de.po
  project_department/i18n/el.po
  project_department/i18n/es.po
  project_department/i18n/es_CR.po
  project_department/i18n/es_MX.po
  project_department/i18n/es_VE.po
  project_department/i18n/fi.po
  project_department/i18n/fr.po
  project_department/i18n/gl.po
  project_department/i18n/hr.po
  project_department/i18n/hr_HR.po
  project_department/i18n/hu.po
  project_department/i18n/it.po
  project_department/i18n/ja.po
  project_department/i18n/lt.po
  project_department/i18n/lv.po
  project_department/i18n/mk.po
  project_department/i18n/mn.po
  project_department/i18n/nl.po
  project_department/i18n/nl_NL.po
  project_department/i18n/pl.po
  project_department/i18n/project_department.pot
  project_department/i18n/pt.po
  project_department/i18n/pt_BR.po
  project_department/i18n/pt_PT.po
  project_department/i18n/ro.po
  project_department/i18n/sl.po
  project_department/i18n/sv.po
  project_department/i18n/tr.po
  project_department/i18n/uk.po
  project_department/i18n/zh_CN.po
  project_department/models/__init__.py
  project_department/models/project.py
  project_department/pyproject.toml
  project_department/readme/CONTRIBUTORS.md
  project_department/readme/DESCRIPTION.md
  project_department/static/description/icon.png
  project_department/static/description/index.html
  project_department/views/project.xml
Labels: approved, ready to merge, bot is merging ⏳

#1452 [16.0][ADD] project_milestone_status: New module project_milestone_st…
  project_milestone_status/README.rst
  project_milestone_status/__init__.py
  project_milestone_status/__manifest__.py
  project_milestone_status/i18n/es.po
  project_milestone_status/models/__init__.py
  project_milestone_status/models/project.py
  project_milestone_status/models/project_milestone.py
  project_milestone_status/readme/CONTRIBUTORS.md
  project_milestone_status/readme/DESCRIPTION.md
  project_milestone_status/readme/USAGE.md
  project_milestone_status/static/description/icon.png
  project_milestone_status/static/description/icon.svg
  project_milestone_status/static/description/index.html
  project_milestone_status/tests/__init__.py
  project_milestone_status/tests/common.py
  project_milestone_status/tests/test_project_milestone_status.py
  project_milestone_status/tests/test_project_status.py
  project_milestone_status/views/project_milestone_views.xml
  project_milestone_status/views/project_views.xml
  setup/project_milestone_status/odoo/addons/project_milestone_status
  setup/project_milestone_status/setup.py
Labels: approved, bot is merging ⏳

#1495 [16.0][FIX] project_stock: Generate analytical lines in both use cases (tasks and pickings)
  project_stock/models/project_task.py
  project_stock/models/stock_move.py
  project_stock/tests/test_project_stock.py
Labels: bot is merging ⏳

#1500 [18.0][FIX] project_task_stock: Generate analytical lines in both use cases (tasks and pickings)
  project_task_stock/models/project_task.py
  project_task_stock/models/stock_move.py
  project_task_stock/tests/test_project_task_stock.py
Labels: bot is merging ⏳

#1472 [17.0][MIG] project_task_name_with_id: Migration to 17.0
  project_task_name_with_id/README.rst
  project_task_name_with_id/__init__.py
  project_task_name_with_id/__manifest__.py
  project_task_name_with_id/i18n/it.po
  project_task_name_with_id/i18n/project_task_name_with_id.pot
  project_task_name_with_id/models/__init__.py
  project_task_name_with_id/models/project_task.py
  project_task_name_with_id/pyproject.toml
  project_task_name_with_id/readme/DESCRIPTION.md
  project_task_name_with_id/readme/USAGE.md
  project_task_name_with_id/static/description/icon.png
  project_task_name_with_id/static/description/index.html
  project_task_name_with_id/tests/__init__.py
  project_task_name_with_id/tests/test_project_task_id.py
  project_task_name_with_id/views/project_task_views.xml
Labels: approved, bot is merging ⏳

#1478 [18.0][MIG] project_timeline: Migration to version 18.0
  project_timeline/README.rst
  project_timeline/__init__.py
  project_timeline/__manifest__.py
  project_timeline/demo/project_project_demo.xml
  project_timeline/demo/project_task_demo.xml
  project_timeline/i18n/ar.po
  project_timeline/i18n/ca.po
  project_timeline/i18n/de.po
  project_timeline/i18n/el.po
  project_timeline/i18n/es.po
  project_timeline/i18n/es_AR.po
  project_timeline/i18n/es_CR.po
  project_timeline/i18n/es_MX.po
  project_timeline/i18n/es_VE.po
  project_timeline/i18n/fi.po
  project_timeline/i18n/fr.po
  project_timeline/i18n/fr_FR.po
  project_timeline/i18n/gl.po
  project_timeline/i18n/he.po
  project_timeline/i18n/hr.po
  project_timeline/i18n/hr_HR.po
  project_timeline/i18n/hu.po
  project_timeline/i18n/it.po
  project_timeline/i18n/ja.po
  project_timeline/i18n/lt.po
  project_timeline/i18n/lv.po
  project_timeline/i18n/mk.po
  project_timeline/i18n/mn.po
  project_timeline/i18n/nl.po
  project_timeline/i18n/nl_NL.po
  project_timeline/i18n/pl.po
  project_timeline/i18n/project_timeline.pot
  project_timeline/i18n/pt.po
  project_timeline/i18n/pt_BR.po
  project_timeline/i18n/pt_PT.po
  project_timeline/i18n/ro.po
  project_timeline/i18n/sl.po
  project_timeline/i18n/sv.po
  project_timeline/i18n/tr.po
  project_timeline/i18n/uk.po
  project_timeline/i18n/zh_CN.po
  project_timeline/models/__init__.py
  project_timeline/models/project_task.py
  project_timeline/pyproject.toml
  project_timeline/readme/CONTRIBUTORS.md
  project_timeline/readme/DESCRIPTION.md
  project_timeline/readme/USAGE.md
  project_timeline/report/__init__.py
  project_timeline/report/project_report.py
  project_timeline/static/description/icon.png
  project_timeline/static/description/icon.svg
  project_timeline/static/description/index.html
  project_timeline/static/src/scss/project_timeline.scss
  project_timeline/tests/__init__.py
  project_timeline/tests/test_project_timeline.py
  project_timeline/views/project_project_view.xml
  project_timeline/views/project_task_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1501 [17.0][MIG] project_milestone_status: Migration to 17.0
  project_milestone_status/README.rst
  project_milestone_status/__init__.py
  project_milestone_status/__manifest__.py
  project_milestone_status/i18n/es.po
  project_milestone_status/i18n/it.po
  project_milestone_status/i18n/project_milestone_status.pot
  project_milestone_status/models/__init__.py
  project_milestone_status/models/project.py
  project_milestone_status/models/project_milestone.py
  project_milestone_status/pyproject.toml
  project_milestone_status/readme/CONTRIBUTORS.md
  project_milestone_status/readme/DESCRIPTION.md
  project_milestone_status/readme/USAGE.md
  project_milestone_status/static/description/icon.png
  project_milestone_status/static/description/icon.svg
  project_milestone_status/static/description/index.html
  project_milestone_status/tests/__init__.py
  project_milestone_status/tests/common.py
  project_milestone_status/tests/test_project_milestone_status.py
  project_milestone_status/tests/test_project_status.py
  project_milestone_status/views/project_milestone_views.xml
  project_milestone_status/views/project_views.xml
Labels: approved, bot is merging ⏳

#1505 [FIX] project_task_parent_due_auto: completing subtask now updates parent deadline
  project_task_parent_due_auto/models/project_task.py
  project_task_parent_due_auto/tests/test_parent_due_auto.py
Labels: approved, bot is merging ⏳

#1499 [17.0][MIG] project_task_code
  project_task_code/README.rst
  project_task_code/__init__.py
  project_task_code/__manifest__.py
  project_task_code/data/task_sequence.xml
  project_task_code/hooks.py
  project_task_code/i18n/ar.po
  project_task_code/i18n/bg.po
  project_task_code/i18n/ca.po
  project_task_code/i18n/de.po
  project_task_code/i18n/el.po
  project_task_code/i18n/es.po
  project_task_code/i18n/es_AR.po
  project_task_code/i18n/es_CR.po
  project_task_code/i18n/es_MX.po
  project_task_code/i18n/es_VE.po
  project_task_code/i18n/fi.po
  project_task_code/i18n/fr.po
  project_task_code/i18n/fr_FR.po
  project_task_code/i18n/gl.po
  project_task_code/i18n/hr.po
  project_task_code/i18n/hr_HR.po
  project_task_code/i18n/hu.po
  project_task_code/i18n/it.po
  project_task_code/i18n/ja.po
  project_task_code/i18n/lt.po
  project_task_code/i18n/lv.po
  project_task_code/i18n/mk.po
  project_task_code/i18n/mn.po
  project_task_code/i18n/nl.po
  project_task_code/i18n/nl_NL.po
  project_task_code/i18n/pl.po
  project_task_code/i18n/project_task_code.pot
  project_task_code/i18n/pt.po
  project_task_code/i18n/pt_BR.po
  project_task_code/i18n/pt_PT.po
  project_task_code/i18n/ro.po
  project_task_code/i18n/sk.po
  project_task_code/i18n/sl.po
  project_task_code/i18n/sv.po
  project_task_code/i18n/tr.po
  project_task_code/i18n/uk.po
  project_task_code/i18n/zh_CN.po
  project_task_code/models/__init__.py
  project_task_code/models/project_task.py
  project_task_code/pyproject.toml
  project_task_code/readme/CONFIGURE.md
  project_task_code/readme/CONTRIBUTORS.md
  project_task_code/readme/DESCRIPTION.md
  project_task_code/readme/USAGE.md
  project_task_code/static/description/icon.png
  project_task_code/static/description/index.html
  project_task_code/tests/__init__.py
  project_task_code/tests/test_project_task_code.py
  project_task_code/views/project_view.xml
Labels: approved, bot is merging ⏳

#1402 [18.0][MIG] project_task_pull_request: Migration to 18.0
  project_task_pull_request/README.rst
  project_task_pull_request/__init__.py
  project_task_pull_request/__manifest__.py
  project_task_pull_request/i18n/ar.po
  project_task_pull_request/i18n/ca.po
  project_task_pull_request/i18n/de.po
  project_task_pull_request/i18n/el.po
  project_task_pull_request/i18n/es.po
  project_task_pull_request/i18n/es_AR.po
  project_task_pull_request/i18n/es_CR.po
  project_task_pull_request/i18n/es_MX.po
  project_task_pull_request/i18n/es_VE.po
  project_task_pull_request/i18n/fi.po
  project_task_pull_request/i18n/fr.po
  project_task_pull_request/i18n/gl.po
  project_task_pull_request/i18n/hr.po
  project_task_pull_request/i18n/hr_HR.po
  project_task_pull_request/i18n/hu.po
  project_task_pull_request/i18n/it.po
  project_task_pull_request/i18n/ja.po
  project_task_pull_request/i18n/lt.po
  project_task_pull_request/i18n/lv.po
  project_task_pull_request/i18n/mk.po
  project_task_pull_request/i18n/mn.po
  project_task_pull_request/i18n/nl.po
  project_task_pull_request/i18n/nl_NL.po
  project_task_pull_request/i18n/pl.po
  project_task_pull_request/i18n/project_task_pull_request.pot
  project_task_pull_request/i18n/pt.po
  project_task_pull_request/i18n/pt_BR.po
  project_task_pull_request/i18n/pt_PT.po
  project_task_pull_request/i18n/ro.po
  project_task_pull_request/i18n/sl.po
  project_task_pull_request/i18n/sv.po
  project_task_pull_request/i18n/tr.po
  project_task_pull_request/i18n/uk.po
  project_task_pull_request/i18n/zh_CN.po
  project_task_pull_request/models/__init__.py
  project_task_pull_request/models/project_project.py
  project_task_pull_request/models/project_task.py
  project_task_pull_request/pyproject.toml
  project_task_pull_request/readme/CONTRIBUTORS.md
  project_task_pull_request/readme/DESCRIPTION.md
  project_task_pull_request/readme/USAGE.md
  project_task_pull_request/static/description/icon.png
  project_task_pull_request/static/description/index.html
  project_task_pull_request/tests/__init__.py
  project_task_pull_request/tests/test_project_task_pull_request.py
  project_task_pull_request/views/project_task_pull_request_view.xml
Labels: approved, bot is merging ⏳

#1465 [17.0][IMP] project_key - improvement on the display_name for the projects and tasks
  project_key/models/project_project.py
  project_key/models/project_task.py
Labels: approved, bot is merging ⏳
