Repository OCA/project, pull requests merged in 2025-06, with the labels that each got.

#1503 [17.0][FIX] project_task_name_with_id: avoid overriding _compute_display_name
  project_task_name_with_id/models/project_task.py
Labels: approved, ready to merge, bot is merging ⏳

#1403 [18.0][MIG] project_task_stage_mgmt: Migration to 18.0
  project_task_stage_mgmt/README.rst
  project_task_stage_mgmt/__init__.py
  project_task_stage_mgmt/__manifest__.py
  project_task_stage_mgmt/i18n/it.po
  project_task_stage_mgmt/i18n/project_task_stage_mgmt.pot
  project_task_stage_mgmt/i18n/pt_BR.po
  project_task_stage_mgmt/pyproject.toml
  project_task_stage_mgmt/readme/CONTRIBUTORS.md
  project_task_stage_mgmt/readme/DESCRIPTION.md
  project_task_stage_mgmt/static/description/icon.png
  project_task_stage_mgmt/static/description/index.html
  project_task_stage_mgmt/views/project.xml
Labels: approved, bot is merging ⏳

#1514 [18.0][MIG] project_key: Migration to 18.0
  project_key/README.rst
  project_key/__init__.py
  project_key/__manifest__.py
  project_key/controllers/__init__.py
  project_key/controllers/main.py
  project_key/hooks.py
  project_key/i18n/de.po
  project_key/i18n/es_AR.po
  project_key/i18n/fr.po
  project_key/i18n/it.po
  project_key/i18n/project_key.pot
  project_key/models/__init__.py
  project_key/models/project_project.py
  project_key/models/project_task.py
  project_key/pyproject.toml
  project_key/readme/CONTRIBUTORS.md
  project_key/readme/DESCRIPTION.md
  project_key/readme/USAGE.md
  project_key/static/description/icon.png
  project_key/static/description/index.html
  project_key/tests/__init__.py
  project_key/tests/test_common.py
  project_key/tests/test_controller.py
  project_key/tests/test_project.py
  project_key/tests/test_task.py
  project_key/views/project_key_views.xml
Labels: merged 🎉

#1323 [16.0][MIG]project_task_recurring_activity: migration to `16.0`
  project_task_recurring_activity/README.rst
  project_task_recurring_activity/__init__.py
  project_task_recurring_activity/__manifest__.py
  project_task_recurring_activity/data/recurring_activity.xml
  project_task_recurring_activity/i18n/es.po
  project_task_recurring_activity/i18n/it.po
  project_task_recurring_activity/i18n/project_task_recurring_activity.pot
  project_task_recurring_activity/models/__init__.py
  project_task_recurring_activity/models/project_task.py
  project_task_recurring_activity/models/project_task_recurrence.py
  project_task_recurring_activity/models/recurring_activity.py
  project_task_recurring_activity/readme/CONFIGURE.rst
  project_task_recurring_activity/readme/CONTRIBUTORS.rst
  project_task_recurring_activity/readme/DESCRIPTION.rst
  project_task_recurring_activity/readme/USAGE.rst
  project_task_recurring_activity/security/ir.model.access.csv
  project_task_recurring_activity/static/description/icon.png
  project_task_recurring_activity/static/description/index.html
  project_task_recurring_activity/tests/__init__.py
  project_task_recurring_activity/tests/test_project_recurrence.py
  project_task_recurring_activity/views/project_task.xml
  project_task_recurring_activity/views/recurring_activity.xml
  setup/project_task_recurring_activity/odoo/addons/project_task_recurring_activity
  setup/project_task_recurring_activity/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1482 [16.0][ADD] project_task_add_very_high: implement for portal
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/views/templates.xml
Labels: approved, bot is merging ⏳

#1513 [18.0][MIG] project_version: Migration to 18.0
  project_version/README.rst
  project_version/__init__.py
  project_version/__manifest__.py
  project_version/i18n/es.po
  project_version/i18n/it.po
  project_version/i18n/project_version.pot
  project_version/models/__init__.py
  project_version/models/project_project.py
  project_version/models/project_task.py
  project_version/models/project_version.py
  project_version/pyproject.toml
  project_version/readme/CONTRIBUTORS.md
  project_version/readme/DESCRIPTION.md
  project_version/readme/USAGE.md
  project_version/security/ir.model.access.csv
  project_version/static/description/icon.png
  project_version/static/description/icon.svg
  project_version/static/description/index.html
  project_version/views/project_project_views.xml
  project_version/views/project_task_views.xml
  project_version/views/project_version_views.xml
Labels: approved, bot is merging ⏳

#1494 [18.0] [MIG] project_parent_task_filter: Migration to 18.0
  project_parent_task_filter/README.rst
  project_parent_task_filter/__init__.py
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/i18n/ca.po
  project_parent_task_filter/i18n/de.po
  project_parent_task_filter/i18n/es.po
  project_parent_task_filter/i18n/es_AR.po
  project_parent_task_filter/i18n/es_ES.po
  project_parent_task_filter/i18n/fr.po
  project_parent_task_filter/i18n/fr_FR.po
  project_parent_task_filter/i18n/it.po
  project_parent_task_filter/i18n/nl_NL.po
  project_parent_task_filter/i18n/project_parent_task_filter.pot
  project_parent_task_filter/i18n/pt_BR.po
  project_parent_task_filter/pyproject.toml
  project_parent_task_filter/readme/CONTRIBUTORS.md
  project_parent_task_filter/readme/DESCRIPTION.md
  project_parent_task_filter/readme/ROADMAP.md
  project_parent_task_filter/readme/USAGE.md
  project_parent_task_filter/static/description/icon.png
  project_parent_task_filter/static/description/index.html
  project_parent_task_filter/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#1520 [17.0][MIG] project_hr: Migration to 17.0
  project_hr/README.rst
  project_hr/__init__.py
  project_hr/__manifest__.py
  project_hr/i18n/ca.po
  project_hr/i18n/de.po
  project_hr/i18n/es.po
  project_hr/i18n/hr.po
  project_hr/i18n/it.po
  project_hr/i18n/nl.po
  project_hr/i18n/project_hr.pot
  project_hr/i18n/pt_BR.po
  project_hr/i18n/sl.po
  project_hr/models/__init__.py
  project_hr/models/hr_employee.py
  project_hr/models/project_project.py
  project_hr/models/project_task.py
  project_hr/models/res_users.py
  project_hr/pyproject.toml
  project_hr/readme/CONFIGURE.md
  project_hr/readme/CONTRIBUTORS.md
  project_hr/readme/DESCRIPTION.md
  project_hr/readme/ROADMAP.md
  project_hr/readme/USAGE.md
  project_hr/static/description/icon.png
  project_hr/static/description/index.html
  project_hr/tests/__init__.py
  project_hr/tests/test_project_hr.py
  project_hr/views/project_project_views.xml
  project_hr/views/project_task_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1526 [17.0][IMP] project_hr: restore odoo default user_ids domain
  project_hr/models/project_task.py
Labels: bot is merging ⏳

#1531 [18.0][IMP] project_timesheet_time_control: Test improvements
  project_timesheet_time_control/README.rst
  project_timesheet_time_control/__manifest__.py
  project_timesheet_time_control/static/description/index.html
  project_timesheet_time_control/tests/test_project_timesheet_time_control.py
Labels: bot is merging ⏳

#1533 [17.0][FIX] project_task_related: Don't set current task as parent when creating new related tasks.
  project_task_related/views/project_task_views_related.xml
Labels: approved, bot is merging ⏳
