Repository OCA/project, pull requests merged in 2025-08, with the labels that each got.

#1551 [15.0][FIX] project_template_milestone: fix dependencies
  project_template_milestone/__manifest__.py
  project_template_milestone/static/description/index.html
Labels: approved, bot is merging ⏳

#1536 [18.0] [MIG] project_group: Migration to 18.0
  project_group/README.rst
  project_group/__init__.py
  project_group/__manifest__.py
  project_group/i18n/it.po
  project_group/i18n/project_group.pot
  project_group/models/__init__.py
  project_group/models/project_project.py
  project_group/pyproject.toml
  project_group/readme/CONTRIBUTORS.md
  project_group/readme/DESCRIPTION.md
  project_group/readme/USAGE.md
  project_group/security/project_project.xml
  project_group/static/description/icon.png
  project_group/static/description/index.html
  project_group/tests/__init__.py
  project_group/tests/test_project_visibility.py
  project_group/views/project_project.xml
Labels: approved, ready to merge, bot is merging ⏳

#1557 [17.0][IMP] project_task_note: update maintainer
  project_task_note/README.rst
  project_task_note/__manifest__.py
  project_task_note/static/description/index.html
Labels: bot is merging ⏳
