Repository OCA/project, pull requests merged in 2025-04, with the labels that each got.

#1400 [18.0][MIG] project_task_add_very_high: Migration to 18.0
  project_task_add_very_high/README.rst
  project_task_add_very_high/__init__.py
  project_task_add_very_high/__manifest__.py
  project_task_add_very_high/i18n/ar.po
  project_task_add_very_high/i18n/ca.po
  project_task_add_very_high/i18n/cs_CZ.po
  project_task_add_very_high/i18n/de.po
  project_task_add_very_high/i18n/el.po
  project_task_add_very_high/i18n/es.po
  project_task_add_very_high/i18n/es_AR.po
  project_task_add_very_high/i18n/es_CO.po
  project_task_add_very_high/i18n/es_CR.po
  project_task_add_very_high/i18n/es_MX.po
  project_task_add_very_high/i18n/es_VE.po
  project_task_add_very_high/i18n/fi.po
  project_task_add_very_high/i18n/fr.po
  project_task_add_very_high/i18n/fr_FR.po
  project_task_add_very_high/i18n/gl.po
  project_task_add_very_high/i18n/hr.po
  project_task_add_very_high/i18n/hr_HR.po
  project_task_add_very_high/i18n/hu.po
  project_task_add_very_high/i18n/it.po
  project_task_add_very_high/i18n/ja.po
  project_task_add_very_high/i18n/lt.po
  project_task_add_very_high/i18n/lv.po
  project_task_add_very_high/i18n/mk.po
  project_task_add_very_high/i18n/mn.po
  project_task_add_very_high/i18n/nb.po
  project_task_add_very_high/i18n/nl.po
  project_task_add_very_high/i18n/nl_NL.po
  project_task_add_very_high/i18n/pl.po
  project_task_add_very_high/i18n/project_task_add_very_high.pot
  project_task_add_very_high/i18n/pt.po
  project_task_add_very_high/i18n/pt_BR.po
  project_task_add_very_high/i18n/pt_PT.po
  project_task_add_very_high/i18n/ro.po
  project_task_add_very_high/i18n/sl.po
  project_task_add_very_high/i18n/sv.po
  project_task_add_very_high/i18n/tr.po
  project_task_add_very_high/i18n/uk.po
  project_task_add_very_high/i18n/zh_CN.po
  project_task_add_very_high/models/__init__.py
  project_task_add_very_high/models/project_task.py
  project_task_add_very_high/pyproject.toml
  project_task_add_very_high/readme/CONTRIBUTORS.md
  project_task_add_very_high/readme/DESCRIPTION.md
  project_task_add_very_high/readme/USAGE.md
  project_task_add_very_high/static/description/icon.png
  project_task_add_very_high/static/description/image.png
  project_task_add_very_high/static/description/image2.png
  project_task_add_very_high/static/description/image2_a.png
  project_task_add_very_high/static/description/image_a.png
  project_task_add_very_high/static/description/index.html
  project_task_add_very_high/tests/__init__.py
  project_task_add_very_high/tests/test_project_task.py
  project_task_add_very_high/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1458 [18.0][FIX] project_timesheet_time_control: hide show_time_control
  project_timesheet_time_control/README.rst
  project_timesheet_time_control/readme/CONTRIBUTORS.md
  project_timesheet_time_control/static/description/index.html
  project_timesheet_time_control/views/account_analytic_line_view.xml
  project_timesheet_time_control/views/project_task_view.xml
Labels: bot is merging ⏳

#1462 [17.0][FIX] project_timesheet_time_control: invisible to column_invisible for tree view
  project_timesheet_time_control/views/account_analytic_line_view.xml
  project_timesheet_time_control/views/project_project_view.xml
  project_timesheet_time_control/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1464 [17.0][ADD] project_task_related: create module to add a non parent/child relationship beetween tasks
  project_task_related/README.rst
  project_task_related/__init__.py
  project_task_related/__manifest__.py
  project_task_related/i18n/es.po
  project_task_related/i18n/project_task_related.pot
  project_task_related/models/__init__.py
  project_task_related/models/project_task.py
  project_task_related/pyproject.toml
  project_task_related/readme/CONTRIBUTORS.md
  project_task_related/readme/DESCRIPTION.md
  project_task_related/static/description/index.html
  project_task_related/tests/__init__.py
  project_task_related/tests/test_project_task_related.py
  project_task_related/views/project_task_views_related.xml
Labels: bot is merging ⏳

#1461 [16.0][IMP] project_task_name_with_id: improve searching
  project_task_name_with_id/models/project_task.py
Labels: approved, ready to merge, bot is merging ⏳

#1463 [16.0][IMP] project_stock: Support for analytical account not accessible byrules
  project_stock/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1467 [16.0][ADD] project_task_parent_due_auto: Updates parent task due date when child due date changes.
  project_task_parent_due_auto/README.rst
  project_task_parent_due_auto/__init__.py
  project_task_parent_due_auto/__manifest__.py
  project_task_parent_due_auto/models/__init__.py
  project_task_parent_due_auto/models/project_task.py
  project_task_parent_due_auto/readme/CONTRIBUTORS.rst
  project_task_parent_due_auto/readme/DESCRIPTION.rst
  project_task_parent_due_auto/static/description/index.html
  project_task_parent_due_auto/tests/__init__.py
  project_task_parent_due_auto/tests/test_parent_due_auto.py
  setup/project_task_parent_due_auto/odoo/addons/project_task_parent_due_auto
  setup/project_task_parent_due_auto/setup.py
Labels: approved

#1469 [17.0][IMP] project_task_related: show only same client tasks by default
  project_task_related/i18n/es.po
  project_task_related/i18n/project_task_related.pot
  project_task_related/views/project_task_views_related.xml
Labels: bot is merging ⏳

#1470 [16.0][ADD] project_task_parent_completion_blocking: parent can't be completed if all childs aren't completed.
  project_task_parent_completion_blocking/README.rst
  project_task_parent_completion_blocking/__init__.py
  project_task_parent_completion_blocking/__manifest__.py
  project_task_parent_completion_blocking/i18n/es.po
  project_task_parent_completion_blocking/i18n/project_task_parent_completion_blocking.pot
  project_task_parent_completion_blocking/models/__init__.py
  project_task_parent_completion_blocking/models/project_task.py
  project_task_parent_completion_blocking/readme/CONTRIBUTORS.rst
  project_task_parent_completion_blocking/readme/DESCRIPTION.rst
  project_task_parent_completion_blocking/static/description/index.html
  project_task_parent_completion_blocking/tests/__init__.py
  project_task_parent_completion_blocking/tests/test_project_task_parent_completion_blocking.py
  setup/project_task_parent_completion_blocking/odoo/addons/project_task_parent_completion_blocking
  setup/project_task_parent_completion_blocking/setup.py
Labels: approved, bot is merging ⏳

#1471 [17.0][MIG] project_version: Migration to 17.0
  project_version/README.rst
  project_version/__init__.py
  project_version/__manifest__.py
  project_version/i18n/es.po
  project_version/i18n/it.po
  project_version/i18n/project_version.pot
  project_version/models/__init__.py
  project_version/models/project_project.py
  project_version/models/project_task.py
  project_version/models/project_version.py
  project_version/pyproject.toml
  project_version/readme/CONTRIBUTORS.md
  project_version/readme/DESCRIPTION.md
  project_version/readme/USAGE.md
  project_version/security/ir.model.access.csv
  project_version/static/description/icon.png
  project_version/static/description/icon.svg
  project_version/static/description/index.html
  project_version/views/project_project_views.xml
  project_version/views/project_task_views.xml
  project_version/views/project_version_views.xml
Labels: approved, bot is merging ⏳

#1473 [17.0][FIX] project_timesheet_time_control: Correctly hide show_time_control in task form
  project_timesheet_time_control/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1474 [18.0][FIX] project_timesheet_time_control: Correctly hide show_time_control in task form
  project_timesheet_time_control/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#1468 [17.0][MIG] project_merge: Migration to 17.0
  project_merge/README.rst
  project_merge/__init__.py
  project_merge/__manifest__.py
  project_merge/i18n/it.po
  project_merge/i18n/project_merge.pot
  project_merge/pyproject.toml
  project_merge/readme/CONTRIBUTORS.md
  project_merge/readme/DESCRIPTION.md
  project_merge/readme/USAGE.md
  project_merge/security/ir.model.access.csv
  project_merge/static/description/icon.png
  project_merge/static/description/index.html
  project_merge/tests/__init__.py
  project_merge/tests/test_project_merge.py
  project_merge/wizard/__init__.py
  project_merge/wizard/project_task_merge.py
  project_merge/wizard/project_task_merge_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1454 [18.0][MIG] project_stock > project_task_stock: Migration to 18.0
  project_task_stock/README.rst
  project_task_stock/__init__.py
  project_task_stock/__manifest__.py
  project_task_stock/demo/project_data.xml
  project_task_stock/demo/stock_picking_type_data.xml
  project_task_stock/i18n/es.po
  project_task_stock/i18n/fr.po
  project_task_stock/i18n/hr.po
  project_task_stock/i18n/it.po
  project_task_stock/i18n/project_task_stock.pot
  project_task_stock/i18n/pt_BR.po
  project_task_stock/models/__init__.py
  project_task_stock/models/account_analytic_line.py
  project_task_stock/models/project_project.py
  project_task_stock/models/project_task.py
  project_task_stock/models/stock_move.py
  project_task_stock/models/stock_scrap.py
  project_task_stock/pyproject.toml
  project_task_stock/readme/CONFIGURE.md
  project_task_stock/readme/CONTRIBUTORS.md
  project_task_stock/readme/DESCRIPTION.md
  project_task_stock/readme/USAGE.md
  project_task_stock/static/description/icon.png
  project_task_stock/static/description/index.html
  project_task_stock/tests/__init__.py
  project_task_stock/tests/common.py
  project_task_stock/tests/test_project_task_stock.py
  project_task_stock/views/project_project_view.xml
  project_task_stock/views/project_task_type_view.xml
  project_task_stock/views/project_task_view.xml
  project_task_stock/views/stock_move_view.xml
  project_task_stock/views/stock_scrap_views.xml
Labels: approved, bot is merging ⏳
