Repository OCA/project, pull requests merged in 2025-07, with the labels that each got.

#1541 [16.0][FIX] project_timesheet_time_control: keep the date when it comes in the creation or writing values.
  project_timesheet_time_control/models/account_analytic_line.py
  project_timesheet_time_control/tests/test_project_timesheet_time_control.py
Labels: approved, bot is merging ⏳

#1547 [16.0][FIX] project_timesheet_time_control: Define the appropriate date if it is a str
  project_timesheet_time_control/models/account_analytic_line.py
  project_timesheet_time_control/tests/test_project_timesheet_time_control.py
Labels: bot is merging ⏳

#1405 [18.0][MIG] project_task_tag: Migration to 18.0
  project_task_tag/README.rst
  project_task_tag/__init__.py
  project_task_tag/__manifest__.py
  project_task_tag/i18n/it.po
  project_task_tag/i18n/project_task_tag.pot
  project_task_tag/pyproject.toml
  project_task_tag/readme/CONTRIBUTORS.md
  project_task_tag/readme/DESCRIPTION.md
  project_task_tag/static/description/icon.png
  project_task_tag/static/description/index.html
  project_task_tag/views/project_task.xml
Labels: approved, bot is merging ⏳

#1408 [18.0][MIG] sale_project_task_recurrency: Migration to 18.0
  sale_project_task_recurrency/README.rst
  sale_project_task_recurrency/__init__.py
  sale_project_task_recurrency/__manifest__.py
  sale_project_task_recurrency/i18n/es.po
  sale_project_task_recurrency/i18n/it.po
  sale_project_task_recurrency/i18n/sale_project_task_recurrency.pot
  sale_project_task_recurrency/models/__init__.py
  sale_project_task_recurrency/models/product_template.py
  sale_project_task_recurrency/models/sale_order_line.py
  sale_project_task_recurrency/pyproject.toml
  sale_project_task_recurrency/readme/CONFIGURE.md
  sale_project_task_recurrency/readme/CONTRIBUTORS.md
  sale_project_task_recurrency/readme/DESCRIPTION.md
  sale_project_task_recurrency/readme/USAGE.md
  sale_project_task_recurrency/static/description/icon.png
  sale_project_task_recurrency/static/description/index.html
  sale_project_task_recurrency/tests/__init__.py
  sale_project_task_recurrency/tests/test_product_task_recurrency.py
  sale_project_task_recurrency/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1524 [17.0][MIG] project_risk: Migration to 17.0
  project_risk/README.rst
  project_risk/__init__.py
  project_risk/__manifest__.py
  project_risk/data/project_risk_category_data.xml
  project_risk/data/project_risk_response_category_data.xml
  project_risk/i18n/es.po
  project_risk/i18n/it.po
  project_risk/i18n/project_risk.pot
  project_risk/i18n/sl.po
  project_risk/migration_version.rst
  project_risk/models/__init__.py
  project_risk/models/project_project.py
  project_risk/models/project_risk.py
  project_risk/models/project_risk_category.py
  project_risk/models/project_risk_response.py
  project_risk/models/project_risk_response_category.py
  project_risk/pyproject.toml
  project_risk/readme/CONFIGURE.md
  project_risk/readme/CONTRIBUTORS.md
  project_risk/readme/DESCRIPTION.md
  project_risk/readme/ROADMAP.md
  project_risk/readme/USAGE.md
  project_risk/security/ir_model_access.xml
  project_risk/static/description/icon.png
  project_risk/static/description/index.html
  project_risk/static/description/matrix.png
  project_risk/tests/__init__.py
  project_risk/tests/test_project_risk.py
  project_risk/views/menuitems.xml
  project_risk/views/project_project_view.xml
  project_risk/views/project_risk_category_view.xml
  project_risk/views/project_risk_response_category_view.xml
  project_risk/views/project_risk_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1525 [18.0][MIG] project_merge: Migration to 18.0
  project_merge/README.rst
  project_merge/__init__.py
  project_merge/__manifest__.py
  project_merge/i18n/it.po
  project_merge/i18n/project_merge.pot
  project_merge/pyproject.toml
  project_merge/readme/CONTRIBUTORS.md
  project_merge/readme/DESCRIPTION.md
  project_merge/readme/USAGE.md
  project_merge/security/ir.model.access.csv
  project_merge/static/description/icon.png
  project_merge/static/description/index.html
  project_merge/tests/__init__.py
  project_merge/tests/test_project_task_merge.py
  project_merge/wizard/__init__.py
  project_merge/wizard/project_task_merge.py
  project_merge/wizard/project_task_merge_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1397 [18.0][MIG] project_administrator_restricted_visibility: Migration to 18.0
  project_administrator_restricted_visibility/README.rst
  project_administrator_restricted_visibility/__init__.py
  project_administrator_restricted_visibility/__manifest__.py
  project_administrator_restricted_visibility/hooks.py
  project_administrator_restricted_visibility/i18n/it.po
  project_administrator_restricted_visibility/i18n/project_administrator_restricted_visibility.pot
  project_administrator_restricted_visibility/pyproject.toml
  project_administrator_restricted_visibility/readme/CONFIGURE.md
  project_administrator_restricted_visibility/readme/CONTRIBUTORS.md
  project_administrator_restricted_visibility/readme/DESCRIPTION.md
  project_administrator_restricted_visibility/readme/USAGE.md
  project_administrator_restricted_visibility/security/project_security.xml
  project_administrator_restricted_visibility/static/description/icon.png
  project_administrator_restricted_visibility/static/description/index.html
  project_administrator_restricted_visibility/tests/__init__.py
  project_administrator_restricted_visibility/tests/test_project_administrator_restricted_visibility.py
  project_administrator_restricted_visibility/tests/test_uninstall_hook.py
Labels: approved, bot is merging ⏳
