Repository OCA/project, pull requests merged in 2025-03, with the labels that each got.

#1399 [18.0][MIG] project_parent: Migration to 18.0
  project_parent/README.rst
  project_parent/__init__.py
  project_parent/__manifest__.py
  project_parent/demo/project_project_demo.xml
  project_parent/i18n/es.po
  project_parent/i18n/fr.po
  project_parent/i18n/hr.po
  project_parent/i18n/it.po
  project_parent/i18n/nl.po
  project_parent/i18n/nl_NL.po
  project_parent/i18n/project_parent.pot
  project_parent/i18n/pt_BR.po
  project_parent/i18n/sl.po
  project_parent/models/__init__.py
  project_parent/models/project_project.py
  project_parent/pyproject.toml
  project_parent/readme/CONTRIBUTORS.md
  project_parent/readme/DESCRIPTION.md
  project_parent/readme/USAGE.md
  project_parent/static/description/icon.png
  project_parent/static/description/index.html
  project_parent/tests/__init__.py
  project_parent/tests/test_project_parent.py
  project_parent/views/project_parent_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1424 [17.0] [MIG] project_key: Migration to 17.0
  project_key/README.rst
  project_key/__init__.py
  project_key/__manifest__.py
  project_key/controllers/__init__.py
  project_key/controllers/main.py
  project_key/hooks.py
  project_key/i18n/de.po
  project_key/i18n/es_AR.po
  project_key/i18n/fr.po
  project_key/i18n/it.po
  project_key/i18n/project_key.pot
  project_key/models/__init__.py
  project_key/models/project_project.py
  project_key/models/project_task.py
  project_key/pyproject.toml
  project_key/readme/CONTRIBUTORS.md
  project_key/readme/DESCRIPTION.md
  project_key/readme/USAGE.md
  project_key/static/description/icon.png
  project_key/static/description/index.html
  project_key/tests/__init__.py
  project_key/tests/test_common.py
  project_key/tests/test_controller.py
  project_key/tests/test_project.py
  project_key/tests/test_task.py
  project_key/views/project_key_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1439 [16.0][ADD] project_task_description_portal
  project_task_description_portal/README.rst
  project_task_description_portal/__init__.py
  project_task_description_portal/__manifest__.py
  project_task_description_portal/controllers/__init__.py
  project_task_description_portal/controllers/portal.py
  project_task_description_portal/models/__init__.py
  project_task_description_portal/models/project_task.py
  project_task_description_portal/readme/CONFIGURE.md
  project_task_description_portal/readme/CONTEXT.md
  project_task_description_portal/readme/CONTRIBUTORS.md
  project_task_description_portal/readme/DESCRIPTION.md
  project_task_description_portal/readme/ROADMAP.md
  project_task_description_portal/readme/USAGE.md
  project_task_description_portal/static/description/icon.png
  project_task_description_portal/static/description/img/portal_description.png
  project_task_description_portal/static/description/img/portal_view.png
  project_task_description_portal/static/description/img/use_portal_description.png
  project_task_description_portal/static/description/index.html
  project_task_description_portal/views/project_portal_templates.xml
  project_task_description_portal/views/project_task_views.xml
  setup/project_task_description_portal/odoo/addons/project_task_description_portal
  setup/project_task_description_portal/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1426 [17.0][MIG] project_parent_task_filter: Migration to 17.0
  project_parent_task_filter/README.rst
  project_parent_task_filter/__init__.py
  project_parent_task_filter/__manifest__.py
  project_parent_task_filter/i18n/ca.po
  project_parent_task_filter/i18n/de.po
  project_parent_task_filter/i18n/es.po
  project_parent_task_filter/i18n/es_AR.po
  project_parent_task_filter/i18n/es_ES.po
  project_parent_task_filter/i18n/fr.po
  project_parent_task_filter/i18n/fr_FR.po
  project_parent_task_filter/i18n/it.po
  project_parent_task_filter/i18n/nl_NL.po
  project_parent_task_filter/i18n/project_parent_task_filter.pot
  project_parent_task_filter/i18n/pt_BR.po
  project_parent_task_filter/pyproject.toml
  project_parent_task_filter/readme/CONTRIBUTORS.md
  project_parent_task_filter/readme/DESCRIPTION.md
  project_parent_task_filter/readme/ROADMAP.md
  project_parent_task_filter/readme/USAGE.md
  project_parent_task_filter/static/description/icon.png
  project_parent_task_filter/static/description/index.html
  project_parent_task_filter/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#1446 [17.0][FIX] project_task_default_stage: Do not set user_id on default stages
  project_task_default_stage/__manifest__.py
  project_task_default_stage/data/project_data.xml
  project_task_default_stage/migrations/17.0.1.0.1/post-migration.py
Labels: bot is merging ⏳

#1435 [17.0][MIG] project_template: Migration to 17.0
  project_template/README.rst
  project_template/__init__.py
  project_template/__manifest__.py
  project_template/i18n/de.po
  project_template/i18n/es.po
  project_template/i18n/es_AR.po
  project_template/i18n/fr.po
  project_template/i18n/fr_FR.po
  project_template/i18n/he.po
  project_template/i18n/hr.po
  project_template/i18n/it.po
  project_template/i18n/nl.po
  project_template/i18n/project_template.pot
  project_template/i18n/pt.po
  project_template/i18n/pt_BR.po
  project_template/i18n/sl.po
  project_template/i18n/sv.po
  project_template/models/__init__.py
  project_template/models/project.py
  project_template/models/project_task.py
  project_template/pyproject.toml
  project_template/readme/CONTRIBUTORS.md
  project_template/readme/DESCRIPTION.md
  project_template/readme/USAGE.md
  project_template/static/description/icon.png
  project_template/static/description/index.html
  project_template/tests/__init__.py
  project_template/tests/test_project_template.py
  project_template/views/project.xml
Labels: approved, bot is merging ⏳

#1449 [18.0][MIG] project_tag_hierarchy: Migration to 18.0
  project_tag_hierarchy/README.rst
  project_tag_hierarchy/__init__.py
  project_tag_hierarchy/__manifest__.py
  project_tag_hierarchy/i18n/es.po
  project_tag_hierarchy/i18n/it.po
  project_tag_hierarchy/i18n/project_tag_hierarchy.pot
  project_tag_hierarchy/models/__init__.py
  project_tag_hierarchy/models/project_tags.py
  project_tag_hierarchy/pyproject.toml
  project_tag_hierarchy/readme/CONTRIBUTORS.md
  project_tag_hierarchy/readme/DESCRIPTION.md
  project_tag_hierarchy/static/description/icon.png
  project_tag_hierarchy/static/description/index.html
  project_tag_hierarchy/tests/__init__.py
  project_tag_hierarchy/tests/test_project_tag_hierarchy.py
  project_tag_hierarchy/views/project_tags_views.xml
Labels: approved, bot is merging ⏳

#1450 [18.0][MIG] project_tag_multicompany: Migration to 18.0
  project_tag_multicompany/README.rst
  project_tag_multicompany/__init__.py
  project_tag_multicompany/__manifest__.py
  project_tag_multicompany/i18n/es.po
  project_tag_multicompany/i18n/it.po
  project_tag_multicompany/i18n/project_tag_multicompany.pot
  project_tag_multicompany/models/__init__.py
  project_tag_multicompany/models/project_tags.py
  project_tag_multicompany/pyproject.toml
  project_tag_multicompany/readme/CONTRIBUTORS.md
  project_tag_multicompany/readme/DESCRIPTION.md
  project_tag_multicompany/security/project_tags_security.xml
  project_tag_multicompany/static/description/icon.png
  project_tag_multicompany/static/description/index.html
  project_tag_multicompany/views/project_tags_views.xml
Labels: approved, bot is merging ⏳

#1451 [18.0][MIG] project_tag_security: Migration to 18.0
  project_tag_security/README.rst
  project_tag_security/__init__.py
  project_tag_security/__manifest__.py
  project_tag_security/i18n/es.po
  project_tag_security/i18n/it.po
  project_tag_security/i18n/project_tag_security.pot
  project_tag_security/models/__init__.py
  project_tag_security/models/project_project.py
  project_tag_security/models/project_tags.py
  project_tag_security/models/project_task.py
  project_tag_security/pyproject.toml
  project_tag_security/readme/CONTRIBUTORS.md
  project_tag_security/readme/DESCRIPTION.md
  project_tag_security/readme/USAGE.md
  project_tag_security/static/description/icon.png
  project_tag_security/static/description/index.html
  project_tag_security/tests/__init__.py
  project_tag_security/tests/test_project_tag_security.py
  project_tag_security/views/project_tags_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1453 [18.0][MIG] project_stage_last_update_date: Migration to 18.0
  project_stage_last_update_date/README.rst
  project_stage_last_update_date/__init__.py
  project_stage_last_update_date/__manifest__.py
  project_stage_last_update_date/i18n/es.po
  project_stage_last_update_date/i18n/it.po
  project_stage_last_update_date/i18n/project_stage_last_update_date.pot
  project_stage_last_update_date/models/__init__.py
  project_stage_last_update_date/models/project_project.py
  project_stage_last_update_date/pyproject.toml
  project_stage_last_update_date/readme/CONTRIBUTORS.md
  project_stage_last_update_date/readme/DESCRIPTION.md
  project_stage_last_update_date/static/description/icon.png
  project_stage_last_update_date/static/description/index.html
  project_stage_last_update_date/tests/__init__.py
  project_stage_last_update_date/tests/test_project.py
  project_stage_last_update_date/views/project_project_views.xml
Labels: approved, bot is merging ⏳

#1455 [18.0][MIG] project_pivot: Migration to 18.0
  project_pivot/README.rst
  project_pivot/__init__.py
  project_pivot/__manifest__.py
  project_pivot/i18n/it.po
  project_pivot/i18n/project_pivot.pot
  project_pivot/pyproject.toml
  project_pivot/readme/CONTRIBUTORS.md
  project_pivot/readme/DESCRIPTION.md
  project_pivot/readme/ROADMAP.md
  project_pivot/static/description/icon.png
  project_pivot/static/description/index.html
  project_pivot/views/project_project.xml
Labels: approved, bot is merging ⏳
